default_color_bg=0x272822
default_color_fg=0xF8F8F2
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=0x272822
dialog_color_fg=0xF8F8F2
dialog_shaded_color_bg=0x272822
dialog_shaded_color_fg=0x75715E
entry_attr=
entry_color_bg=0x272822
entry_color_fg=0xF8F8F2
help_attr=bold
help_color_bg=0xA6E22E
help_color_fg=0x272822
history_name_attr=bold
history_name_attr_selected=reverse
history_name_recv_color_bg=
history_name_recv_color_fg=0x66D9EF
history_name_recv_group_color_bg=
history_name_recv_group_color_fg=0xAE81FF
history_name_sent_color_bg=
history_name_sent_color_fg=0xA6E22E
history_text_attachment_color_bg=
history_text_attachment_color_fg=0xE6DB74
history_text_attr=
history_text_attr_selected=reverse
history_text_quoted_color_bg=
history_text_quoted_color_fg=0x75715E
history_text_reaction_color_bg=
history_text_reaction_color_fg=0xFD971F
history_text_recv_color_bg=
history_text_recv_color_fg=0xF8F8F2
history_text_recv_group_color_bg=
history_text_recv_group_color_fg=0xF8F8F2
history_text_sent_color_bg=
history_text_sent_color_fg=0xF8F8F2
list_attr=
list_attr_selected=reverse
list_color_bg=0x272822
list_color_fg=0xF8F8F2
list_color_unread_bg=
list_color_unread_fg=0xE6DB74
listborder_attr=
listborder_color_bg=0x272822
listborder_color_fg=0x75715E
status_attr=reverse
status_color_bg=0x3E3D32
status_color_fg=0xF8F8F2
top_attr=reverse
top_color_bg=0x272822
top_color_fg=0xA6E22E
