// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/resources/resources.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sort order for process listing.
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	// Sort by CPU usage (highest first).
	SortOrder_SORT_ORDER_CPU SortOrder = 1
	// Sort by memory usage (highest first).
	SortOrder_SORT_ORDER_MEMORY SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_CPU",
		2: "SORT_ORDER_MEMORY",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_CPU":         1,
		"SORT_ORDER_MEMORY":      2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{0}
}

// Type of system resource for historical data queries.
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	// RAM/memory usage data.
	ResourceType_RESOURCE_TYPE_RAM ResourceType = 1
	// CPU utilization data.
	ResourceType_RESOURCE_TYPE_CPU ResourceType = 2
	// Disk usage data.
	ResourceType_RESOURCE_TYPE_DISK ResourceType = 3
	// CPU temperature data.
	ResourceType_RESOURCE_TYPE_CPU_TEMP ResourceType = 4
	// Battery level data.
	ResourceType_RESOURCE_TYPE_BATTERY ResourceType = 5
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_RAM",
		2: "RESOURCE_TYPE_CPU",
		3: "RESOURCE_TYPE_DISK",
		4: "RESOURCE_TYPE_CPU_TEMP",
		5: "RESOURCE_TYPE_BATTERY",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_RAM":         1,
		"RESOURCE_TYPE_CPU":         2,
		"RESOURCE_TYPE_DISK":        3,
		"RESOURCE_TYPE_CPU_TEMP":    4,
		"RESOURCE_TYPE_BATTERY":     5,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{1}
}

// Unit of measurement for metric values.
type Unit int32

const (
	Unit_UNIT_UNSPECIFIED Unit = 0
	// Percentage value (0-100).
	Unit_UNIT_PERCENT Unit = 1
	// Degrees Celsius.
	Unit_UNIT_CELSIUS Unit = 2
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "UNIT_UNSPECIFIED",
		1: "UNIT_PERCENT",
		2: "UNIT_CELSIUS",
	}
	Unit_value = map[string]int32{
		"UNIT_UNSPECIFIED": 0,
		"UNIT_PERCENT":     1,
		"UNIT_CELSIUS":     2,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[2].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[2]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{2}
}

// Linux process state as reported by the kernel.
type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	// Currently running or runnable.
	ProcessState_PROCESS_STATE_RUNNING ProcessState = 1
	// Sleeping in an interruptible wait.
	ProcessState_PROCESS_STATE_SLEEPING ProcessState = 2
	// Uninterruptible disk sleep (D state).
	ProcessState_PROCESS_STATE_DISK_SLEEP ProcessState = 3
	// Zombie — terminated but not yet reaped by parent.
	ProcessState_PROCESS_STATE_ZOMBIE ProcessState = 4
	// Stopped (SIGSTOP or TTY input).
	ProcessState_PROCESS_STATE_STOPPED ProcessState = 5
	// Tracing stop (ptrace).
	ProcessState_PROCESS_STATE_TRACE_STOP ProcessState = 6
	// Dead (should not be visible).
	ProcessState_PROCESS_STATE_DEAD ProcessState = 7
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_RUNNING",
		2: "PROCESS_STATE_SLEEPING",
		3: "PROCESS_STATE_DISK_SLEEP",
		4: "PROCESS_STATE_ZOMBIE",
		5: "PROCESS_STATE_STOPPED",
		6: "PROCESS_STATE_TRACE_STOP",
		7: "PROCESS_STATE_DEAD",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_RUNNING":     1,
		"PROCESS_STATE_SLEEPING":    2,
		"PROCESS_STATE_DISK_SLEEP":  3,
		"PROCESS_STATE_ZOMBIE":      4,
		"PROCESS_STATE_STOPPED":     5,
		"PROCESS_STATE_TRACE_STOP":  6,
		"PROCESS_STATE_DEAD":        7,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[3].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[3]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{3}
}

// Battery charge/discharge status as reported by the power supply subsystem.
type BatteryStatus int32

const (
	BatteryStatus_BATTERY_STATUS_UNSPECIFIED BatteryStatus = 0
	// Battery is currently charging.
	BatteryStatus_BATTERY_STATUS_CHARGING BatteryStatus = 1
	// Battery is discharging (on battery power).
	BatteryStatus_BATTERY_STATUS_DISCHARGING BatteryStatus = 2
	// Battery is fully charged.
	BatteryStatus_BATTERY_STATUS_FULL BatteryStatus = 3
	// Battery is not charging but also not full (e.g. charge threshold).
	BatteryStatus_BATTERY_STATUS_NOT_CHARGING BatteryStatus = 4
)

// Enum value maps for BatteryStatus.
var (
	BatteryStatus_name = map[int32]string{
		0: "BATTERY_STATUS_UNSPECIFIED",
		1: "BATTERY_STATUS_CHARGING",
		2: "BATTERY_STATUS_DISCHARGING",
		3: "BATTERY_STATUS_FULL",
		4: "BATTERY_STATUS_NOT_CHARGING",
	}
	BatteryStatus_value = map[string]int32{
		"BATTERY_STATUS_UNSPECIFIED":  0,
		"BATTERY_STATUS_CHARGING":     1,
		"BATTERY_STATUS_DISCHARGING":  2,
		"BATTERY_STATUS_FULL":         3,
		"BATTERY_STATUS_NOT_CHARGING": 4,
	}
)

func (x BatteryStatus) Enum() *BatteryStatus {
	p := new(BatteryStatus)
	*p = x
	return p
}

func (x BatteryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[4].Descriptor()
}

func (BatteryStatus) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[4]
}

func (x BatteryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryStatus.Descriptor instead.
func (BatteryStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{4}
}

// ASUS performance profile as reported by asusctl.
type ASUSProfile int32

const (
	ASUSProfile_ASUS_PROFILE_UNSPECIFIED ASUSProfile = 0
	// Performance mode (high power).
	ASUSProfile_ASUS_PROFILE_PERF ASUSProfile = 1
	// Balanced mode.
	ASUSProfile_ASUS_PROFILE_BAL ASUSProfile = 2
	// Quiet mode (low power, low fan).
	ASUSProfile_ASUS_PROFILE_QUIET ASUSProfile = 3
)

// Enum value maps for ASUSProfile.
var (
	ASUSProfile_name = map[int32]string{
		0: "ASUS_PROFILE_UNSPECIFIED",
		1: "ASUS_PROFILE_PERF",
		2: "ASUS_PROFILE_BAL",
		3: "ASUS_PROFILE_QUIET",
	}
	ASUSProfile_value = map[string]int32{
		"ASUS_PROFILE_UNSPECIFIED": 0,
		"ASUS_PROFILE_PERF":        1,
		"ASUS_PROFILE_BAL":         2,
		"ASUS_PROFILE_QUIET":       3,
	}
)

func (x ASUSProfile) Enum() *ASUSProfile {
	p := new(ASUSProfile)
	*p = x
	return p
}

func (x ASUSProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASUSProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[5].Descriptor()
}

func (ASUSProfile) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[5]
}

func (x ASUSProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASUSProfile.Descriptor instead.
func (ASUSProfile) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{5}
}

// GPU mode as detected from the ASUS nv-wmi driver.
type GPUProfile int32

const (
	GPUProfile_GPU_PROFILE_UNSPECIFIED GPUProfile = 0
	// External GPU connected via Thunderbolt.
	GPUProfile_GPU_PROFILE_EGPU GPUProfile = 1
	// Dedicated NVIDIA GPU active (mux switched).
	GPUProfile_GPU_PROFILE_NVIDIA GPUProfile = 2
	// Integrated GPU only (dGPU disabled).
	GPUProfile_GPU_PROFILE_IGPU GPUProfile = 3
	// Hybrid mode (iGPU + dGPU, dynamic switching).
	GPUProfile_GPU_PROFILE_HYBRID GPUProfile = 4
)

// Enum value maps for GPUProfile.
var (
	GPUProfile_name = map[int32]string{
		0: "GPU_PROFILE_UNSPECIFIED",
		1: "GPU_PROFILE_EGPU",
		2: "GPU_PROFILE_NVIDIA",
		3: "GPU_PROFILE_IGPU",
		4: "GPU_PROFILE_HYBRID",
	}
	GPUProfile_value = map[string]int32{
		"GPU_PROFILE_UNSPECIFIED": 0,
		"GPU_PROFILE_EGPU":        1,
		"GPU_PROFILE_NVIDIA":      2,
		"GPU_PROFILE_IGPU":        3,
		"GPU_PROFILE_HYBRID":      4,
	}
)

func (x GPUProfile) Enum() *GPUProfile {
	p := new(GPUProfile)
	*p = x
	return p
}

func (x GPUProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_resources_resources_proto_enumTypes[6].Descriptor()
}

func (GPUProfile) Type() protoreflect.EnumType {
	return &file_proto_resources_resources_proto_enumTypes[6]
}

func (x GPUProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUProfile.Descriptor instead.
func (GPUProfile) EnumDescriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{6}
}

// CurrentRequest is empty. Current returns the latest snapshot.
type CurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRequest) Reset() {
	*x = CurrentRequest{}
	mi := &file_proto_resources_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRequest) ProtoMessage() {}

func (x *CurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRequest.ProtoReflect.Descriptor instead.
func (*CurrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{0}
}

// WatchRequest specifies which resources the client wants to monitor.
// Only fields with filter=true are checked for changes; updates are
// streamed when any watched field differs from the previous poll.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter controlling which resources trigger stream updates.
	Filter        *WatchFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_resources_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{1}
}

func (x *WatchRequest) GetFilter() *WatchFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// WatchFilter selects which resources the client is interested in.
// Only set fields to true for the resources you want to watch.
type WatchFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RAM usage percentage changes.
	Ram bool `protobuf:"varint,1,opt,name=ram,proto3" json:"ram,omitempty"`
	// CPU usage percentage changes.
	Cpu bool `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Root disk usage percentage changes.
	Disk bool `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	// Disk I/O statistics changes.
	DiskIo bool `protobuf:"varint,4,opt,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	// CPU temperature changes.
	CpuTemp bool `protobuf:"varint,5,opt,name=cpu_temp,json=cpuTemp,proto3" json:"cpu_temp,omitempty"`
	// Battery level or status changes.
	Battery bool `protobuf:"varint,6,opt,name=battery,proto3" json:"battery,omitempty"`
	// WiFi signal or SSID changes.
	Wifi bool `protobuf:"varint,7,opt,name=wifi,proto3" json:"wifi,omitempty"`
	// ASUS performance profile changes.
	AsusProfile bool `protobuf:"varint,8,opt,name=asus_profile,json=asusProfile,proto3" json:"asus_profile,omitempty"`
	// GPU mode changes.
	GpuProfile bool `protobuf:"varint,9,opt,name=gpu_profile,json=gpuProfile,proto3" json:"gpu_profile,omitempty"`
	// Keyboard layout changes.
	KeyboardLayout bool `protobuf:"varint,10,opt,name=keyboard_layout,json=keyboardLayout,proto3" json:"keyboard_layout,omitempty"`
	// Top CPU/memory process name changes.
	TopProcesses  bool `protobuf:"varint,11,opt,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFilter) Reset() {
	*x = WatchFilter{}
	mi := &file_proto_resources_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFilter) ProtoMessage() {}

func (x *WatchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFilter.ProtoReflect.Descriptor instead.
func (*WatchFilter) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{2}
}

func (x *WatchFilter) GetRam() bool {
	if x != nil {
		return x.Ram
	}
	return false
}

func (x *WatchFilter) GetCpu() bool {
	if x != nil {
		return x.Cpu
	}
	return false
}

func (x *WatchFilter) GetDisk() bool {
	if x != nil {
		return x.Disk
	}
	return false
}

func (x *WatchFilter) GetDiskIo() bool {
	if x != nil {
		return x.DiskIo
	}
	return false
}

func (x *WatchFilter) GetCpuTemp() bool {
	if x != nil {
		return x.CpuTemp
	}
	return false
}

func (x *WatchFilter) GetBattery() bool {
	if x != nil {
		return x.Battery
	}
	return false
}

func (x *WatchFilter) GetWifi() bool {
	if x != nil {
		return x.Wifi
	}
	return false
}

func (x *WatchFilter) GetAsusProfile() bool {
	if x != nil {
		return x.AsusProfile
	}
	return false
}

func (x *WatchFilter) GetGpuProfile() bool {
	if x != nil {
		return x.GpuProfile
	}
	return false
}

func (x *WatchFilter) GetKeyboardLayout() bool {
	if x != nil {
		return x.KeyboardLayout
	}
	return false
}

func (x *WatchFilter) GetTopProcesses() bool {
	if x != nil {
		return x.TopProcesses
	}
	return false
}

// CurrentResponse contains the latest snapshot of all resources.
type CurrentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RAM usage snapshot.
	Ram *RAMSnapshot `protobuf:"bytes,1,opt,name=ram,proto3" json:"ram,omitempty"`
	// CPU usage snapshot with per-type breakdown.
	Cpu *CPUSnapshot `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Root disk partition usage.
	Disk *DiskSnapshot `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
	// Primary block device I/O statistics.
	DiskIo *DiskIOSnapshot `protobuf:"bytes,4,opt,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	// CPU temperature snapshot from thermal sensors.
	CpuTemp *CPUTempSnapshot `protobuf:"bytes,5,opt,name=cpu_temp,json=cpuTemp,proto3" json:"cpu_temp,omitempty"`
	// Battery status snapshot (level, charging, plugged).
	Battery *BatterySnapshot `protobuf:"bytes,6,opt,name=battery,proto3" json:"battery,omitempty"`
	// WiFi signal snapshot (strength, SSID).
	Wifi *WiFiSnapshot `protobuf:"bytes,7,opt,name=wifi,proto3" json:"wifi,omitempty"`
	// ASUS performance profile.
	AsusProfile ASUSProfile `protobuf:"varint,8,opt,name=asus_profile,json=asusProfile,proto3,enum=resources.ASUSProfile" json:"asus_profile,omitempty"`
	// GPU mode.
	GpuProfile GPUProfile `protobuf:"varint,9,opt,name=gpu_profile,json=gpuProfile,proto3,enum=resources.GPUProfile" json:"gpu_profile,omitempty"`
	// Current keyboard layout (e.g., "us" or "es").
	KeyboardLayout string `protobuf:"bytes,10,opt,name=keyboard_layout,json=keyboardLayout,proto3" json:"keyboard_layout,omitempty"`
	// Name of the process with highest CPU usage.
	TopCpuProcess string `protobuf:"bytes,11,opt,name=top_cpu_process,json=topCpuProcess,proto3" json:"top_cpu_process,omitempty"`
	// Name of the process with highest memory usage.
	TopMemProcess string `protobuf:"bytes,12,opt,name=top_mem_process,json=topMemProcess,proto3" json:"top_mem_process,omitempty"`
	// Monotonic counter incremented on each poll cycle. Tmuxbar plugin
	// uses this to detect fresh data and trigger refresh-client.
	PollCount int64 `protobuf:"varint,13,opt,name=poll_count,json=pollCount,proto3" json:"poll_count,omitempty"`
	// System load average over the last 1 minute.
	LoadAverage_1 float64 `protobuf:"fixed64,14,opt,name=load_average_1,json=loadAverage1,proto3" json:"load_average_1,omitempty"`
	// System load average over the last 5 minutes.
	LoadAverage_5 float64 `protobuf:"fixed64,15,opt,name=load_average_5,json=loadAverage5,proto3" json:"load_average_5,omitempty"`
	// System load average over the last 15 minutes.
	LoadAverage_15 float64 `protobuf:"fixed64,16,opt,name=load_average_15,json=loadAverage15,proto3" json:"load_average_15,omitempty"`
	// System uptime in seconds since boot.
	UptimeSeconds float64 `protobuf:"fixed64,17,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Total number of processes on the system.
	ProcessCount int32 `protobuf:"varint,18,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	// Total number of threads on the system.
	ThreadCount int32 `protobuf:"varint,19,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	// Number of processes currently running (state R).
	RunningProcessCount int32 `protobuf:"varint,20,opt,name=running_process_count,json=runningProcessCount,proto3" json:"running_process_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CurrentResponse) Reset() {
	*x = CurrentResponse{}
	mi := &file_proto_resources_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentResponse) ProtoMessage() {}

func (x *CurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentResponse.ProtoReflect.Descriptor instead.
func (*CurrentResponse) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentResponse) GetRam() *RAMSnapshot {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *CurrentResponse) GetCpu() *CPUSnapshot {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *CurrentResponse) GetDisk() *DiskSnapshot {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *CurrentResponse) GetDiskIo() *DiskIOSnapshot {
	if x != nil {
		return x.DiskIo
	}
	return nil
}

func (x *CurrentResponse) GetCpuTemp() *CPUTempSnapshot {
	if x != nil {
		return x.CpuTemp
	}
	return nil
}

func (x *CurrentResponse) GetBattery() *BatterySnapshot {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *CurrentResponse) GetWifi() *WiFiSnapshot {
	if x != nil {
		return x.Wifi
	}
	return nil
}

func (x *CurrentResponse) GetAsusProfile() ASUSProfile {
	if x != nil {
		return x.AsusProfile
	}
	return ASUSProfile_ASUS_PROFILE_UNSPECIFIED
}

func (x *CurrentResponse) GetGpuProfile() GPUProfile {
	if x != nil {
		return x.GpuProfile
	}
	return GPUProfile_GPU_PROFILE_UNSPECIFIED
}

func (x *CurrentResponse) GetKeyboardLayout() string {
	if x != nil {
		return x.KeyboardLayout
	}
	return ""
}

func (x *CurrentResponse) GetTopCpuProcess() string {
	if x != nil {
		return x.TopCpuProcess
	}
	return ""
}

func (x *CurrentResponse) GetTopMemProcess() string {
	if x != nil {
		return x.TopMemProcess
	}
	return ""
}

func (x *CurrentResponse) GetPollCount() int64 {
	if x != nil {
		return x.PollCount
	}
	return 0
}

func (x *CurrentResponse) GetLoadAverage_1() float64 {
	if x != nil {
		return x.LoadAverage_1
	}
	return 0
}

func (x *CurrentResponse) GetLoadAverage_5() float64 {
	if x != nil {
		return x.LoadAverage_5
	}
	return 0
}

func (x *CurrentResponse) GetLoadAverage_15() float64 {
	if x != nil {
		return x.LoadAverage_15
	}
	return 0
}

func (x *CurrentResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *CurrentResponse) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *CurrentResponse) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *CurrentResponse) GetRunningProcessCount() int32 {
	if x != nil {
		return x.RunningProcessCount
	}
	return 0
}

// Request to list top processes by resource usage.
type TopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of processes to return (default: 10).
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Sort order for process listing. Unset means CPU sort.
	Sort          SortOrder `protobuf:"varint,2,opt,name=sort,proto3,enum=resources.SortOrder" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_proto_resources_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{4}
}

func (x *TopRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopRequest) GetSort() SortOrder {
	if x != nil {
		return x.Sort
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// TopResponse contains the list of top processes.
type TopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Top processes sorted by the requested metric.
	Processes     []*ProcessInfo `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopResponse) Reset() {
	*x = TopResponse{}
	mi := &file_proto_resources_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopResponse) ProtoMessage() {}

func (x *TopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopResponse.ProtoReflect.Descriptor instead.
func (*TopResponse) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{5}
}

func (x *TopResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Request to query detailed process information.
type PSRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter to a specific process PID. Empty means list all processes.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Number of processes to return (default: 20).
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Sort order for process listing. Unset means CPU sort.
	Sort          SortOrder `protobuf:"varint,3,opt,name=sort,proto3,enum=resources.SortOrder" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSRequest) Reset() {
	*x = PSRequest{}
	mi := &file_proto_resources_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSRequest) ProtoMessage() {}

func (x *PSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSRequest.ProtoReflect.Descriptor instead.
func (*PSRequest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{6}
}

func (x *PSRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PSRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PSRequest) GetSort() SortOrder {
	if x != nil {
		return x.Sort
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

// PSResponse contains detailed process information.
type PSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process list matching the query criteria.
	Processes     []*ProcessInfo `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSResponse) Reset() {
	*x = PSResponse{}
	mi := &file_proto_resources_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSResponse) ProtoMessage() {}

func (x *PSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSResponse.ProtoReflect.Descriptor instead.
func (*PSResponse) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{7}
}

func (x *PSResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// Request for historical resource data.
type HistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource to query. Unset means RAM.
	Resource ResourceType `protobuf:"varint,1,opt,name=resource,proto3,enum=resources.ResourceType" json:"resource,omitempty"`
	// Number of data points to return (default: 20, max: 100).
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_proto_resources_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryRequest) GetResource() ResourceType {
	if x != nil {
		return x.Resource
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *HistoryRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// HistoryResponse contains time-series data for a resource.
type HistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data point values in chronological order (oldest first).
	Values []float64 `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	// The resource these values correspond to.
	Resource ResourceType `protobuf:"varint,2,opt,name=resource,proto3,enum=resources.ResourceType" json:"resource,omitempty"`
	// Unit of measurement for the values.
	Unit          Unit `protobuf:"varint,3,opt,name=unit,proto3,enum=resources.Unit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_resources_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{9}
}

func (x *HistoryResponse) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *HistoryResponse) GetResource() ResourceType {
	if x != nil {
		return x.Resource
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *HistoryResponse) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

// RAMSnapshot captures memory usage at a point in time.
type RAMSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total physical RAM in MB.
	TotalMb float64 `protobuf:"fixed64,1,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	// Currently used RAM in MB (excluding buffers/cache).
	UsedMb float64 `protobuf:"fixed64,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	// Available RAM in MB (includes buffers/cache reclaimable by apps).
	AvailableMb float64 `protobuf:"fixed64,3,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	// RAM usage as percentage of total.
	Percent       float64 `protobuf:"fixed64,4,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAMSnapshot) Reset() {
	*x = RAMSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAMSnapshot) ProtoMessage() {}

func (x *RAMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAMSnapshot.ProtoReflect.Descriptor instead.
func (*RAMSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{10}
}

func (x *RAMSnapshot) GetTotalMb() float64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *RAMSnapshot) GetUsedMb() float64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *RAMSnapshot) GetAvailableMb() float64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *RAMSnapshot) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// CPUSnapshot captures CPU utilization at a point in time.
type CPUSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU usage across all cores as percentage.
	TotalPercent float64 `protobuf:"fixed64,1,opt,name=total_percent,json=totalPercent,proto3" json:"total_percent,omitempty"`
	// CPU time spent in user space as percentage.
	UserPercent float64 `protobuf:"fixed64,2,opt,name=user_percent,json=userPercent,proto3" json:"user_percent,omitempty"`
	// CPU time spent in kernel space as percentage.
	SystemPercent float64 `protobuf:"fixed64,3,opt,name=system_percent,json=systemPercent,proto3" json:"system_percent,omitempty"`
	// CPU time waiting for I/O operations as percentage.
	IowaitPercent float64 `protobuf:"fixed64,4,opt,name=iowait_percent,json=iowaitPercent,proto3" json:"iowait_percent,omitempty"`
	// Number of logical CPU cores detected.
	NumCores int32 `protobuf:"varint,5,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	// Per-core CPU usage percentages, indexed from 0. Length equals num_cores.
	PerCorePercent []float64 `protobuf:"fixed64,6,rep,packed,name=per_core_percent,json=perCorePercent,proto3" json:"per_core_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CPUSnapshot) Reset() {
	*x = CPUSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUSnapshot) ProtoMessage() {}

func (x *CPUSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUSnapshot.ProtoReflect.Descriptor instead.
func (*CPUSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{11}
}

func (x *CPUSnapshot) GetTotalPercent() float64 {
	if x != nil {
		return x.TotalPercent
	}
	return 0
}

func (x *CPUSnapshot) GetUserPercent() float64 {
	if x != nil {
		return x.UserPercent
	}
	return 0
}

func (x *CPUSnapshot) GetSystemPercent() float64 {
	if x != nil {
		return x.SystemPercent
	}
	return 0
}

func (x *CPUSnapshot) GetIowaitPercent() float64 {
	if x != nil {
		return x.IowaitPercent
	}
	return 0
}

func (x *CPUSnapshot) GetNumCores() int32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *CPUSnapshot) GetPerCorePercent() []float64 {
	if x != nil {
		return x.PerCorePercent
	}
	return nil
}

// DiskSnapshot captures disk usage for the root partition.
type DiskSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mount point path (e.g., "/").
	MountPoint string `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Total disk capacity in GB.
	TotalGb float64 `protobuf:"fixed64,2,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"`
	// Used disk space in GB.
	UsedGb float64 `protobuf:"fixed64,3,opt,name=used_gb,json=usedGb,proto3" json:"used_gb,omitempty"`
	// Available disk space in GB.
	AvailGb float64 `protobuf:"fixed64,4,opt,name=avail_gb,json=availGb,proto3" json:"avail_gb,omitempty"`
	// Disk usage as percentage.
	Percent       float64 `protobuf:"fixed64,5,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSnapshot) Reset() {
	*x = DiskSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSnapshot) ProtoMessage() {}

func (x *DiskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSnapshot.ProtoReflect.Descriptor instead.
func (*DiskSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{12}
}

func (x *DiskSnapshot) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskSnapshot) GetTotalGb() float64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

func (x *DiskSnapshot) GetUsedGb() float64 {
	if x != nil {
		return x.UsedGb
	}
	return 0
}

func (x *DiskSnapshot) GetAvailGb() float64 {
	if x != nil {
		return x.AvailGb
	}
	return 0
}

func (x *DiskSnapshot) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// DiskIOSnapshot captures block device I/O metrics.
type DiskIOSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block device name (e.g., "nvme0n1" or "sda").
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// Read operations per second.
	ReadsPerSec float64 `protobuf:"fixed64,2,opt,name=reads_per_sec,json=readsPerSec,proto3" json:"reads_per_sec,omitempty"`
	// Write operations per second.
	WritesPerSec float64 `protobuf:"fixed64,3,opt,name=writes_per_sec,json=writesPerSec,proto3" json:"writes_per_sec,omitempty"`
	// Bytes read per second.
	ReadBytesPerSec float64 `protobuf:"fixed64,4,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	// Bytes written per second.
	WriteBytesPerSec float64 `protobuf:"fixed64,5,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiskIOSnapshot) Reset() {
	*x = DiskIOSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOSnapshot) ProtoMessage() {}

func (x *DiskIOSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOSnapshot.ProtoReflect.Descriptor instead.
func (*DiskIOSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{13}
}

func (x *DiskIOSnapshot) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskIOSnapshot) GetReadsPerSec() float64 {
	if x != nil {
		return x.ReadsPerSec
	}
	return 0
}

func (x *DiskIOSnapshot) GetWritesPerSec() float64 {
	if x != nil {
		return x.WritesPerSec
	}
	return 0
}

func (x *DiskIOSnapshot) GetReadBytesPerSec() float64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *DiskIOSnapshot) GetWriteBytesPerSec() float64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

// CPUTempSnapshot captures the CPU temperature from onboard thermal sensors.
type CPUTempSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU temperature in degrees Celsius.
	TempCelsius float64 `protobuf:"fixed64,1,opt,name=temp_celsius,json=tempCelsius,proto3" json:"temp_celsius,omitempty"`
	// Minimum observed temperature since plugin start.
	MinCelsius float64 `protobuf:"fixed64,2,opt,name=min_celsius,json=minCelsius,proto3" json:"min_celsius,omitempty"`
	// Maximum observed temperature since plugin start.
	MaxCelsius float64 `protobuf:"fixed64,3,opt,name=max_celsius,json=maxCelsius,proto3" json:"max_celsius,omitempty"`
	// Bar percentage (0-100) within the observed [min, max] range.
	// Used by tmuxbar for color and bar graph thresholds.
	BarPct        float64 `protobuf:"fixed64,4,opt,name=bar_pct,json=barPct,proto3" json:"bar_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUTempSnapshot) Reset() {
	*x = CPUTempSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUTempSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUTempSnapshot) ProtoMessage() {}

func (x *CPUTempSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUTempSnapshot.ProtoReflect.Descriptor instead.
func (*CPUTempSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{14}
}

func (x *CPUTempSnapshot) GetTempCelsius() float64 {
	if x != nil {
		return x.TempCelsius
	}
	return 0
}

func (x *CPUTempSnapshot) GetMinCelsius() float64 {
	if x != nil {
		return x.MinCelsius
	}
	return 0
}

func (x *CPUTempSnapshot) GetMaxCelsius() float64 {
	if x != nil {
		return x.MaxCelsius
	}
	return 0
}

func (x *CPUTempSnapshot) GetBarPct() float64 {
	if x != nil {
		return x.BarPct
	}
	return 0
}

// BatterySnapshot captures the battery status at a point in time.
type BatterySnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Battery charge level as percentage (0-100).
	Percent float64 `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	// Whether the battery is currently being charged.
	Charging bool `protobuf:"varint,2,opt,name=charging,proto3" json:"charging,omitempty"`
	// Whether the AC power adapter is plugged in.
	Plugged bool `protobuf:"varint,3,opt,name=plugged,proto3" json:"plugged,omitempty"`
	// Raw battery charge/discharge status from sysfs.
	Status BatteryStatus `protobuf:"varint,4,opt,name=status,proto3,enum=resources.BatteryStatus" json:"status,omitempty"`
	// Current energy remaining in microamp-hours (µAh).
	EnergyNow int64 `protobuf:"varint,5,opt,name=energy_now,json=energyNow,proto3" json:"energy_now,omitempty"`
	// Full charge energy capacity in microamp-hours (µAh).
	EnergyFull int64 `protobuf:"varint,6,opt,name=energy_full,json=energyFull,proto3" json:"energy_full,omitempty"`
	// Current power draw in microwatts (µW). Positive for discharge,
	// negative is not used — interpret via `status`.
	PowerNow      int64 `protobuf:"varint,7,opt,name=power_now,json=powerNow,proto3" json:"power_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatterySnapshot) Reset() {
	*x = BatterySnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatterySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySnapshot) ProtoMessage() {}

func (x *BatterySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySnapshot.ProtoReflect.Descriptor instead.
func (*BatterySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{15}
}

func (x *BatterySnapshot) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *BatterySnapshot) GetCharging() bool {
	if x != nil {
		return x.Charging
	}
	return false
}

func (x *BatterySnapshot) GetPlugged() bool {
	if x != nil {
		return x.Plugged
	}
	return false
}

func (x *BatterySnapshot) GetStatus() BatteryStatus {
	if x != nil {
		return x.Status
	}
	return BatteryStatus_BATTERY_STATUS_UNSPECIFIED
}

func (x *BatterySnapshot) GetEnergyNow() int64 {
	if x != nil {
		return x.EnergyNow
	}
	return 0
}

func (x *BatterySnapshot) GetEnergyFull() int64 {
	if x != nil {
		return x.EnergyFull
	}
	return 0
}

func (x *BatterySnapshot) GetPowerNow() int64 {
	if x != nil {
		return x.PowerNow
	}
	return 0
}

// WiFiSnapshot captures the WiFi signal strength at a point in time.
type WiFiSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wireless interface name (e.g., "wlp6s0").
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// Signal quality as percentage (0-100). Higher is better.
	Percent float64 `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// Connected network SSID.
	Ssid          string `protobuf:"bytes,3,opt,name=ssid,proto3" json:"ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiFiSnapshot) Reset() {
	*x = WiFiSnapshot{}
	mi := &file_proto_resources_resources_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiFiSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiSnapshot) ProtoMessage() {}

func (x *WiFiSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiSnapshot.ProtoReflect.Descriptor instead.
func (*WiFiSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{16}
}

func (x *WiFiSnapshot) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *WiFiSnapshot) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *WiFiSnapshot) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

// ProcessInfo describes a running process.
type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process ID.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Process name (comm).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// CPU usage percentage.
	CpuPercent float64 `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Memory usage percentage.
	MemPercent float64 `protobuf:"fixed64,4,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	// Memory usage in MB.
	MemMb float64 `protobuf:"fixed64,5,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`
	// Process state.
	State ProcessState `protobuf:"varint,6,opt,name=state,proto3,enum=resources.ProcessState" json:"state,omitempty"`
	// Number of threads in the process.
	ThreadCount int32 `protobuf:"varint,7,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	// Username of the process owner.
	User string `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// Kernel scheduling priority.
	Priority int32 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	// Nice value (lower = higher priority).
	Nice int32 `protobuf:"varint,10,opt,name=nice,proto3" json:"nice,omitempty"`
	// Cumulative CPU time consumed (jiffies).
	Time int64 `protobuf:"varint,11,opt,name=time,proto3" json:"time,omitempty"`
	// Full command line (argv).
	Command       string `protobuf:"bytes,12,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_resources_resources_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resources_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_resources_resources_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemMb() float64 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

func (x *ProcessInfo) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ProcessInfo) GetThreadCount() int32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProcessInfo) GetNice() int32 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *ProcessInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

var File_proto_resources_resources_proto protoreflect.FileDescriptor

const file_proto_resources_resources_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/resources/resources.proto\x12\tresources\"\x10\n" +
	"\x0eCurrentRequest\">\n" +
	"\fWatchRequest\x12.\n" +
	"\x06filter\x18\x01 \x01(\v2\x16.resources.WatchFilterR\x06filter\"\xb9\x02\n" +
	"\vWatchFilter\x12\x10\n" +
	"\x03ram\x18\x01 \x01(\bR\x03ram\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\bR\x03cpu\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\bR\x04disk\x12\x17\n" +
	"\adisk_io\x18\x04 \x01(\bR\x06diskIo\x12\x19\n" +
	"\bcpu_temp\x18\x05 \x01(\bR\acpuTemp\x12\x18\n" +
	"\abattery\x18\x06 \x01(\bR\abattery\x12\x12\n" +
	"\x04wifi\x18\a \x01(\bR\x04wifi\x12!\n" +
	"\fasus_profile\x18\b \x01(\bR\vasusProfile\x12\x1f\n" +
	"\vgpu_profile\x18\t \x01(\bR\n" +
	"gpuProfile\x12'\n" +
	"\x0fkeyboard_layout\x18\n" +
	" \x01(\bR\x0ekeyboardLayout\x12#\n" +
	"\rtop_processes\x18\v \x01(\bR\ftopProcesses\"\x82\a\n" +
	"\x0fCurrentResponse\x12(\n" +
	"\x03ram\x18\x01 \x01(\v2\x16.resources.RAMSnapshotR\x03ram\x12(\n" +
	"\x03cpu\x18\x02 \x01(\v2\x16.resources.CPUSnapshotR\x03cpu\x12+\n" +
	"\x04disk\x18\x03 \x01(\v2\x17.resources.DiskSnapshotR\x04disk\x122\n" +
	"\adisk_io\x18\x04 \x01(\v2\x19.resources.DiskIOSnapshotR\x06diskIo\x125\n" +
	"\bcpu_temp\x18\x05 \x01(\v2\x1a.resources.CPUTempSnapshotR\acpuTemp\x124\n" +
	"\abattery\x18\x06 \x01(\v2\x1a.resources.BatterySnapshotR\abattery\x12+\n" +
	"\x04wifi\x18\a \x01(\v2\x17.resources.WiFiSnapshotR\x04wifi\x129\n" +
	"\fasus_profile\x18\b \x01(\x0e2\x16.resources.ASUSProfileR\vasusProfile\x126\n" +
	"\vgpu_profile\x18\t \x01(\x0e2\x15.resources.GPUProfileR\n" +
	"gpuProfile\x12'\n" +
	"\x0fkeyboard_layout\x18\n" +
	" \x01(\tR\x0ekeyboardLayout\x12&\n" +
	"\x0ftop_cpu_process\x18\v \x01(\tR\rtopCpuProcess\x12&\n" +
	"\x0ftop_mem_process\x18\f \x01(\tR\rtopMemProcess\x12\x1d\n" +
	"\n" +
	"poll_count\x18\r \x01(\x03R\tpollCount\x12$\n" +
	"\x0eload_average_1\x18\x0e \x01(\x01R\floadAverage1\x12$\n" +
	"\x0eload_average_5\x18\x0f \x01(\x01R\floadAverage5\x12&\n" +
	"\x0fload_average_15\x18\x10 \x01(\x01R\rloadAverage15\x12%\n" +
	"\x0euptime_seconds\x18\x11 \x01(\x01R\ruptimeSeconds\x12#\n" +
	"\rprocess_count\x18\x12 \x01(\x05R\fprocessCount\x12!\n" +
	"\fthread_count\x18\x13 \x01(\x05R\vthreadCount\x122\n" +
	"\x15running_process_count\x18\x14 \x01(\x05R\x13runningProcessCount\"L\n" +
	"\n" +
	"TopRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12(\n" +
	"\x04sort\x18\x02 \x01(\x0e2\x14.resources.SortOrderR\x04sort\"C\n" +
	"\vTopResponse\x124\n" +
	"\tprocesses\x18\x01 \x03(\v2\x16.resources.ProcessInfoR\tprocesses\"]\n" +
	"\tPSRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12(\n" +
	"\x04sort\x18\x03 \x01(\x0e2\x14.resources.SortOrderR\x04sort\"B\n" +
	"\n" +
	"PSResponse\x124\n" +
	"\tprocesses\x18\x01 \x03(\v2\x16.resources.ProcessInfoR\tprocesses\"[\n" +
	"\x0eHistoryRequest\x123\n" +
	"\bresource\x18\x01 \x01(\x0e2\x17.resources.ResourceTypeR\bresource\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x83\x01\n" +
	"\x0fHistoryResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x123\n" +
	"\bresource\x18\x02 \x01(\x0e2\x17.resources.ResourceTypeR\bresource\x12#\n" +
	"\x04unit\x18\x03 \x01(\x0e2\x0f.resources.UnitR\x04unit\"~\n" +
	"\vRAMSnapshot\x12\x19\n" +
	"\btotal_mb\x18\x01 \x01(\x01R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x02 \x01(\x01R\x06usedMb\x12!\n" +
	"\favailable_mb\x18\x03 \x01(\x01R\vavailableMb\x12\x18\n" +
	"\apercent\x18\x04 \x01(\x01R\apercent\"\xea\x01\n" +
	"\vCPUSnapshot\x12#\n" +
	"\rtotal_percent\x18\x01 \x01(\x01R\ftotalPercent\x12!\n" +
	"\fuser_percent\x18\x02 \x01(\x01R\vuserPercent\x12%\n" +
	"\x0esystem_percent\x18\x03 \x01(\x01R\rsystemPercent\x12%\n" +
	"\x0eiowait_percent\x18\x04 \x01(\x01R\riowaitPercent\x12\x1b\n" +
	"\tnum_cores\x18\x05 \x01(\x05R\bnumCores\x12(\n" +
	"\x10per_core_percent\x18\x06 \x03(\x01R\x0eperCorePercent\"\x98\x01\n" +
	"\fDiskSnapshot\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x19\n" +
	"\btotal_gb\x18\x02 \x01(\x01R\atotalGb\x12\x17\n" +
	"\aused_gb\x18\x03 \x01(\x01R\x06usedGb\x12\x19\n" +
	"\bavail_gb\x18\x04 \x01(\x01R\aavailGb\x12\x18\n" +
	"\apercent\x18\x05 \x01(\x01R\apercent\"\xce\x01\n" +
	"\x0eDiskIOSnapshot\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\"\n" +
	"\rreads_per_sec\x18\x02 \x01(\x01R\vreadsPerSec\x12$\n" +
	"\x0ewrites_per_sec\x18\x03 \x01(\x01R\fwritesPerSec\x12+\n" +
	"\x12read_bytes_per_sec\x18\x04 \x01(\x01R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\x05 \x01(\x01R\x10writeBytesPerSec\"\x8f\x01\n" +
	"\x0fCPUTempSnapshot\x12!\n" +
	"\ftemp_celsius\x18\x01 \x01(\x01R\vtempCelsius\x12\x1f\n" +
	"\vmin_celsius\x18\x02 \x01(\x01R\n" +
	"minCelsius\x12\x1f\n" +
	"\vmax_celsius\x18\x03 \x01(\x01R\n" +
	"maxCelsius\x12\x17\n" +
	"\abar_pct\x18\x04 \x01(\x01R\x06barPct\"\xf0\x01\n" +
	"\x0fBatterySnapshot\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\x12\x1a\n" +
	"\bcharging\x18\x02 \x01(\bR\bcharging\x12\x18\n" +
	"\aplugged\x18\x03 \x01(\bR\aplugged\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.resources.BatteryStatusR\x06status\x12\x1d\n" +
	"\n" +
	"energy_now\x18\x05 \x01(\x03R\tenergyNow\x12\x1f\n" +
	"\venergy_full\x18\x06 \x01(\x03R\n" +
	"energyFull\x12\x1b\n" +
	"\tpower_now\x18\a \x01(\x03R\bpowerNow\"Z\n" +
	"\fWiFiSnapshot\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x12\n" +
	"\x04ssid\x18\x03 \x01(\tR\x04ssid\"\xd0\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x04 \x01(\x01R\n" +
	"memPercent\x12\x15\n" +
	"\x06mem_mb\x18\x05 \x01(\x01R\x05memMb\x12-\n" +
	"\x05state\x18\x06 \x01(\x0e2\x17.resources.ProcessStateR\x05state\x12!\n" +
	"\fthread_count\x18\a \x01(\x05R\vthreadCount\x12\x12\n" +
	"\x04user\x18\b \x01(\tR\x04user\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x12\n" +
	"\x04nice\x18\n" +
	" \x01(\x05R\x04nice\x12\x12\n" +
	"\x04time\x18\v \x01(\x03R\x04time\x12\x18\n" +
	"\acommand\x18\f \x01(\tR\acommand*R\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_CPU\x10\x01\x12\x15\n" +
	"\x11SORT_ORDER_MEMORY\x10\x02*\xaa\x01\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESOURCE_TYPE_RAM\x10\x01\x12\x15\n" +
	"\x11RESOURCE_TYPE_CPU\x10\x02\x12\x16\n" +
	"\x12RESOURCE_TYPE_DISK\x10\x03\x12\x1a\n" +
	"\x16RESOURCE_TYPE_CPU_TEMP\x10\x04\x12\x19\n" +
	"\x15RESOURCE_TYPE_BATTERY\x10\x05*@\n" +
	"\x04Unit\x12\x14\n" +
	"\x10UNIT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUNIT_PERCENT\x10\x01\x12\x10\n" +
	"\fUNIT_CELSIUS\x10\x02*\xed\x01\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x01\x12\x1a\n" +
	"\x16PROCESS_STATE_SLEEPING\x10\x02\x12\x1c\n" +
	"\x18PROCESS_STATE_DISK_SLEEP\x10\x03\x12\x18\n" +
	"\x14PROCESS_STATE_ZOMBIE\x10\x04\x12\x19\n" +
	"\x15PROCESS_STATE_STOPPED\x10\x05\x12\x1c\n" +
	"\x18PROCESS_STATE_TRACE_STOP\x10\x06\x12\x16\n" +
	"\x12PROCESS_STATE_DEAD\x10\a*\xa6\x01\n" +
	"\rBatteryStatus\x12\x1e\n" +
	"\x1aBATTERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BATTERY_STATUS_CHARGING\x10\x01\x12\x1e\n" +
	"\x1aBATTERY_STATUS_DISCHARGING\x10\x02\x12\x17\n" +
	"\x13BATTERY_STATUS_FULL\x10\x03\x12\x1f\n" +
	"\x1bBATTERY_STATUS_NOT_CHARGING\x10\x04*p\n" +
	"\vASUSProfile\x12\x1c\n" +
	"\x18ASUS_PROFILE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ASUS_PROFILE_PERF\x10\x01\x12\x14\n" +
	"\x10ASUS_PROFILE_BAL\x10\x02\x12\x16\n" +
	"\x12ASUS_PROFILE_QUIET\x10\x03*\x85\x01\n" +
	"\n" +
	"GPUProfile\x12\x1b\n" +
	"\x17GPU_PROFILE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GPU_PROFILE_EGPU\x10\x01\x12\x16\n" +
	"\x12GPU_PROFILE_NVIDIA\x10\x02\x12\x14\n" +
	"\x10GPU_PROFILE_IGPU\x10\x03\x12\x16\n" +
	"\x12GPU_PROFILE_HYBRID\x10\x042\xbf\x02\n" +
	"\x10ResourcesService\x12@\n" +
	"\aCurrent\x12\x19.resources.CurrentRequest\x1a\x1a.resources.CurrentResponse\x124\n" +
	"\x03Top\x12\x15.resources.TopRequest\x1a\x16.resources.TopResponse\x121\n" +
	"\x02PS\x12\x14.resources.PSRequest\x1a\x15.resources.PSResponse\x12@\n" +
	"\aHistory\x12\x19.resources.HistoryRequest\x1a\x1a.resources.HistoryResponse\x12>\n" +
	"\x05Watch\x12\x17.resources.WatchRequest\x1a\x1a.resources.CurrentResponse0\x01B#Z!plugins/resources/proto/resourcesb\x06proto3"

var (
	file_proto_resources_resources_proto_rawDescOnce sync.Once
	file_proto_resources_resources_proto_rawDescData []byte
)

func file_proto_resources_resources_proto_rawDescGZIP() []byte {
	file_proto_resources_resources_proto_rawDescOnce.Do(func() {
		file_proto_resources_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resources_resources_proto_rawDesc), len(file_proto_resources_resources_proto_rawDesc)))
	})
	return file_proto_resources_resources_proto_rawDescData
}

var file_proto_resources_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_resources_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_resources_resources_proto_goTypes = []any{
	(SortOrder)(0),          // 0: resources.SortOrder
	(ResourceType)(0),       // 1: resources.ResourceType
	(Unit)(0),               // 2: resources.Unit
	(ProcessState)(0),       // 3: resources.ProcessState
	(BatteryStatus)(0),      // 4: resources.BatteryStatus
	(ASUSProfile)(0),        // 5: resources.ASUSProfile
	(GPUProfile)(0),         // 6: resources.GPUProfile
	(*CurrentRequest)(nil),  // 7: resources.CurrentRequest
	(*WatchRequest)(nil),    // 8: resources.WatchRequest
	(*WatchFilter)(nil),     // 9: resources.WatchFilter
	(*CurrentResponse)(nil), // 10: resources.CurrentResponse
	(*TopRequest)(nil),      // 11: resources.TopRequest
	(*TopResponse)(nil),     // 12: resources.TopResponse
	(*PSRequest)(nil),       // 13: resources.PSRequest
	(*PSResponse)(nil),      // 14: resources.PSResponse
	(*HistoryRequest)(nil),  // 15: resources.HistoryRequest
	(*HistoryResponse)(nil), // 16: resources.HistoryResponse
	(*RAMSnapshot)(nil),     // 17: resources.RAMSnapshot
	(*CPUSnapshot)(nil),     // 18: resources.CPUSnapshot
	(*DiskSnapshot)(nil),    // 19: resources.DiskSnapshot
	(*DiskIOSnapshot)(nil),  // 20: resources.DiskIOSnapshot
	(*CPUTempSnapshot)(nil), // 21: resources.CPUTempSnapshot
	(*BatterySnapshot)(nil), // 22: resources.BatterySnapshot
	(*WiFiSnapshot)(nil),    // 23: resources.WiFiSnapshot
	(*ProcessInfo)(nil),     // 24: resources.ProcessInfo
}
var file_proto_resources_resources_proto_depIdxs = []int32{
	9,  // 0: resources.WatchRequest.filter:type_name -> resources.WatchFilter
	17, // 1: resources.CurrentResponse.ram:type_name -> resources.RAMSnapshot
	18, // 2: resources.CurrentResponse.cpu:type_name -> resources.CPUSnapshot
	19, // 3: resources.CurrentResponse.disk:type_name -> resources.DiskSnapshot
	20, // 4: resources.CurrentResponse.disk_io:type_name -> resources.DiskIOSnapshot
	21, // 5: resources.CurrentResponse.cpu_temp:type_name -> resources.CPUTempSnapshot
	22, // 6: resources.CurrentResponse.battery:type_name -> resources.BatterySnapshot
	23, // 7: resources.CurrentResponse.wifi:type_name -> resources.WiFiSnapshot
	5,  // 8: resources.CurrentResponse.asus_profile:type_name -> resources.ASUSProfile
	6,  // 9: resources.CurrentResponse.gpu_profile:type_name -> resources.GPUProfile
	0,  // 10: resources.TopRequest.sort:type_name -> resources.SortOrder
	24, // 11: resources.TopResponse.processes:type_name -> resources.ProcessInfo
	0,  // 12: resources.PSRequest.sort:type_name -> resources.SortOrder
	24, // 13: resources.PSResponse.processes:type_name -> resources.ProcessInfo
	1,  // 14: resources.HistoryRequest.resource:type_name -> resources.ResourceType
	1,  // 15: resources.HistoryResponse.resource:type_name -> resources.ResourceType
	2,  // 16: resources.HistoryResponse.unit:type_name -> resources.Unit
	4,  // 17: resources.BatterySnapshot.status:type_name -> resources.BatteryStatus
	3,  // 18: resources.ProcessInfo.state:type_name -> resources.ProcessState
	7,  // 19: resources.ResourcesService.Current:input_type -> resources.CurrentRequest
	11, // 20: resources.ResourcesService.Top:input_type -> resources.TopRequest
	13, // 21: resources.ResourcesService.PS:input_type -> resources.PSRequest
	15, // 22: resources.ResourcesService.History:input_type -> resources.HistoryRequest
	8,  // 23: resources.ResourcesService.Watch:input_type -> resources.WatchRequest
	10, // 24: resources.ResourcesService.Current:output_type -> resources.CurrentResponse
	12, // 25: resources.ResourcesService.Top:output_type -> resources.TopResponse
	14, // 26: resources.ResourcesService.PS:output_type -> resources.PSResponse
	16, // 27: resources.ResourcesService.History:output_type -> resources.HistoryResponse
	10, // 28: resources.ResourcesService.Watch:output_type -> resources.CurrentResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_resources_resources_proto_init() }
func file_proto_resources_resources_proto_init() {
	if File_proto_resources_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resources_resources_proto_rawDesc), len(file_proto_resources_resources_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resources_resources_proto_goTypes,
		DependencyIndexes: file_proto_resources_resources_proto_depIdxs,
		EnumInfos:         file_proto_resources_resources_proto_enumTypes,
		MessageInfos:      file_proto_resources_resources_proto_msgTypes,
	}.Build()
	File_proto_resources_resources_proto = out.File
	file_proto_resources_resources_proto_goTypes = nil
	file_proto_resources_resources_proto_depIdxs = nil
}
