package plugin

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	dotfilesdv1connect "dotfilesd/proto/dotfilesd/v1/dotfilesdv1/dotfilesdv1connect"

	"connectrpc.com/grpcreflect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

// Service is a Connect RPC service a plugin exposes.
// Plugins define their own protobuf services and register them here.
type Service struct {
	// Fully-qualified service name (e.g. "dotfilesd.v1.WeatherService").
	Name string
	// Human-readable description.
	Description string
	// HTTP path prefix (e.g. "/dotfilesd.v1.WeatherService/").
	Path string
	// Connect RPC handler.
	Handler http.Handler
	// Whether this service is accessible to other plugins.
	PluginAccessible bool
	// Method names that need interactive stdin (e.g. "Play2048", "Move").
	// The daemon uses this hint to set up raw terminal mode and stdin
	// forwarding so TUI plugins receive keystrokes in real time.
	InteractiveMethods []string
}

// Config configures a plugin.
type Config struct {
	// Plugin metadata.
	Name, DisplayName, Version, Description, Author string
	// Plugin type: "server" (long-lived) or "command" (ephemeral).
	Type string

	// Background worker (optional). Runs after the server starts.
	Background func(ctx Context, stop <-chan struct{})

	// Custom Connect RPC services this plugin exposes.
	// Other plugins can call these after discovering them via the registry.
	Services []Service

	// DocsContent is optional documentation string (legacy). Superseded
	// by DocsProto when both are set.
	DocsContent string

	// DocsProto is optional pre-generated Documentation proto, embedded via
	// //go:embed of the .doc.pb file generated by protoc-gen-docs.
	// When set, the default DocumentationService returns structured docs
	// in DocumentationResponse.documentation.
	DocsProto *dotfilesdv1.Documentation
}

// Serve starts the plugin server.
//
// The server mounts grpcreflect handlers (for daemon discovery),
// a default DocumentationService, and all custom services from
// Config.Services. It performs the handshake with the daemon and
// blocks until SIGTERM/SIGINT.
func Serve(cfg Config) {
	ctxURL := os.Getenv("EXECUTION_CONTEXT_URL")
	ctxToken := os.Getenv("EXECUTION_CONTEXT_TOKEN")
	sessionID := os.Getenv("SESSION_ID")

	if ctxURL == "" {
		fmt.Fprintf(os.Stderr, "plugin: EXECUTION_CONTEXT_URL not set\n")
		os.Exit(1)
	}

	ctxClient := newContextClient(ctxURL, ctxToken, sessionID, cfg.Name, "")

	mux := http.NewServeMux()

	// Collect all service names for the grpcreflect reflector.
	names := []string{}
	hasDocsSvc := false
	for _, svc := range cfg.Services {
		names = append(names, svc.Name)
		if svc.Name == "dotfilesd.v1.DocumentationService" {
			hasDocsSvc = true
		}
	}
	if !hasDocsSvc {
		names = append(names, "dotfilesd.v1.DocumentationService")
	}

	// Mount grpcreflect handlers — daemon discovers ALL services via this.
	reflector := grpcreflect.NewStaticReflector(names...)
	mux.Handle(grpcreflect.NewHandlerV1(reflector))
	mux.Handle(grpcreflect.NewHandlerV1Alpha(reflector))

	// Mount default DocumentationService (SKIP if plugin provides its own).
	if !hasDocsSvc {
		docsSvc := &documentationServiceServer{
			name:        cfg.Name,
			displayName: cfg.DisplayName,
			version:     cfg.Version,
			description: cfg.Description,
			services:    cfg.Services,
			docsContent: cfg.DocsContent,
			docsProto:   cfg.DocsProto,
		}
		docsPath, docsHandler := dotfilesdv1connect.NewDocumentationServiceHandler(docsSvc)
		mux.Handle(docsPath, docsHandler)
	}

	// Mount custom services (type-safe plugin-to-plugin RPC).
	for _, svc := range cfg.Services {
		mux.Handle(svc.Path, svc.Handler)
	}

	// Serve method hints — tells the daemon which RPCs need interactive
	// stdin (e.g. TUI games). The daemon fetches this at plugin load time
	// and populates MethodSchema.needs_interactive_stdin accordingly.
	mux.HandleFunc("/__dotfiles/method_hints", func(w http.ResponseWriter, r *http.Request) {
		hints := buildMethodHints(cfg.Services)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(hints)
	})

	// Context injection middleware: wraps every request so handlers can
	// call plugin.ExtractContext(ctx) to get daemon access.
	// Reads X-Dotfiles-Render-Output and X-Client-ID from incoming requests
	// and propagates them into the plugin Context for stream multiplexing.
	// When X-Dotfiles-Diag-Parent is set, creates a sub-executor node in the
	// diagnostics tree so plugin-to-plugin RPC chains are visible.
	ctxWrappedMux := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		clientID := r.Header.Get("X-Client-ID")
		ro := r.Header.Get("X-Dotfiles-Render-Output") == "true"
		diagParent := r.Header.Get("X-Dotfiles-Diag-Parent")

		var ctx Context = ctxClient
		if clientID != "" || ro || diagParent != "" {
			c := *ctxClient
			if clientID != "" {
				c.clientID = clientID
			}
			if ro {
				c.renderOutput = true
			}

			// When called with a diagnostics parent (X-Dotfiles-Diag-Parent),
			// create a sub-node in the diagnostics tree so the full plugin
			// call chain is visible in the tree.
			if diagParent != "" {
				rpcName := extractMethodName(r.URL.Path)
				rpcID := fmt.Sprintf("plugin-rpc:%s_%x", rpcName, time.Now().UnixNano())
				c.pushDiagEvent("plugin_rpc_open", rpcID, diagParent, rpcName, nil)
				c.diagParent = rpcID
				defer c.pushDiagEvent("plugin_rpc_close", rpcID, diagParent, rpcName, nil)
			}

			ctx = &c
		}
		r = r.WithContext(WithContext(r.Context(), ctx))
		mux.ServeHTTP(w, r)
	})

	// Wrap DefaultTransport to propagate X-Dotfiles-Diag-Parent on outgoing
	// Connect calls (plugin-to-plugin RPC). Reads the header from the request
	// context's plugin Context, which is set by the incoming request middleware.
	baseTransport := http.DefaultTransport
	http.DefaultTransport = roundTripperFunc(func(r *http.Request) (*http.Response, error) {
		if pc := ExtractContext(r.Context()); pc != nil {
			if dp := pc.DiagParent(); dp != "" {
				r.Header.Set("X-Dotfiles-Diag-Parent", dp)
			}
		}
		return baseTransport.RoundTrip(r)
	})

	// Listen on a random available port.
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		fmt.Fprintf(os.Stderr, "plugin: failed to listen: %v\n", err)
		os.Exit(1)
	}

	addr := listener.Addr().(*net.TCPAddr)
	pluginURL := fmt.Sprintf("http://127.0.0.1:%d", addr.Port)

	// Write handshake JSON to stdout so the daemon can discover us.
	handshake := map[string]string{
		"protocol":     "dotfilesd-plugin-v1",
		"url":          pluginURL,
		"session_id":   sessionID,
		"name":         cfg.Name,
		"display_name": cfg.DisplayName,
		"version":      cfg.Version,
		"description":  cfg.Description,
	}
	enc := json.NewEncoder(os.Stdout)
	if err := enc.Encode(handshake); err != nil {
		fmt.Fprintf(os.Stderr, "plugin: handshake encode failed: %v\n", err)
		os.Exit(1)
	}

	// Signal handler for graceful shutdown.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGTERM, syscall.SIGINT)

	srv := &http.Server{Handler: h2c.NewHandler(ctxWrappedMux, &http2.Server{})}
	go func() {
		if err := srv.Serve(listener); err != nil && err != http.ErrServerClosed {
			fmt.Fprintf(os.Stderr, "plugin: serve error: %v\n", err)
		}
	}()

	// Start background worker if provided.
	if cfg.Background != nil {
		stopCh := make(chan struct{})
		go cfg.Background(ctxClient, stopCh)
		<-sigCh
		close(stopCh)
	} else {
		<-sigCh
	}
	_ = srv.Shutdown(context.Background())
}

// roundTripperFunc is an http.RoundTripper that calls a function.
type roundTripperFunc func(*http.Request) (*http.Response, error)

func (f roundTripperFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

// extractMethodName extracts the method name from a Connect RPC URL path.
// Connect paths are like "/package.Service/Method", so we take the last
// segment after trimming trailing slash.
// extractMethodName extracts the full "Service.Method" from a Connect RPC URL path.
// Connect paths are like "/resources.ResourcesService/Current", so we take the
// last two segments and join them with a dot.
func extractMethodName(path string) string {
	path = strings.TrimSuffix(path, "/")
	// Split into segments.
	parts := strings.Split(path, "/")
	if len(parts) >= 2 {
		// parts[len-2] is Service, parts[len-1] is Method
		return parts[len(parts)-2] + "." + parts[len(parts)-1]
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return path
}

// methodHintsJSON is the JSON structure returned by /__dotfiles/method_hints.
type methodHintsJSON struct {
	Services []serviceHintsJSON `json:"services"`
}

type serviceHintsJSON struct {
	Name              string   `json:"name"`
	InteractiveMethod []string `json:"interactive_methods,omitempty"`
}

// buildMethodHints collects interactive stdin hints from all services
// into a JSON-serializable structure.
func buildMethodHints(services []Service) methodHintsJSON {
	out := methodHintsJSON{}
	for _, svc := range services {
		if len(svc.InteractiveMethods) > 0 {
			out.Services = append(out.Services, serviceHintsJSON{
				Name:              svc.Name,
				InteractiveMethod: svc.InteractiveMethods,
			})
		}
	}
	return out
}
