font_family Hack Nerd Font Mono
font_size 11.0

foreground #E8E8E2
background #1e1f1c
selection_foreground #E8E8E2
selection_background #383830

cursor #E8E8E2
cursor_text_color #272822

url_color #66D9EF

active_border_color #A6E22E
inactive_border_color #383830
bell_border_color #E6DB74

active_tab_background #A6E22E
active_tab_foreground #272822
inactive_tab_background #272822
inactive_tab_foreground #75715E

tab_bar_background #272822

# Monokai ANSI colors
color0 #272822
color1 #E82572
color2 #A6E22E
color3 #E6DB74
color4 #66D9EF
color5 #AE81FF
color6 #A1EFE4
color7 #E8E8E2
color8 #75715E
color9 #F92672
color10 #A6E22E
color11 #E6DB74
color12 #66D9EF
color13 #AE81FF
color14 #A1EFE4
color15 #F8F8F2

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

shell_integration enabled

enable_audio_bell no
