// Code generated by protoc-gen-docs. DO NOT EDIT.

package dotfilesdv1

import (
	_ "embed"

	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	"dotfilesd/plugin"
	"google.golang.org/protobuf/proto"
)

//go:embed plugin_registry_doc.pb
var pluginDocsData []byte

func init() {
	var doc dotfilesdv1.Documentation
	if err := proto.Unmarshal(pluginDocsData, &doc); err != nil {
		return
	}
	PluginDocs = &doc
	plugin.DefaultDocs = &doc
}

var PluginDocs *dotfilesdv1.Documentation
