// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/stdinecho/stdinecho.proto

package stdinechoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	stdinecho "plugins/stdinecho/proto/stdinecho"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StdinechoServiceName is the fully-qualified name of the StdinechoService service.
	StdinechoServiceName = "stdinecho.StdinechoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StdinechoServiceEchoProcedure is the fully-qualified name of the StdinechoService's Echo RPC.
	StdinechoServiceEchoProcedure = "/stdinecho.StdinechoService/Echo"
)

// StdinechoServiceClient is a client for the stdinecho.StdinechoService service.
type StdinechoServiceClient interface {
	// Echo reads lines from stdin and echoes them back.
	Echo(context.Context, *connect.Request[stdinecho.EchoRequest]) (*connect.Response[stdinecho.EchoResponse], error)
}

// NewStdinechoServiceClient constructs a client for the stdinecho.StdinechoService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStdinechoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StdinechoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stdinechoServiceMethods := stdinecho.File_proto_stdinecho_stdinecho_proto.Services().ByName("StdinechoService").Methods()
	return &stdinechoServiceClient{
		echo: connect.NewClient[stdinecho.EchoRequest, stdinecho.EchoResponse](
			httpClient,
			baseURL+StdinechoServiceEchoProcedure,
			connect.WithSchema(stdinechoServiceMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stdinechoServiceClient implements StdinechoServiceClient.
type stdinechoServiceClient struct {
	echo *connect.Client[stdinecho.EchoRequest, stdinecho.EchoResponse]
}

// Echo calls stdinecho.StdinechoService.Echo.
func (c *stdinechoServiceClient) Echo(ctx context.Context, req *connect.Request[stdinecho.EchoRequest]) (*connect.Response[stdinecho.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// StdinechoServiceHandler is an implementation of the stdinecho.StdinechoService service.
type StdinechoServiceHandler interface {
	// Echo reads lines from stdin and echoes them back.
	Echo(context.Context, *connect.Request[stdinecho.EchoRequest]) (*connect.Response[stdinecho.EchoResponse], error)
}

// NewStdinechoServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStdinechoServiceHandler(svc StdinechoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stdinechoServiceMethods := stdinecho.File_proto_stdinecho_stdinecho_proto.Services().ByName("StdinechoService").Methods()
	stdinechoServiceEchoHandler := connect.NewUnaryHandler(
		StdinechoServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(stdinechoServiceMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/stdinecho.StdinechoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StdinechoServiceEchoProcedure:
			stdinechoServiceEchoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStdinechoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStdinechoServiceHandler struct{}

func (UnimplementedStdinechoServiceHandler) Echo(context.Context, *connect.Request[stdinecho.EchoRequest]) (*connect.Response[stdinecho.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("stdinecho.StdinechoService.Echo is not implemented"))
}
