logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: servergordo
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 192.168.100.2
  }
  node {
    name: servernotangordo
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 192.168.100.5
  }
}

quorum {
  provider: corosync_votequorum
}

totem {
  cluster_name: casa
  config_version: 6
  interface {
    bindnetaddr: 192.168.100.0
    mcastport: 5405
    ringnumber: 0
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  two_node: 1
  version: 2
}

