### Font ###
font-engine=freetype
font-name=DejaVu Sans Mono
font-size=14

### Palette — Monokai ###
palette=custom
palette-foreground=248, 248, 242
palette-background=39, 40, 34
palette-black=39, 40, 34
palette-red=249, 38, 114
palette-green=166, 226, 46
palette-yellow=253, 151, 31
palette-blue=102, 217, 239
palette-magenta=174, 129, 255
palette-cyan=166, 226, 46
palette-light-grey=117, 113, 94
palette-dark-grey=73, 72, 62
palette-light-red=249, 38, 114
palette-light-green=166, 226, 46
palette-light-yellow=230, 219, 116
palette-light-blue=102, 217, 239
palette-light-magenta=174, 129, 255
palette-light-cyan=102, 217, 239
palette-white=248, 248, 242

### Input ###
xkb-layout=us
switchvt

### Session ###
session-control
