// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/tmuxbar/tmuxbar.proto

package tmuxbarconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	tmuxbar "plugins/tmuxbar/proto/tmuxbar"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TmuxBarServiceName is the fully-qualified name of the TmuxBarService service.
	TmuxBarServiceName = "tmuxbar.TmuxBarService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TmuxBarServiceRAMWidgetProcedure is the fully-qualified name of the TmuxBarService's RAMWidget
	// RPC.
	TmuxBarServiceRAMWidgetProcedure = "/tmuxbar.TmuxBarService/RAMWidget"
	// TmuxBarServiceCPUWidgetProcedure is the fully-qualified name of the TmuxBarService's CPUWidget
	// RPC.
	TmuxBarServiceCPUWidgetProcedure = "/tmuxbar.TmuxBarService/CPUWidget"
	// TmuxBarServiceCPUTempWidgetProcedure is the fully-qualified name of the TmuxBarService's
	// CPUTempWidget RPC.
	TmuxBarServiceCPUTempWidgetProcedure = "/tmuxbar.TmuxBarService/CPUTempWidget"
	// TmuxBarServiceBatteryWidgetProcedure is the fully-qualified name of the TmuxBarService's
	// BatteryWidget RPC.
	TmuxBarServiceBatteryWidgetProcedure = "/tmuxbar.TmuxBarService/BatteryWidget"
	// TmuxBarServiceStatusBarProcedure is the fully-qualified name of the TmuxBarService's StatusBar
	// RPC.
	TmuxBarServiceStatusBarProcedure = "/tmuxbar.TmuxBarService/StatusBar"
)

// TmuxBarServiceClient is a client for the tmuxbar.TmuxBarService service.
type TmuxBarServiceClient interface {
	// RAM usage widget: "RAM 6.2/15.9 GB 39%"
	RAMWidget(context.Context, *connect.Request[tmuxbar.RAMWidgetRequest]) (*connect.Response[tmuxbar.RAMWidgetResponse], error)
	// CPU usage widget: "CPU 24% ▁▃▅▇▆▄▃"
	CPUWidget(context.Context, *connect.Request[tmuxbar.CPUWidgetRequest]) (*connect.Response[tmuxbar.CPUWidgetResponse], error)
	// CPU temperature widget: "🌡 65°C"
	CPUTempWidget(context.Context, *connect.Request[tmuxbar.CPUTempWidgetRequest]) (*connect.Response[tmuxbar.CPUTempWidgetResponse], error)
	// Battery widget: "🔋 85%" or "⚡charging"
	BatteryWidget(context.Context, *connect.Request[tmuxbar.BatteryWidgetRequest]) (*connect.Response[tmuxbar.BatteryWidgetResponse], error)
	// Combined compact status: "CPU 24% | RAM 39% | 65°C"
	StatusBar(context.Context, *connect.Request[tmuxbar.StatusBarRequest]) (*connect.Response[tmuxbar.StatusBarResponse], error)
}

// NewTmuxBarServiceClient constructs a client for the tmuxbar.TmuxBarService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTmuxBarServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TmuxBarServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tmuxBarServiceMethods := tmuxbar.File_proto_tmuxbar_tmuxbar_proto.Services().ByName("TmuxBarService").Methods()
	return &tmuxBarServiceClient{
		rAMWidget: connect.NewClient[tmuxbar.RAMWidgetRequest, tmuxbar.RAMWidgetResponse](
			httpClient,
			baseURL+TmuxBarServiceRAMWidgetProcedure,
			connect.WithSchema(tmuxBarServiceMethods.ByName("RAMWidget")),
			connect.WithClientOptions(opts...),
		),
		cPUWidget: connect.NewClient[tmuxbar.CPUWidgetRequest, tmuxbar.CPUWidgetResponse](
			httpClient,
			baseURL+TmuxBarServiceCPUWidgetProcedure,
			connect.WithSchema(tmuxBarServiceMethods.ByName("CPUWidget")),
			connect.WithClientOptions(opts...),
		),
		cPUTempWidget: connect.NewClient[tmuxbar.CPUTempWidgetRequest, tmuxbar.CPUTempWidgetResponse](
			httpClient,
			baseURL+TmuxBarServiceCPUTempWidgetProcedure,
			connect.WithSchema(tmuxBarServiceMethods.ByName("CPUTempWidget")),
			connect.WithClientOptions(opts...),
		),
		batteryWidget: connect.NewClient[tmuxbar.BatteryWidgetRequest, tmuxbar.BatteryWidgetResponse](
			httpClient,
			baseURL+TmuxBarServiceBatteryWidgetProcedure,
			connect.WithSchema(tmuxBarServiceMethods.ByName("BatteryWidget")),
			connect.WithClientOptions(opts...),
		),
		statusBar: connect.NewClient[tmuxbar.StatusBarRequest, tmuxbar.StatusBarResponse](
			httpClient,
			baseURL+TmuxBarServiceStatusBarProcedure,
			connect.WithSchema(tmuxBarServiceMethods.ByName("StatusBar")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tmuxBarServiceClient implements TmuxBarServiceClient.
type tmuxBarServiceClient struct {
	rAMWidget     *connect.Client[tmuxbar.RAMWidgetRequest, tmuxbar.RAMWidgetResponse]
	cPUWidget     *connect.Client[tmuxbar.CPUWidgetRequest, tmuxbar.CPUWidgetResponse]
	cPUTempWidget *connect.Client[tmuxbar.CPUTempWidgetRequest, tmuxbar.CPUTempWidgetResponse]
	batteryWidget *connect.Client[tmuxbar.BatteryWidgetRequest, tmuxbar.BatteryWidgetResponse]
	statusBar     *connect.Client[tmuxbar.StatusBarRequest, tmuxbar.StatusBarResponse]
}

// RAMWidget calls tmuxbar.TmuxBarService.RAMWidget.
func (c *tmuxBarServiceClient) RAMWidget(ctx context.Context, req *connect.Request[tmuxbar.RAMWidgetRequest]) (*connect.Response[tmuxbar.RAMWidgetResponse], error) {
	return c.rAMWidget.CallUnary(ctx, req)
}

// CPUWidget calls tmuxbar.TmuxBarService.CPUWidget.
func (c *tmuxBarServiceClient) CPUWidget(ctx context.Context, req *connect.Request[tmuxbar.CPUWidgetRequest]) (*connect.Response[tmuxbar.CPUWidgetResponse], error) {
	return c.cPUWidget.CallUnary(ctx, req)
}

// CPUTempWidget calls tmuxbar.TmuxBarService.CPUTempWidget.
func (c *tmuxBarServiceClient) CPUTempWidget(ctx context.Context, req *connect.Request[tmuxbar.CPUTempWidgetRequest]) (*connect.Response[tmuxbar.CPUTempWidgetResponse], error) {
	return c.cPUTempWidget.CallUnary(ctx, req)
}

// BatteryWidget calls tmuxbar.TmuxBarService.BatteryWidget.
func (c *tmuxBarServiceClient) BatteryWidget(ctx context.Context, req *connect.Request[tmuxbar.BatteryWidgetRequest]) (*connect.Response[tmuxbar.BatteryWidgetResponse], error) {
	return c.batteryWidget.CallUnary(ctx, req)
}

// StatusBar calls tmuxbar.TmuxBarService.StatusBar.
func (c *tmuxBarServiceClient) StatusBar(ctx context.Context, req *connect.Request[tmuxbar.StatusBarRequest]) (*connect.Response[tmuxbar.StatusBarResponse], error) {
	return c.statusBar.CallUnary(ctx, req)
}

// TmuxBarServiceHandler is an implementation of the tmuxbar.TmuxBarService service.
type TmuxBarServiceHandler interface {
	// RAM usage widget: "RAM 6.2/15.9 GB 39%"
	RAMWidget(context.Context, *connect.Request[tmuxbar.RAMWidgetRequest]) (*connect.Response[tmuxbar.RAMWidgetResponse], error)
	// CPU usage widget: "CPU 24% ▁▃▅▇▆▄▃"
	CPUWidget(context.Context, *connect.Request[tmuxbar.CPUWidgetRequest]) (*connect.Response[tmuxbar.CPUWidgetResponse], error)
	// CPU temperature widget: "🌡 65°C"
	CPUTempWidget(context.Context, *connect.Request[tmuxbar.CPUTempWidgetRequest]) (*connect.Response[tmuxbar.CPUTempWidgetResponse], error)
	// Battery widget: "🔋 85%" or "⚡charging"
	BatteryWidget(context.Context, *connect.Request[tmuxbar.BatteryWidgetRequest]) (*connect.Response[tmuxbar.BatteryWidgetResponse], error)
	// Combined compact status: "CPU 24% | RAM 39% | 65°C"
	StatusBar(context.Context, *connect.Request[tmuxbar.StatusBarRequest]) (*connect.Response[tmuxbar.StatusBarResponse], error)
}

// NewTmuxBarServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTmuxBarServiceHandler(svc TmuxBarServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tmuxBarServiceMethods := tmuxbar.File_proto_tmuxbar_tmuxbar_proto.Services().ByName("TmuxBarService").Methods()
	tmuxBarServiceRAMWidgetHandler := connect.NewUnaryHandler(
		TmuxBarServiceRAMWidgetProcedure,
		svc.RAMWidget,
		connect.WithSchema(tmuxBarServiceMethods.ByName("RAMWidget")),
		connect.WithHandlerOptions(opts...),
	)
	tmuxBarServiceCPUWidgetHandler := connect.NewUnaryHandler(
		TmuxBarServiceCPUWidgetProcedure,
		svc.CPUWidget,
		connect.WithSchema(tmuxBarServiceMethods.ByName("CPUWidget")),
		connect.WithHandlerOptions(opts...),
	)
	tmuxBarServiceCPUTempWidgetHandler := connect.NewUnaryHandler(
		TmuxBarServiceCPUTempWidgetProcedure,
		svc.CPUTempWidget,
		connect.WithSchema(tmuxBarServiceMethods.ByName("CPUTempWidget")),
		connect.WithHandlerOptions(opts...),
	)
	tmuxBarServiceBatteryWidgetHandler := connect.NewUnaryHandler(
		TmuxBarServiceBatteryWidgetProcedure,
		svc.BatteryWidget,
		connect.WithSchema(tmuxBarServiceMethods.ByName("BatteryWidget")),
		connect.WithHandlerOptions(opts...),
	)
	tmuxBarServiceStatusBarHandler := connect.NewUnaryHandler(
		TmuxBarServiceStatusBarProcedure,
		svc.StatusBar,
		connect.WithSchema(tmuxBarServiceMethods.ByName("StatusBar")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tmuxbar.TmuxBarService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TmuxBarServiceRAMWidgetProcedure:
			tmuxBarServiceRAMWidgetHandler.ServeHTTP(w, r)
		case TmuxBarServiceCPUWidgetProcedure:
			tmuxBarServiceCPUWidgetHandler.ServeHTTP(w, r)
		case TmuxBarServiceCPUTempWidgetProcedure:
			tmuxBarServiceCPUTempWidgetHandler.ServeHTTP(w, r)
		case TmuxBarServiceBatteryWidgetProcedure:
			tmuxBarServiceBatteryWidgetHandler.ServeHTTP(w, r)
		case TmuxBarServiceStatusBarProcedure:
			tmuxBarServiceStatusBarHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTmuxBarServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTmuxBarServiceHandler struct{}

func (UnimplementedTmuxBarServiceHandler) RAMWidget(context.Context, *connect.Request[tmuxbar.RAMWidgetRequest]) (*connect.Response[tmuxbar.RAMWidgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tmuxbar.TmuxBarService.RAMWidget is not implemented"))
}

func (UnimplementedTmuxBarServiceHandler) CPUWidget(context.Context, *connect.Request[tmuxbar.CPUWidgetRequest]) (*connect.Response[tmuxbar.CPUWidgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tmuxbar.TmuxBarService.CPUWidget is not implemented"))
}

func (UnimplementedTmuxBarServiceHandler) CPUTempWidget(context.Context, *connect.Request[tmuxbar.CPUTempWidgetRequest]) (*connect.Response[tmuxbar.CPUTempWidgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tmuxbar.TmuxBarService.CPUTempWidget is not implemented"))
}

func (UnimplementedTmuxBarServiceHandler) BatteryWidget(context.Context, *connect.Request[tmuxbar.BatteryWidgetRequest]) (*connect.Response[tmuxbar.BatteryWidgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tmuxbar.TmuxBarService.BatteryWidget is not implemented"))
}

func (UnimplementedTmuxBarServiceHandler) StatusBar(context.Context, *connect.Request[tmuxbar.StatusBarRequest]) (*connect.Response[tmuxbar.StatusBarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tmuxbar.TmuxBarService.StatusBar is not implemented"))
}
