// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dotfilesd/v1/dotfilesdv1/context.proto

package dotfilesdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContextSudoExecRequest — simplified sudo exec for plugins. The daemon
// handles password elicitation; the plugin just specifies the command.
type ContextSudoExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextSudoExecRequest) Reset() {
	*x = ContextSudoExecRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextSudoExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSudoExecRequest) ProtoMessage() {}

func (x *ContextSudoExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSudoExecRequest.ProtoReflect.Descriptor instead.
func (*ContextSudoExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{0}
}

func (x *ContextSudoExecRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ContextSudoExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// ContextSudoExecResponse — result of a sudo exec from a plugin call.
type ContextSudoExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextSudoExecResponse) Reset() {
	*x = ContextSudoExecResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextSudoExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSudoExecResponse) ProtoMessage() {}

func (x *ContextSudoExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSudoExecResponse.ProtoReflect.Descriptor instead.
func (*ContextSudoExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{1}
}

func (x *ContextSudoExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContextSudoExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ContextSudoExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

// LogEntry represents a single log record from a plugin.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // trace, debug, info, warn, error, fatal
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// LogRequest is sent by plugins to submit log entries to the daemon.
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Entry         *LogEntry              `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{3}
}

func (x *LogRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LogRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *LogRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// LogResponse acknowledges receipt of a log entry.
type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{4}
}

// CallPluginRequest asks the daemon to invoke a tool on another plugin.
type CallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     map[string]string      `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginRequest) Reset() {
	*x = CallPluginRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginRequest) ProtoMessage() {}

func (x *CallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginRequest.ProtoReflect.Descriptor instead.
func (*CallPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{5}
}

func (x *CallPluginRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *CallPluginRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallPluginRequest) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CallPluginResponse returns the result of a plugin tool invocation.
type CallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // non-empty if the tool returned a Go error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginResponse) Reset() {
	*x = CallPluginResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginResponse) ProtoMessage() {}

func (x *CallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginResponse.ProtoReflect.Descriptor instead.
func (*CallPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{6}
}

func (x *CallPluginResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CallPluginResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CallPluginResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CallPluginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RunScriptViaContextRequest asks the daemon to run a script.
type RunScriptViaContextRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RunScriptViaContextRequest_Script
	//	*RunScriptViaContextRequest_ScriptPath
	//	*RunScriptViaContextRequest_RegisteredScript
	Source        isRunScriptViaContextRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScriptViaContextRequest) Reset() {
	*x = RunScriptViaContextRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptViaContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptViaContextRequest) ProtoMessage() {}

func (x *RunScriptViaContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptViaContextRequest.ProtoReflect.Descriptor instead.
func (*RunScriptViaContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{7}
}

func (x *RunScriptViaContextRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RunScriptViaContextRequest) GetSource() isRunScriptViaContextRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RunScriptViaContextRequest) GetScript() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptViaContextRequest_Script); ok {
			return x.Script
		}
	}
	return ""
}

func (x *RunScriptViaContextRequest) GetScriptPath() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptViaContextRequest_ScriptPath); ok {
			return x.ScriptPath
		}
	}
	return ""
}

func (x *RunScriptViaContextRequest) GetRegisteredScript() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptViaContextRequest_RegisteredScript); ok {
			return x.RegisteredScript
		}
	}
	return ""
}

type isRunScriptViaContextRequest_Source interface {
	isRunScriptViaContextRequest_Source()
}

type RunScriptViaContextRequest_Script struct {
	Script string `protobuf:"bytes,1,opt,name=script,proto3,oneof"` // inline script content
}

type RunScriptViaContextRequest_ScriptPath struct {
	ScriptPath string `protobuf:"bytes,2,opt,name=script_path,json=scriptPath,proto3,oneof"` // path on the daemon host
}

type RunScriptViaContextRequest_RegisteredScript struct {
	RegisteredScript string `protobuf:"bytes,3,opt,name=registered_script,json=registeredScript,proto3,oneof"` // registered script name (e.g. "git/commit")
}

func (*RunScriptViaContextRequest_Script) isRunScriptViaContextRequest_Source() {}

func (*RunScriptViaContextRequest_ScriptPath) isRunScriptViaContextRequest_Source() {}

func (*RunScriptViaContextRequest_RegisteredScript) isRunScriptViaContextRequest_Source() {}

// RunScriptViaContextResponse returns the result of a script execution.
type RunScriptViaContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllSucceeded  bool                   `protobuf:"varint,1,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	Steps         []*StepResult          `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // overall error if script couldn't run
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScriptViaContextResponse) Reset() {
	*x = RunScriptViaContextResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptViaContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptViaContextResponse) ProtoMessage() {}

func (x *RunScriptViaContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptViaContextResponse.ProtoReflect.Descriptor instead.
func (*RunScriptViaContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP(), []int{8}
}

func (x *RunScriptViaContextResponse) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

func (x *RunScriptViaContextResponse) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RunScriptViaContextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_dotfilesd_v1_dotfilesdv1_context_proto protoreflect.FileDescriptor

const file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDesc = "" +
	"\n" +
	",proto/dotfilesd/v1/dotfilesdv1/context.proto\x12\fdotfilesd.v1\x1a,proto/dotfilesd/v1/dotfilesdv1/session.proto\x1a)proto/dotfilesd/v1/dotfilesdv1/exec.proto\x1a-proto/dotfilesd/v1/dotfilesdv1/feedback.proto\x1a+proto/dotfilesd/v1/dotfilesdv1/script.proto\"c\n" +
	"\x16ContextSudoExecRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"f\n" +
	"\x17ContextSudoExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"\xc1\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2&.dotfilesd.v1.LogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\n" +
	"LogRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12,\n" +
	"\x05entry\x18\x02 \x01(\v2\x16.dotfilesd.v1.LogEntryR\x05entry\"\r\n" +
	"\vLogResponse\"\x8e\x02\n" +
	"\x11CallPluginRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12L\n" +
	"\targuments\x18\x03 \x03(\v2..dotfilesd.v1.CallPluginRequest.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x12CallPluginResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xc3\x01\n" +
	"\x1aRunScriptViaContextRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x18\n" +
	"\x06script\x18\x01 \x01(\tH\x00R\x06script\x12!\n" +
	"\vscript_path\x18\x02 \x01(\tH\x00R\n" +
	"scriptPath\x12-\n" +
	"\x11registered_script\x18\x03 \x01(\tH\x00R\x10registeredScriptB\b\n" +
	"\x06source\"\x88\x01\n" +
	"\x1bRunScriptViaContextResponse\x12#\n" +
	"\rall_succeeded\x18\x01 \x01(\bR\fallSucceeded\x12.\n" +
	"\x05steps\x18\x02 \x03(\v2\x18.dotfilesd.v1.StepResultR\x05steps\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xfd\x04\n" +
	"\x10ExecutionContext\x12=\n" +
	"\x04Exec\x12\x19.dotfilesd.v1.ExecRequest\x1a\x1a.dotfilesd.v1.ExecResponse\x12W\n" +
	"\bSudoExec\x12$.dotfilesd.v1.ContextSudoExecRequest\x1a%.dotfilesd.v1.ContextSudoExecResponse\x12G\n" +
	"\fRequestInput\x12\x1a.dotfilesd.v1.InputRequest\x1a\x1b.dotfilesd.v1.InputResponse\x12M\n" +
	"\x0eRequestConfirm\x12\x1c.dotfilesd.v1.ConfirmRequest\x1a\x1d.dotfilesd.v1.ConfirmResponse\x12J\n" +
	"\rRequestChoose\x12\x1b.dotfilesd.v1.ChooseRequest\x1a\x1c.dotfilesd.v1.ChooseResponse\x12:\n" +
	"\x03Log\x12\x18.dotfilesd.v1.LogRequest\x1a\x19.dotfilesd.v1.LogResponse\x12O\n" +
	"\n" +
	"CallPlugin\x12\x1f.dotfilesd.v1.CallPluginRequest\x1a .dotfilesd.v1.CallPluginResponse\x12`\n" +
	"\tRunScript\x12(.dotfilesd.v1.RunScriptViaContextRequest\x1a).dotfilesd.v1.RunScriptViaContextResponseB*Z(dotfilesd/proto/dotfilesd/v1/dotfilesdv1b\x06proto3"

var (
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescOnce sync.Once
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescData []byte
)

func file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescGZIP() []byte {
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescOnce.Do(func() {
		file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDesc)))
	})
	return file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDescData
}

var file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_dotfilesd_v1_dotfilesdv1_context_proto_goTypes = []any{
	(*ContextSudoExecRequest)(nil),      // 0: dotfilesd.v1.ContextSudoExecRequest
	(*ContextSudoExecResponse)(nil),     // 1: dotfilesd.v1.ContextSudoExecResponse
	(*LogEntry)(nil),                    // 2: dotfilesd.v1.LogEntry
	(*LogRequest)(nil),                  // 3: dotfilesd.v1.LogRequest
	(*LogResponse)(nil),                 // 4: dotfilesd.v1.LogResponse
	(*CallPluginRequest)(nil),           // 5: dotfilesd.v1.CallPluginRequest
	(*CallPluginResponse)(nil),          // 6: dotfilesd.v1.CallPluginResponse
	(*RunScriptViaContextRequest)(nil),  // 7: dotfilesd.v1.RunScriptViaContextRequest
	(*RunScriptViaContextResponse)(nil), // 8: dotfilesd.v1.RunScriptViaContextResponse
	nil,                                 // 9: dotfilesd.v1.LogEntry.AttributesEntry
	nil,                                 // 10: dotfilesd.v1.CallPluginRequest.ArgumentsEntry
	(*Session)(nil),                     // 11: dotfilesd.v1.Session
	(*StepResult)(nil),                  // 12: dotfilesd.v1.StepResult
	(*ExecRequest)(nil),                 // 13: dotfilesd.v1.ExecRequest
	(*InputRequest)(nil),                // 14: dotfilesd.v1.InputRequest
	(*ConfirmRequest)(nil),              // 15: dotfilesd.v1.ConfirmRequest
	(*ChooseRequest)(nil),               // 16: dotfilesd.v1.ChooseRequest
	(*ExecResponse)(nil),                // 17: dotfilesd.v1.ExecResponse
	(*InputResponse)(nil),               // 18: dotfilesd.v1.InputResponse
	(*ConfirmResponse)(nil),             // 19: dotfilesd.v1.ConfirmResponse
	(*ChooseResponse)(nil),              // 20: dotfilesd.v1.ChooseResponse
}
var file_proto_dotfilesd_v1_dotfilesdv1_context_proto_depIdxs = []int32{
	11, // 0: dotfilesd.v1.ContextSudoExecRequest.session:type_name -> dotfilesd.v1.Session
	9,  // 1: dotfilesd.v1.LogEntry.attributes:type_name -> dotfilesd.v1.LogEntry.AttributesEntry
	11, // 2: dotfilesd.v1.LogRequest.session:type_name -> dotfilesd.v1.Session
	2,  // 3: dotfilesd.v1.LogRequest.entry:type_name -> dotfilesd.v1.LogEntry
	11, // 4: dotfilesd.v1.CallPluginRequest.session:type_name -> dotfilesd.v1.Session
	10, // 5: dotfilesd.v1.CallPluginRequest.arguments:type_name -> dotfilesd.v1.CallPluginRequest.ArgumentsEntry
	11, // 6: dotfilesd.v1.RunScriptViaContextRequest.session:type_name -> dotfilesd.v1.Session
	12, // 7: dotfilesd.v1.RunScriptViaContextResponse.steps:type_name -> dotfilesd.v1.StepResult
	13, // 8: dotfilesd.v1.ExecutionContext.Exec:input_type -> dotfilesd.v1.ExecRequest
	0,  // 9: dotfilesd.v1.ExecutionContext.SudoExec:input_type -> dotfilesd.v1.ContextSudoExecRequest
	14, // 10: dotfilesd.v1.ExecutionContext.RequestInput:input_type -> dotfilesd.v1.InputRequest
	15, // 11: dotfilesd.v1.ExecutionContext.RequestConfirm:input_type -> dotfilesd.v1.ConfirmRequest
	16, // 12: dotfilesd.v1.ExecutionContext.RequestChoose:input_type -> dotfilesd.v1.ChooseRequest
	3,  // 13: dotfilesd.v1.ExecutionContext.Log:input_type -> dotfilesd.v1.LogRequest
	5,  // 14: dotfilesd.v1.ExecutionContext.CallPlugin:input_type -> dotfilesd.v1.CallPluginRequest
	7,  // 15: dotfilesd.v1.ExecutionContext.RunScript:input_type -> dotfilesd.v1.RunScriptViaContextRequest
	17, // 16: dotfilesd.v1.ExecutionContext.Exec:output_type -> dotfilesd.v1.ExecResponse
	1,  // 17: dotfilesd.v1.ExecutionContext.SudoExec:output_type -> dotfilesd.v1.ContextSudoExecResponse
	18, // 18: dotfilesd.v1.ExecutionContext.RequestInput:output_type -> dotfilesd.v1.InputResponse
	19, // 19: dotfilesd.v1.ExecutionContext.RequestConfirm:output_type -> dotfilesd.v1.ConfirmResponse
	20, // 20: dotfilesd.v1.ExecutionContext.RequestChoose:output_type -> dotfilesd.v1.ChooseResponse
	4,  // 21: dotfilesd.v1.ExecutionContext.Log:output_type -> dotfilesd.v1.LogResponse
	6,  // 22: dotfilesd.v1.ExecutionContext.CallPlugin:output_type -> dotfilesd.v1.CallPluginResponse
	8,  // 23: dotfilesd.v1.ExecutionContext.RunScript:output_type -> dotfilesd.v1.RunScriptViaContextResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_dotfilesd_v1_dotfilesdv1_context_proto_init() }
func file_proto_dotfilesd_v1_dotfilesdv1_context_proto_init() {
	if File_proto_dotfilesd_v1_dotfilesdv1_context_proto != nil {
		return
	}
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_exec_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_feedback_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes[7].OneofWrappers = []any{
		(*RunScriptViaContextRequest_Script)(nil),
		(*RunScriptViaContextRequest_ScriptPath)(nil),
		(*RunScriptViaContextRequest_RegisteredScript)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dotfilesd_v1_dotfilesdv1_context_proto_goTypes,
		DependencyIndexes: file_proto_dotfilesd_v1_dotfilesdv1_context_proto_depIdxs,
		MessageInfos:      file_proto_dotfilesd_v1_dotfilesdv1_context_proto_msgTypes,
	}.Build()
	File_proto_dotfilesd_v1_dotfilesdv1_context_proto = out.File
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_goTypes = nil
	file_proto_dotfilesd_v1_dotfilesdv1_context_proto_depIdxs = nil
}
