// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dotfilesd/v1/dotfilesdv1/extension.proto

package dotfilesdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescriptorRequest) Reset() {
	*x = GetDescriptorRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorRequest) ProtoMessage() {}

func (x *GetDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{0}
}

type GetDescriptorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ExtensionDescriptor   `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescriptorResponse) Reset() {
	*x = GetDescriptorResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescriptorResponse) ProtoMessage() {}

func (x *GetDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{1}
}

func (x *GetDescriptorResponse) GetDescriptor_() *ExtensionDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

// ExtensionDescriptor describes a plugin's capabilities. The daemon uses
// this metadata to auto-generate CLI commands and MCP tool definitions.
type ExtensionDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique plugin name (e.g. "weather", "backup"). Used as the CLI command
	// namespace and the MCP tool name prefix.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable display name (e.g. "Weather Service").
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Plugin version (semver).
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Short description shown in help text and tool listings.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Tools exposed by this plugin.
	Tools         []*ToolDescriptor `protobuf:"bytes,10,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionDescriptor) Reset() {
	*x = ExtensionDescriptor{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDescriptor) ProtoMessage() {}

func (x *ExtensionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDescriptor.ProtoReflect.Descriptor instead.
func (*ExtensionDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{2}
}

func (x *ExtensionDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ExtensionDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExtensionDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtensionDescriptor) GetTools() []*ToolDescriptor {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolDescriptor describes a single tool/command exposed by a plugin.
type ToolDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name (e.g. "forecast"). Scoped within the plugin: the daemon
	// qualifies it as "<plugin>_<tool>" for MCP and "<plugin> <tool>" for CLI.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of what this tool does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Input schema describing the tool's parameters (JSON Schema-like).
	Input *ToolInputSchema `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// CLI-specific hints for command generation.
	Cli           *CLIHints `protobuf:"bytes,10,opt,name=cli,proto3" json:"cli,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDescriptor) Reset() {
	*x = ToolDescriptor{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptor) ProtoMessage() {}

func (x *ToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptor.ProtoReflect.Descriptor instead.
func (*ToolDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDescriptor) GetInput() *ToolInputSchema {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolDescriptor) GetCli() *CLIHints {
	if x != nil {
		return x.Cli
	}
	return nil
}

// ToolInputSchema describes the expected input for a tool.
type ToolInputSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always "object" for now.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Map of parameter name to its schema.
	Properties map[string]*PropertySchema `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// List of parameter names that are required.
	Required      []string `protobuf:"bytes,3,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInputSchema) Reset() {
	*x = ToolInputSchema{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInputSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInputSchema) ProtoMessage() {}

func (x *ToolInputSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInputSchema.ProtoReflect.Descriptor instead.
func (*ToolInputSchema) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ToolInputSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolInputSchema) GetProperties() map[string]*PropertySchema {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ToolInputSchema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

// PropertySchema describes a single parameter.
type PropertySchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type: "string", "integer", "boolean", "number", "enum".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Human-readable description of the parameter.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Allowed values for enum type.
	Enum []string `protobuf:"bytes,3,rep,name=enum,proto3" json:"enum,omitempty"`
	// Default value (string representation).
	Default string `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	// Whether the default value is set.
	HasDefault    bool `protobuf:"varint,5,opt,name=has_default,json=hasDefault,proto3" json:"has_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertySchema) Reset() {
	*x = PropertySchema{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertySchema) ProtoMessage() {}

func (x *PropertySchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertySchema.ProtoReflect.Descriptor instead.
func (*PropertySchema) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{5}
}

func (x *PropertySchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PropertySchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PropertySchema) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *PropertySchema) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *PropertySchema) GetHasDefault() bool {
	if x != nil {
		return x.HasDefault
	}
	return false
}

// CLIHints provides the daemon with information to generate the CLI command
// tree and help text for this tool.
type CLIHints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subcommand path relative to the plugin root, space-separated.
	// Example: "forecast" becomes "dotfilesctl <plugin> forecast".
	// Nested: "weather forecast" becomes "dotfilesctl <plugin> weather forecast".
	CommandPath string `protobuf:"bytes,1,opt,name=command_path,json=commandPath,proto3" json:"command_path,omitempty"`
	// Category name for grouping in help output (e.g. "Weather", "System").
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Maps argument names to CLI flag names for positional arguments.
	// Example: {"location": "--location"} makes the argument a flag instead
	// of a positional arg.
	FlagMapping   map[string]string `protobuf:"bytes,3,rep,name=flag_mapping,json=flagMapping,proto3" json:"flag_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIHints) Reset() {
	*x = CLIHints{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIHints) ProtoMessage() {}

func (x *CLIHints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIHints.ProtoReflect.Descriptor instead.
func (*CLIHints) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{6}
}

func (x *CLIHints) GetCommandPath() string {
	if x != nil {
		return x.CommandPath
	}
	return ""
}

func (x *CLIHints) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CLIHints) GetFlagMapping() map[string]string {
	if x != nil {
		return x.FlagMapping
	}
	return nil
}

// CallToolRequest invokes a tool with the given named arguments.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the tool to invoke (matches ToolDescriptor.name).
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Arguments as key-value pairs. Values are JSON-encoded strings.
	// The plugin deserializes them as needed.
	Arguments     map[string]string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{7}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CallToolResponse returns the result of a tool invocation.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable text output (stdout-style).
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Whether the tool returned an error.
	IsError bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Structured result data as JSON (optional, for rich clients).
	StructuredData string `protobuf:"bytes,3,opt,name=structured_data,json=structuredData,proto3" json:"structured_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *CallToolResponse) GetStructuredData() string {
	if x != nil {
		return x.StructuredData
	}
	return ""
}

var File_proto_dotfilesd_v1_dotfilesdv1_extension_proto protoreflect.FileDescriptor

const file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDesc = "" +
	"\n" +
	".proto/dotfilesd/v1/dotfilesdv1/extension.proto\x12\fdotfilesd.v1\"\x16\n" +
	"\x14GetDescriptorRequest\"Z\n" +
	"\x15GetDescriptorResponse\x12A\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2!.dotfilesd.v1.ExtensionDescriptorR\n" +
	"descriptor\"\xbc\x01\n" +
	"\x13ExtensionDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x05tools\x18\n" +
	" \x03(\v2\x1c.dotfilesd.v1.ToolDescriptorR\x05tools\"\xa5\x01\n" +
	"\x0eToolDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\x05input\x18\x03 \x01(\v2\x1d.dotfilesd.v1.ToolInputSchemaR\x05input\x12(\n" +
	"\x03cli\x18\n" +
	" \x01(\v2\x16.dotfilesd.v1.CLIHintsR\x03cli\"\xed\x01\n" +
	"\x0fToolInputSchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12M\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2-.dotfilesd.v1.ToolInputSchema.PropertiesEntryR\n" +
	"properties\x12\x1a\n" +
	"\brequired\x18\x03 \x03(\tR\brequired\x1a[\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.dotfilesd.v1.PropertySchemaR\x05value:\x028\x01\"\x95\x01\n" +
	"\x0ePropertySchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04enum\x18\x03 \x03(\tR\x04enum\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x1f\n" +
	"\vhas_default\x18\x05 \x01(\bR\n" +
	"hasDefault\"\xd5\x01\n" +
	"\bCLIHints\x12!\n" +
	"\fcommand_path\x18\x01 \x01(\tR\vcommandPath\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12J\n" +
	"\fflag_mapping\x18\x03 \x03(\v2'.dotfilesd.v1.CLIHints.FlagMappingEntryR\vflagMapping\x1a>\n" +
	"\x10FlagMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12J\n" +
	"\targuments\x18\x02 \x03(\v2,.dotfilesd.v1.CallToolRequest.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x10CallToolResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12'\n" +
	"\x0fstructured_data\x18\x03 \x01(\tR\x0estructuredData2\xb7\x01\n" +
	"\x10ExtensionService\x12X\n" +
	"\rGetDescriptor\x12\".dotfilesd.v1.GetDescriptorRequest\x1a#.dotfilesd.v1.GetDescriptorResponse\x12I\n" +
	"\bCallTool\x12\x1d.dotfilesd.v1.CallToolRequest\x1a\x1e.dotfilesd.v1.CallToolResponseB*Z(dotfilesd/proto/dotfilesd/v1/dotfilesdv1b\x06proto3"

var (
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescOnce sync.Once
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescData []byte
)

func file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescGZIP() []byte {
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescOnce.Do(func() {
		file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDesc)))
	})
	return file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDescData
}

var file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_goTypes = []any{
	(*GetDescriptorRequest)(nil),  // 0: dotfilesd.v1.GetDescriptorRequest
	(*GetDescriptorResponse)(nil), // 1: dotfilesd.v1.GetDescriptorResponse
	(*ExtensionDescriptor)(nil),   // 2: dotfilesd.v1.ExtensionDescriptor
	(*ToolDescriptor)(nil),        // 3: dotfilesd.v1.ToolDescriptor
	(*ToolInputSchema)(nil),       // 4: dotfilesd.v1.ToolInputSchema
	(*PropertySchema)(nil),        // 5: dotfilesd.v1.PropertySchema
	(*CLIHints)(nil),              // 6: dotfilesd.v1.CLIHints
	(*CallToolRequest)(nil),       // 7: dotfilesd.v1.CallToolRequest
	(*CallToolResponse)(nil),      // 8: dotfilesd.v1.CallToolResponse
	nil,                           // 9: dotfilesd.v1.ToolInputSchema.PropertiesEntry
	nil,                           // 10: dotfilesd.v1.CLIHints.FlagMappingEntry
	nil,                           // 11: dotfilesd.v1.CallToolRequest.ArgumentsEntry
}
var file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_depIdxs = []int32{
	2,  // 0: dotfilesd.v1.GetDescriptorResponse.descriptor:type_name -> dotfilesd.v1.ExtensionDescriptor
	3,  // 1: dotfilesd.v1.ExtensionDescriptor.tools:type_name -> dotfilesd.v1.ToolDescriptor
	4,  // 2: dotfilesd.v1.ToolDescriptor.input:type_name -> dotfilesd.v1.ToolInputSchema
	6,  // 3: dotfilesd.v1.ToolDescriptor.cli:type_name -> dotfilesd.v1.CLIHints
	9,  // 4: dotfilesd.v1.ToolInputSchema.properties:type_name -> dotfilesd.v1.ToolInputSchema.PropertiesEntry
	10, // 5: dotfilesd.v1.CLIHints.flag_mapping:type_name -> dotfilesd.v1.CLIHints.FlagMappingEntry
	11, // 6: dotfilesd.v1.CallToolRequest.arguments:type_name -> dotfilesd.v1.CallToolRequest.ArgumentsEntry
	5,  // 7: dotfilesd.v1.ToolInputSchema.PropertiesEntry.value:type_name -> dotfilesd.v1.PropertySchema
	0,  // 8: dotfilesd.v1.ExtensionService.GetDescriptor:input_type -> dotfilesd.v1.GetDescriptorRequest
	7,  // 9: dotfilesd.v1.ExtensionService.CallTool:input_type -> dotfilesd.v1.CallToolRequest
	1,  // 10: dotfilesd.v1.ExtensionService.GetDescriptor:output_type -> dotfilesd.v1.GetDescriptorResponse
	8,  // 11: dotfilesd.v1.ExtensionService.CallTool:output_type -> dotfilesd.v1.CallToolResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_init() }
func file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_init() {
	if File_proto_dotfilesd_v1_dotfilesdv1_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_goTypes,
		DependencyIndexes: file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_depIdxs,
		MessageInfos:      file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_msgTypes,
	}.Build()
	File_proto_dotfilesd_v1_dotfilesdv1_extension_proto = out.File
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_goTypes = nil
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_depIdxs = nil
}
