// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dotfilesd/v1/dotfilesdv1/plugin.proto

package dotfilesdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginTreeEntry represents a node in the plugin directory hierarchy.
// Directories are category groups; leaf entries are loaded Go plugins
// with their ExtensionDescriptor.
type PluginTreeEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basename (e.g. "weather", "tools").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Relative path from the plugins root (e.g. "tools/weather").
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// True if this is a directory with children (not a plugin itself).
	IsDirectory bool `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	// Description from README.md front matter or plugin descriptor.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the entry is enabled (controlled via README.md front matter).
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Child entries (only for directories).
	Children []*PluginTreeEntry `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	// The plugin descriptor, set only for leaf (loaded) entries.
	Plugin *ExtensionDescriptor `protobuf:"bytes,7,opt,name=plugin,proto3" json:"plugin,omitempty"`
	// Plugin type: "server" (supervised) or "command" (ephemeral).
	Type          string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTreeEntry) Reset() {
	*x = PluginTreeEntry{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTreeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTreeEntry) ProtoMessage() {}

func (x *PluginTreeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTreeEntry.ProtoReflect.Descriptor instead.
func (*PluginTreeEntry) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginTreeEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginTreeEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginTreeEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *PluginTreeEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginTreeEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PluginTreeEntry) GetChildren() []*PluginTreeEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *PluginTreeEntry) GetPlugin() *ExtensionDescriptor {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *PluginTreeEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListPluginTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginTreeRequest) Reset() {
	*x = ListPluginTreeRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginTreeRequest) ProtoMessage() {}

func (x *ListPluginTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginTreeRequest.ProtoReflect.Descriptor instead.
func (*ListPluginTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginTreeRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListPluginTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PluginTreeEntry     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginTreeResponse) Reset() {
	*x = ListPluginTreeResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginTreeResponse) ProtoMessage() {}

func (x *ListPluginTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginTreeResponse.ProtoReflect.Descriptor instead.
func (*ListPluginTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginTreeResponse) GetEntries() []*PluginTreeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ListPluginsRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*ExtensionDescriptor `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ListPluginsResponse) GetPlugins() []*ExtensionDescriptor {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type CallPluginToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     map[string]string      `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginToolRequest) Reset() {
	*x = CallPluginToolRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginToolRequest) ProtoMessage() {}

func (x *CallPluginToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginToolRequest.ProtoReflect.Descriptor instead.
func (*CallPluginToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CallPluginToolRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CallPluginToolRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *CallPluginToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallPluginToolRequest) GetArguments() map[string]string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type CallPluginToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A chunk of stdout output from the tool.
	StdoutChunk []byte `protobuf:"bytes,1,opt,name=stdout_chunk,json=stdoutChunk,proto3" json:"stdout_chunk,omitempty"`
	// A chunk of stderr output from the tool.
	StderrChunk []byte `protobuf:"bytes,2,opt,name=stderr_chunk,json=stderrChunk,proto3" json:"stderr_chunk,omitempty"`
	// If true, this is the final message — the tool has finished.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// If done is true, the tool's error message (empty means success).
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginToolResponse) Reset() {
	*x = CallPluginToolResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginToolResponse) ProtoMessage() {}

func (x *CallPluginToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginToolResponse.ProtoReflect.Descriptor instead.
func (*CallPluginToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CallPluginToolResponse) GetStdoutChunk() []byte {
	if x != nil {
		return x.StdoutChunk
	}
	return nil
}

func (x *CallPluginToolResponse) GetStderrChunk() []byte {
	if x != nil {
		return x.StderrChunk
	}
	return nil
}

func (x *CallPluginToolResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CallPluginToolResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_dotfilesd_v1_dotfilesdv1_plugin_proto protoreflect.FileDescriptor

const file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDesc = "" +
	"\n" +
	"+proto/dotfilesd/v1/dotfilesdv1/plugin.proto\x12\fdotfilesd.v1\x1a,proto/dotfilesd/v1/dotfilesdv1/session.proto\x1a.proto/dotfilesd/v1/dotfilesdv1/extension.proto\"\xa2\x02\n" +
	"\x0fPluginTreeEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x129\n" +
	"\bchildren\x18\x06 \x03(\v2\x1d.dotfilesd.v1.PluginTreeEntryR\bchildren\x129\n" +
	"\x06plugin\x18\a \x01(\v2!.dotfilesd.v1.ExtensionDescriptorR\x06plugin\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\"H\n" +
	"\x15ListPluginTreeRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"Q\n" +
	"\x16ListPluginTreeResponse\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.dotfilesd.v1.PluginTreeEntryR\aentries\"E\n" +
	"\x12ListPluginsRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"R\n" +
	"\x13ListPluginsResponse\x12;\n" +
	"\aplugins\x18\x01 \x03(\v2!.dotfilesd.v1.ExtensionDescriptorR\aplugins\"\x96\x02\n" +
	"\x15CallPluginToolRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12P\n" +
	"\targuments\x18\x03 \x03(\v22.dotfilesd.v1.CallPluginToolRequest.ArgumentsEntryR\targuments\x1a<\n" +
	"\x0eArgumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x16CallPluginToolResponse\x12!\n" +
	"\fstdout_chunk\x18\x01 \x01(\fR\vstdoutChunk\x12!\n" +
	"\fstderr_chunk\x18\x02 \x01(\fR\vstderrChunk\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\x9f\x02\n" +
	"\rPluginService\x12R\n" +
	"\vListPlugins\x12 .dotfilesd.v1.ListPluginsRequest\x1a!.dotfilesd.v1.ListPluginsResponse\x12[\n" +
	"\x0eListPluginTree\x12#.dotfilesd.v1.ListPluginTreeRequest\x1a$.dotfilesd.v1.ListPluginTreeResponse\x12]\n" +
	"\x0eCallPluginTool\x12#.dotfilesd.v1.CallPluginToolRequest\x1a$.dotfilesd.v1.CallPluginToolResponse0\x01B*Z(dotfilesd/proto/dotfilesd/v1/dotfilesdv1b\x06proto3"

var (
	file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescOnce sync.Once
	file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescData []byte
)

func file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescGZIP() []byte {
	file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDesc)))
	})
	return file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDescData
}

var file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_goTypes = []any{
	(*PluginTreeEntry)(nil),        // 0: dotfilesd.v1.PluginTreeEntry
	(*ListPluginTreeRequest)(nil),  // 1: dotfilesd.v1.ListPluginTreeRequest
	(*ListPluginTreeResponse)(nil), // 2: dotfilesd.v1.ListPluginTreeResponse
	(*ListPluginsRequest)(nil),     // 3: dotfilesd.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),    // 4: dotfilesd.v1.ListPluginsResponse
	(*CallPluginToolRequest)(nil),  // 5: dotfilesd.v1.CallPluginToolRequest
	(*CallPluginToolResponse)(nil), // 6: dotfilesd.v1.CallPluginToolResponse
	nil,                            // 7: dotfilesd.v1.CallPluginToolRequest.ArgumentsEntry
	(*ExtensionDescriptor)(nil),    // 8: dotfilesd.v1.ExtensionDescriptor
	(*Session)(nil),                // 9: dotfilesd.v1.Session
}
var file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_depIdxs = []int32{
	0,  // 0: dotfilesd.v1.PluginTreeEntry.children:type_name -> dotfilesd.v1.PluginTreeEntry
	8,  // 1: dotfilesd.v1.PluginTreeEntry.plugin:type_name -> dotfilesd.v1.ExtensionDescriptor
	9,  // 2: dotfilesd.v1.ListPluginTreeRequest.session:type_name -> dotfilesd.v1.Session
	0,  // 3: dotfilesd.v1.ListPluginTreeResponse.entries:type_name -> dotfilesd.v1.PluginTreeEntry
	9,  // 4: dotfilesd.v1.ListPluginsRequest.session:type_name -> dotfilesd.v1.Session
	8,  // 5: dotfilesd.v1.ListPluginsResponse.plugins:type_name -> dotfilesd.v1.ExtensionDescriptor
	9,  // 6: dotfilesd.v1.CallPluginToolRequest.session:type_name -> dotfilesd.v1.Session
	7,  // 7: dotfilesd.v1.CallPluginToolRequest.arguments:type_name -> dotfilesd.v1.CallPluginToolRequest.ArgumentsEntry
	3,  // 8: dotfilesd.v1.PluginService.ListPlugins:input_type -> dotfilesd.v1.ListPluginsRequest
	1,  // 9: dotfilesd.v1.PluginService.ListPluginTree:input_type -> dotfilesd.v1.ListPluginTreeRequest
	5,  // 10: dotfilesd.v1.PluginService.CallPluginTool:input_type -> dotfilesd.v1.CallPluginToolRequest
	4,  // 11: dotfilesd.v1.PluginService.ListPlugins:output_type -> dotfilesd.v1.ListPluginsResponse
	2,  // 12: dotfilesd.v1.PluginService.ListPluginTree:output_type -> dotfilesd.v1.ListPluginTreeResponse
	6,  // 13: dotfilesd.v1.PluginService.CallPluginTool:output_type -> dotfilesd.v1.CallPluginToolResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_init() }
func file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_init() {
	if File_proto_dotfilesd_v1_dotfilesdv1_plugin_proto != nil {
		return
	}
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_extension_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_msgTypes,
	}.Build()
	File_proto_dotfilesd_v1_dotfilesdv1_plugin_proto = out.File
	file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_goTypes = nil
	file_proto_dotfilesd_v1_dotfilesdv1_plugin_proto_depIdxs = nil
}
