// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dotfilesd/v1/dotfilesdv1/script.proto

package dotfilesdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------------------------
// Script source
// ---------------------------------------------------------------------------
type RunScriptRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RunScriptRequest_Script
	//	*RunScriptRequest_ScriptPath
	//	*RunScriptRequest_RegisteredScript
	Source        isRunScriptRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScriptRequest) Reset() {
	*x = RunScriptRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptRequest) ProtoMessage() {}

func (x *RunScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptRequest.ProtoReflect.Descriptor instead.
func (*RunScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{0}
}

func (x *RunScriptRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RunScriptRequest) GetSource() isRunScriptRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RunScriptRequest) GetScript() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptRequest_Script); ok {
			return x.Script
		}
	}
	return ""
}

func (x *RunScriptRequest) GetScriptPath() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptRequest_ScriptPath); ok {
			return x.ScriptPath
		}
	}
	return ""
}

func (x *RunScriptRequest) GetRegisteredScript() string {
	if x != nil {
		if x, ok := x.Source.(*RunScriptRequest_RegisteredScript); ok {
			return x.RegisteredScript
		}
	}
	return ""
}

type isRunScriptRequest_Source interface {
	isRunScriptRequest_Source()
}

type RunScriptRequest_Script struct {
	Script string `protobuf:"bytes,1,opt,name=script,proto3,oneof"` // inline script content
}

type RunScriptRequest_ScriptPath struct {
	ScriptPath string `protobuf:"bytes,2,opt,name=script_path,json=scriptPath,proto3,oneof"` // absolute path to a .dsh file on the daemon host
}

type RunScriptRequest_RegisteredScript struct {
	RegisteredScript string `protobuf:"bytes,3,opt,name=registered_script,json=registeredScript,proto3,oneof"` // relative path in the scripts tree (e.g. "git/commit")
}

func (*RunScriptRequest_Script) isRunScriptRequest_Source() {}

func (*RunScriptRequest_ScriptPath) isRunScriptRequest_Source() {}

func (*RunScriptRequest_RegisteredScript) isRunScriptRequest_Source() {}

// ---------------------------------------------------------------------------
// Per-step result
// ---------------------------------------------------------------------------
type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepNumber    int32                  `protobuf:"varint,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	SourceLine    string                 `protobuf:"bytes,2,opt,name=source_line,json=sourceLine,proto3" json:"source_line,omitempty"`
	StepKind      string                 `protobuf:"bytes,3,opt,name=step_kind,json=stepKind,proto3" json:"step_kind,omitempty"` // "exec", "confirm", "input", "choose"
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	FeedbackValue string                 `protobuf:"bytes,7,opt,name=feedback_value,json=feedbackValue,proto3" json:"feedback_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{1}
}

func (x *StepResult) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *StepResult) GetSourceLine() string {
	if x != nil {
		return x.SourceLine
	}
	return ""
}

func (x *StepResult) GetStepKind() string {
	if x != nil {
		return x.StepKind
	}
	return ""
}

func (x *StepResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StepResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StepResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StepResult) GetFeedbackValue() string {
	if x != nil {
		return x.FeedbackValue
	}
	return ""
}

type RunScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*StepResult          `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	AllSucceeded  bool                   `protobuf:"varint,2,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunScriptResponse) Reset() {
	*x = RunScriptResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunScriptResponse) ProtoMessage() {}

func (x *RunScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunScriptResponse.ProtoReflect.Descriptor instead.
func (*RunScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{2}
}

func (x *RunScriptResponse) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RunScriptResponse) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

func (x *RunScriptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---------------------------------------------------------------------------
// Script registry (ListScripts)
// ---------------------------------------------------------------------------
type ListScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,100,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsRequest) Reset() {
	*x = ListScriptsRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsRequest) ProtoMessage() {}

func (x *ListScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{3}
}

func (x *ListScriptsRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListScriptsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root-level tree of registered scripts.
	Entries       []*ScriptEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsResponse) Reset() {
	*x = ListScriptsResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsResponse) ProtoMessage() {}

func (x *ListScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsResponse.ProtoReflect.Descriptor instead.
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{4}
}

func (x *ListScriptsResponse) GetEntries() []*ScriptEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ScriptEntry represents a node in the scripts tree.
type ScriptEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path from the scripts root (e.g. "git/commit", "system").
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Basename without .dsh (e.g. "commit", "system").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// True if this is a directory with children.
	IsDirectory bool `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	// Description from README.md front matter or script front matter.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Whether the entry is enabled (can be disabled via README.md exclude list).
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Child entries (only for directories).
	Children []*ScriptEntry `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	// Parameter definitions from script front matter.
	Params        []*ScriptParam `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptEntry) Reset() {
	*x = ScriptEntry{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptEntry) ProtoMessage() {}

func (x *ScriptEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptEntry.ProtoReflect.Descriptor instead.
func (*ScriptEntry) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{5}
}

func (x *ScriptEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ScriptEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScriptEntry) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *ScriptEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScriptEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScriptEntry) GetChildren() []*ScriptEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScriptEntry) GetParams() []*ScriptParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type ScriptParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptParam) Reset() {
	*x = ScriptParam{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptParam) ProtoMessage() {}

func (x *ScriptParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptParam.ProtoReflect.Descriptor instead.
func (*ScriptParam) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP(), []int{6}
}

func (x *ScriptParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScriptParam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScriptParam) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ScriptParam) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

var File_proto_dotfilesd_v1_dotfilesdv1_script_proto protoreflect.FileDescriptor

const file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDesc = "" +
	"\n" +
	"+proto/dotfilesd/v1/dotfilesdv1/script.proto\x12\fdotfilesd.v1\x1a,proto/dotfilesd/v1/dotfilesdv1/session.proto\"\xb9\x01\n" +
	"\x10RunScriptRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\x12\x18\n" +
	"\x06script\x18\x01 \x01(\tH\x00R\x06script\x12!\n" +
	"\vscript_path\x18\x02 \x01(\tH\x00R\n" +
	"scriptPath\x12-\n" +
	"\x11registered_script\x18\x03 \x01(\tH\x00R\x10registeredScriptB\b\n" +
	"\x06source\"\xdf\x01\n" +
	"\n" +
	"StepResult\x12\x1f\n" +
	"\vstep_number\x18\x01 \x01(\x05R\n" +
	"stepNumber\x12\x1f\n" +
	"\vsource_line\x18\x02 \x01(\tR\n" +
	"sourceLine\x12\x1b\n" +
	"\tstep_kind\x18\x03 \x01(\tR\bstepKind\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\x12%\n" +
	"\x0efeedback_value\x18\a \x01(\tR\rfeedbackValue\"~\n" +
	"\x11RunScriptResponse\x12.\n" +
	"\x05steps\x18\x01 \x03(\v2\x18.dotfilesd.v1.StepResultR\x05steps\x12#\n" +
	"\rall_succeeded\x18\x02 \x01(\bR\fallSucceeded\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\x12ListScriptsRequest\x12/\n" +
	"\asession\x18d \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"J\n" +
	"\x13ListScriptsResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.dotfilesd.v1.ScriptEntryR\aentries\"\xfe\x01\n" +
	"\vScriptEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x125\n" +
	"\bchildren\x18\x06 \x03(\v2\x19.dotfilesd.v1.ScriptEntryR\bchildren\x121\n" +
	"\x06params\x18\a \x03(\v2\x19.dotfilesd.v1.ScriptParamR\x06params\"\x84\x01\n" +
	"\vScriptParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue2\xb1\x01\n" +
	"\rScriptService\x12L\n" +
	"\tRunScript\x12\x1e.dotfilesd.v1.RunScriptRequest\x1a\x1f.dotfilesd.v1.RunScriptResponse\x12R\n" +
	"\vListScripts\x12 .dotfilesd.v1.ListScriptsRequest\x1a!.dotfilesd.v1.ListScriptsResponseB*Z(dotfilesd/proto/dotfilesd/v1/dotfilesdv1b\x06proto3"

var (
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescOnce sync.Once
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescData []byte
)

func file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescGZIP() []byte {
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescOnce.Do(func() {
		file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDesc)))
	})
	return file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDescData
}

var file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dotfilesd_v1_dotfilesdv1_script_proto_goTypes = []any{
	(*RunScriptRequest)(nil),    // 0: dotfilesd.v1.RunScriptRequest
	(*StepResult)(nil),          // 1: dotfilesd.v1.StepResult
	(*RunScriptResponse)(nil),   // 2: dotfilesd.v1.RunScriptResponse
	(*ListScriptsRequest)(nil),  // 3: dotfilesd.v1.ListScriptsRequest
	(*ListScriptsResponse)(nil), // 4: dotfilesd.v1.ListScriptsResponse
	(*ScriptEntry)(nil),         // 5: dotfilesd.v1.ScriptEntry
	(*ScriptParam)(nil),         // 6: dotfilesd.v1.ScriptParam
	(*Session)(nil),             // 7: dotfilesd.v1.Session
}
var file_proto_dotfilesd_v1_dotfilesdv1_script_proto_depIdxs = []int32{
	7, // 0: dotfilesd.v1.RunScriptRequest.session:type_name -> dotfilesd.v1.Session
	1, // 1: dotfilesd.v1.RunScriptResponse.steps:type_name -> dotfilesd.v1.StepResult
	7, // 2: dotfilesd.v1.ListScriptsRequest.session:type_name -> dotfilesd.v1.Session
	5, // 3: dotfilesd.v1.ListScriptsResponse.entries:type_name -> dotfilesd.v1.ScriptEntry
	5, // 4: dotfilesd.v1.ScriptEntry.children:type_name -> dotfilesd.v1.ScriptEntry
	6, // 5: dotfilesd.v1.ScriptEntry.params:type_name -> dotfilesd.v1.ScriptParam
	0, // 6: dotfilesd.v1.ScriptService.RunScript:input_type -> dotfilesd.v1.RunScriptRequest
	3, // 7: dotfilesd.v1.ScriptService.ListScripts:input_type -> dotfilesd.v1.ListScriptsRequest
	2, // 8: dotfilesd.v1.ScriptService.RunScript:output_type -> dotfilesd.v1.RunScriptResponse
	4, // 9: dotfilesd.v1.ScriptService.ListScripts:output_type -> dotfilesd.v1.ListScriptsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dotfilesd_v1_dotfilesdv1_script_proto_init() }
func file_proto_dotfilesd_v1_dotfilesdv1_script_proto_init() {
	if File_proto_dotfilesd_v1_dotfilesdv1_script_proto != nil {
		return
	}
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_init()
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes[0].OneofWrappers = []any{
		(*RunScriptRequest_Script)(nil),
		(*RunScriptRequest_ScriptPath)(nil),
		(*RunScriptRequest_RegisteredScript)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_script_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dotfilesd_v1_dotfilesdv1_script_proto_goTypes,
		DependencyIndexes: file_proto_dotfilesd_v1_dotfilesdv1_script_proto_depIdxs,
		MessageInfos:      file_proto_dotfilesd_v1_dotfilesdv1_script_proto_msgTypes,
	}.Build()
	File_proto_dotfilesd_v1_dotfilesdv1_script_proto = out.File
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_goTypes = nil
	file_proto_dotfilesd_v1_dotfilesdv1_script_proto_depIdxs = nil
}
