// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dotfilesd/v1/dotfilesdv1/session.proto

package dotfilesdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // unix timestamp (seconds)
	LastActive    int64                  `protobuf:"varint,3,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"` // unix timestamp (seconds)
	RequestCount  int32                  `protobuf:"varint,4,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	Finalized     bool                   `protobuf:"varint,5,opt,name=finalized,proto3" json:"finalized,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *Session) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *Session) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *Session) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type FinalizeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSessionRequest) Reset() {
	*x = FinalizeSessionRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSessionRequest) ProtoMessage() {}

func (x *FinalizeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSessionRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{3}
}

func (x *FinalizeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FinalizeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSessionResponse) Reset() {
	*x = FinalizeSessionResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSessionResponse) ProtoMessage() {}

func (x *FinalizeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSessionResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinalizeSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Callback URL where the client's ClientCallback server is listening
	// (e.g. "http://127.0.0.1:43291").
	CallbackUrl string `protobuf:"bytes,1,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	// Session to register the callback with. If empty the daemon creates a
	// new session.
	SessionId     string `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *ConnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ListSessionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_proto_dotfilesd_v1_dotfilesdv1_session_proto protoreflect.FileDescriptor

const file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDesc = "" +
	"\n" +
	",proto/dotfilesd/v1/dotfilesdv1/session.proto\x12\fdotfilesd.v1\"\x8a\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vlast_active\x18\x03 \x01(\x03R\n" +
	"lastActive\x12#\n" +
	"\rrequest_count\x18\x04 \x01(\x05R\frequestCount\x12\x1c\n" +
	"\tfinalized\x18\x05 \x01(\bR\tfinalized\x123\n" +
	"\x04data\x18\x06 \x03(\v2\x1f.dotfilesd.v1.Session.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\"H\n" +
	"\x15CreateSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"7\n" +
	"\x16FinalizeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\"M\n" +
	"\x17FinalizeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\"E\n" +
	"\x12GetSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"R\n" +
	"\x0eConnectRequest\x12!\n" +
	"\fcallback_url\x18\x01 \x01(\tR\vcallbackUrl\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\"B\n" +
	"\x0fConnectResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.dotfilesd.v1.SessionR\asession\"4\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\"I\n" +
	"\x14ListSessionsResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.dotfilesd.v1.SessionR\bsessions2\xba\x03\n" +
	"\x0eSessionService\x12X\n" +
	"\rCreateSession\x12\".dotfilesd.v1.CreateSessionRequest\x1a#.dotfilesd.v1.CreateSessionResponse\x12F\n" +
	"\aConnect\x12\x1c.dotfilesd.v1.ConnectRequest\x1a\x1d.dotfilesd.v1.ConnectResponse\x12^\n" +
	"\x0fFinalizeSession\x12$.dotfilesd.v1.FinalizeSessionRequest\x1a%.dotfilesd.v1.FinalizeSessionResponse\x12O\n" +
	"\n" +
	"GetSession\x12\x1f.dotfilesd.v1.GetSessionRequest\x1a .dotfilesd.v1.GetSessionResponse\x12U\n" +
	"\fListSessions\x12!.dotfilesd.v1.ListSessionsRequest\x1a\".dotfilesd.v1.ListSessionsResponseB*Z(dotfilesd/proto/dotfilesd/v1/dotfilesdv1b\x06proto3"

var (
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescOnce sync.Once
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescData []byte
)

func file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescGZIP() []byte {
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescOnce.Do(func() {
		file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDesc)))
	})
	return file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDescData
}

var file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_dotfilesd_v1_dotfilesdv1_session_proto_goTypes = []any{
	(*Session)(nil),                 // 0: dotfilesd.v1.Session
	(*CreateSessionRequest)(nil),    // 1: dotfilesd.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),   // 2: dotfilesd.v1.CreateSessionResponse
	(*FinalizeSessionRequest)(nil),  // 3: dotfilesd.v1.FinalizeSessionRequest
	(*FinalizeSessionResponse)(nil), // 4: dotfilesd.v1.FinalizeSessionResponse
	(*GetSessionRequest)(nil),       // 5: dotfilesd.v1.GetSessionRequest
	(*GetSessionResponse)(nil),      // 6: dotfilesd.v1.GetSessionResponse
	(*ConnectRequest)(nil),          // 7: dotfilesd.v1.ConnectRequest
	(*ConnectResponse)(nil),         // 8: dotfilesd.v1.ConnectResponse
	(*ListSessionsRequest)(nil),     // 9: dotfilesd.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),    // 10: dotfilesd.v1.ListSessionsResponse
	nil,                             // 11: dotfilesd.v1.Session.DataEntry
}
var file_proto_dotfilesd_v1_dotfilesdv1_session_proto_depIdxs = []int32{
	11, // 0: dotfilesd.v1.Session.data:type_name -> dotfilesd.v1.Session.DataEntry
	0,  // 1: dotfilesd.v1.CreateSessionResponse.session:type_name -> dotfilesd.v1.Session
	0,  // 2: dotfilesd.v1.GetSessionResponse.session:type_name -> dotfilesd.v1.Session
	0,  // 3: dotfilesd.v1.ConnectResponse.session:type_name -> dotfilesd.v1.Session
	0,  // 4: dotfilesd.v1.ListSessionsResponse.sessions:type_name -> dotfilesd.v1.Session
	1,  // 5: dotfilesd.v1.SessionService.CreateSession:input_type -> dotfilesd.v1.CreateSessionRequest
	7,  // 6: dotfilesd.v1.SessionService.Connect:input_type -> dotfilesd.v1.ConnectRequest
	3,  // 7: dotfilesd.v1.SessionService.FinalizeSession:input_type -> dotfilesd.v1.FinalizeSessionRequest
	5,  // 8: dotfilesd.v1.SessionService.GetSession:input_type -> dotfilesd.v1.GetSessionRequest
	9,  // 9: dotfilesd.v1.SessionService.ListSessions:input_type -> dotfilesd.v1.ListSessionsRequest
	2,  // 10: dotfilesd.v1.SessionService.CreateSession:output_type -> dotfilesd.v1.CreateSessionResponse
	8,  // 11: dotfilesd.v1.SessionService.Connect:output_type -> dotfilesd.v1.ConnectResponse
	4,  // 12: dotfilesd.v1.SessionService.FinalizeSession:output_type -> dotfilesd.v1.FinalizeSessionResponse
	6,  // 13: dotfilesd.v1.SessionService.GetSession:output_type -> dotfilesd.v1.GetSessionResponse
	10, // 14: dotfilesd.v1.SessionService.ListSessions:output_type -> dotfilesd.v1.ListSessionsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_dotfilesd_v1_dotfilesdv1_session_proto_init() }
func file_proto_dotfilesd_v1_dotfilesdv1_session_proto_init() {
	if File_proto_dotfilesd_v1_dotfilesdv1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDesc), len(file_proto_dotfilesd_v1_dotfilesdv1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dotfilesd_v1_dotfilesdv1_session_proto_goTypes,
		DependencyIndexes: file_proto_dotfilesd_v1_dotfilesdv1_session_proto_depIdxs,
		MessageInfos:      file_proto_dotfilesd_v1_dotfilesdv1_session_proto_msgTypes,
	}.Build()
	File_proto_dotfilesd_v1_dotfilesdv1_session_proto = out.File
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_goTypes = nil
	file_proto_dotfilesd_v1_dotfilesdv1_session_proto_depIdxs = nil
}
