// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/games/games.proto

package gamesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	games "plugins/games/proto/games"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SolitaireServiceName is the fully-qualified name of the SolitaireService service.
	SolitaireServiceName = "games.SolitaireService"
	// MinesweeperServiceName is the fully-qualified name of the MinesweeperService service.
	MinesweeperServiceName = "games.MinesweeperService"
	// Game2048ServiceName is the fully-qualified name of the Game2048Service service.
	Game2048ServiceName = "games.Game2048Service"
	// BattleshipServiceName is the fully-qualified name of the BattleshipService service.
	BattleshipServiceName = "games.BattleshipService"
	// ChessServiceName is the fully-qualified name of the ChessService service.
	ChessServiceName = "games.ChessService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SolitaireServicePlayProcedure is the fully-qualified name of the SolitaireService's Play RPC.
	SolitaireServicePlayProcedure = "/games.SolitaireService/Play"
	// MinesweeperServicePlayProcedure is the fully-qualified name of the MinesweeperService's Play RPC.
	MinesweeperServicePlayProcedure = "/games.MinesweeperService/Play"
	// Game2048ServicePlayProcedure is the fully-qualified name of the Game2048Service's Play RPC.
	Game2048ServicePlayProcedure = "/games.Game2048Service/Play"
	// BattleshipServicePlayProcedure is the fully-qualified name of the BattleshipService's Play RPC.
	BattleshipServicePlayProcedure = "/games.BattleshipService/Play"
	// ChessServicePlayProcedure is the fully-qualified name of the ChessService's Play RPC.
	ChessServicePlayProcedure = "/games.ChessService/Play"
)

// SolitaireServiceClient is a client for the games.SolitaireService service.
type SolitaireServiceClient interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewSolitaireServiceClient constructs a client for the games.SolitaireService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSolitaireServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SolitaireServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	solitaireServiceMethods := games.File_proto_games_games_proto.Services().ByName("SolitaireService").Methods()
	return &solitaireServiceClient{
		play: connect.NewClient[games.PlayRequest, games.PlayResponse](
			httpClient,
			baseURL+SolitaireServicePlayProcedure,
			connect.WithSchema(solitaireServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// solitaireServiceClient implements SolitaireServiceClient.
type solitaireServiceClient struct {
	play *connect.Client[games.PlayRequest, games.PlayResponse]
}

// Play calls games.SolitaireService.Play.
func (c *solitaireServiceClient) Play(ctx context.Context, req *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return c.play.CallUnary(ctx, req)
}

// SolitaireServiceHandler is an implementation of the games.SolitaireService service.
type SolitaireServiceHandler interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewSolitaireServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSolitaireServiceHandler(svc SolitaireServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	solitaireServiceMethods := games.File_proto_games_games_proto.Services().ByName("SolitaireService").Methods()
	solitaireServicePlayHandler := connect.NewUnaryHandler(
		SolitaireServicePlayProcedure,
		svc.Play,
		connect.WithSchema(solitaireServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/games.SolitaireService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SolitaireServicePlayProcedure:
			solitaireServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSolitaireServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSolitaireServiceHandler struct{}

func (UnimplementedSolitaireServiceHandler) Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("games.SolitaireService.Play is not implemented"))
}

// MinesweeperServiceClient is a client for the games.MinesweeperService service.
type MinesweeperServiceClient interface {
	Play(context.Context, *connect.Request[games.MinesweeperRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewMinesweeperServiceClient constructs a client for the games.MinesweeperService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMinesweeperServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MinesweeperServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	minesweeperServiceMethods := games.File_proto_games_games_proto.Services().ByName("MinesweeperService").Methods()
	return &minesweeperServiceClient{
		play: connect.NewClient[games.MinesweeperRequest, games.PlayResponse](
			httpClient,
			baseURL+MinesweeperServicePlayProcedure,
			connect.WithSchema(minesweeperServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// minesweeperServiceClient implements MinesweeperServiceClient.
type minesweeperServiceClient struct {
	play *connect.Client[games.MinesweeperRequest, games.PlayResponse]
}

// Play calls games.MinesweeperService.Play.
func (c *minesweeperServiceClient) Play(ctx context.Context, req *connect.Request[games.MinesweeperRequest]) (*connect.Response[games.PlayResponse], error) {
	return c.play.CallUnary(ctx, req)
}

// MinesweeperServiceHandler is an implementation of the games.MinesweeperService service.
type MinesweeperServiceHandler interface {
	Play(context.Context, *connect.Request[games.MinesweeperRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewMinesweeperServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMinesweeperServiceHandler(svc MinesweeperServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	minesweeperServiceMethods := games.File_proto_games_games_proto.Services().ByName("MinesweeperService").Methods()
	minesweeperServicePlayHandler := connect.NewUnaryHandler(
		MinesweeperServicePlayProcedure,
		svc.Play,
		connect.WithSchema(minesweeperServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/games.MinesweeperService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MinesweeperServicePlayProcedure:
			minesweeperServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMinesweeperServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMinesweeperServiceHandler struct{}

func (UnimplementedMinesweeperServiceHandler) Play(context.Context, *connect.Request[games.MinesweeperRequest]) (*connect.Response[games.PlayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("games.MinesweeperService.Play is not implemented"))
}

// Game2048ServiceClient is a client for the games.Game2048Service service.
type Game2048ServiceClient interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewGame2048ServiceClient constructs a client for the games.Game2048Service service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGame2048ServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) Game2048ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	game2048ServiceMethods := games.File_proto_games_games_proto.Services().ByName("Game2048Service").Methods()
	return &game2048ServiceClient{
		play: connect.NewClient[games.PlayRequest, games.PlayResponse](
			httpClient,
			baseURL+Game2048ServicePlayProcedure,
			connect.WithSchema(game2048ServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// game2048ServiceClient implements Game2048ServiceClient.
type game2048ServiceClient struct {
	play *connect.Client[games.PlayRequest, games.PlayResponse]
}

// Play calls games.Game2048Service.Play.
func (c *game2048ServiceClient) Play(ctx context.Context, req *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return c.play.CallUnary(ctx, req)
}

// Game2048ServiceHandler is an implementation of the games.Game2048Service service.
type Game2048ServiceHandler interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewGame2048ServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGame2048ServiceHandler(svc Game2048ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	game2048ServiceMethods := games.File_proto_games_games_proto.Services().ByName("Game2048Service").Methods()
	game2048ServicePlayHandler := connect.NewUnaryHandler(
		Game2048ServicePlayProcedure,
		svc.Play,
		connect.WithSchema(game2048ServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/games.Game2048Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case Game2048ServicePlayProcedure:
			game2048ServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGame2048ServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGame2048ServiceHandler struct{}

func (UnimplementedGame2048ServiceHandler) Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("games.Game2048Service.Play is not implemented"))
}

// BattleshipServiceClient is a client for the games.BattleshipService service.
type BattleshipServiceClient interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewBattleshipServiceClient constructs a client for the games.BattleshipService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBattleshipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BattleshipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	battleshipServiceMethods := games.File_proto_games_games_proto.Services().ByName("BattleshipService").Methods()
	return &battleshipServiceClient{
		play: connect.NewClient[games.PlayRequest, games.PlayResponse](
			httpClient,
			baseURL+BattleshipServicePlayProcedure,
			connect.WithSchema(battleshipServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// battleshipServiceClient implements BattleshipServiceClient.
type battleshipServiceClient struct {
	play *connect.Client[games.PlayRequest, games.PlayResponse]
}

// Play calls games.BattleshipService.Play.
func (c *battleshipServiceClient) Play(ctx context.Context, req *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return c.play.CallUnary(ctx, req)
}

// BattleshipServiceHandler is an implementation of the games.BattleshipService service.
type BattleshipServiceHandler interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewBattleshipServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBattleshipServiceHandler(svc BattleshipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	battleshipServiceMethods := games.File_proto_games_games_proto.Services().ByName("BattleshipService").Methods()
	battleshipServicePlayHandler := connect.NewUnaryHandler(
		BattleshipServicePlayProcedure,
		svc.Play,
		connect.WithSchema(battleshipServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/games.BattleshipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BattleshipServicePlayProcedure:
			battleshipServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBattleshipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBattleshipServiceHandler struct{}

func (UnimplementedBattleshipServiceHandler) Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("games.BattleshipService.Play is not implemented"))
}

// ChessServiceClient is a client for the games.ChessService service.
type ChessServiceClient interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewChessServiceClient constructs a client for the games.ChessService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chessServiceMethods := games.File_proto_games_games_proto.Services().ByName("ChessService").Methods()
	return &chessServiceClient{
		play: connect.NewClient[games.PlayRequest, games.PlayResponse](
			httpClient,
			baseURL+ChessServicePlayProcedure,
			connect.WithSchema(chessServiceMethods.ByName("Play")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chessServiceClient implements ChessServiceClient.
type chessServiceClient struct {
	play *connect.Client[games.PlayRequest, games.PlayResponse]
}

// Play calls games.ChessService.Play.
func (c *chessServiceClient) Play(ctx context.Context, req *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return c.play.CallUnary(ctx, req)
}

// ChessServiceHandler is an implementation of the games.ChessService service.
type ChessServiceHandler interface {
	Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error)
}

// NewChessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChessServiceHandler(svc ChessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chessServiceMethods := games.File_proto_games_games_proto.Services().ByName("ChessService").Methods()
	chessServicePlayHandler := connect.NewUnaryHandler(
		ChessServicePlayProcedure,
		svc.Play,
		connect.WithSchema(chessServiceMethods.ByName("Play")),
		connect.WithHandlerOptions(opts...),
	)
	return "/games.ChessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChessServicePlayProcedure:
			chessServicePlayHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChessServiceHandler struct{}

func (UnimplementedChessServiceHandler) Play(context.Context, *connect.Request[games.PlayRequest]) (*connect.Response[games.PlayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("games.ChessService.Play is not implemented"))
}
