// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/callback.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientCallbackName is the fully-qualified name of the ClientCallback service.
	ClientCallbackName = "dotfilesd.v1.ClientCallback"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientCallbackFeedbackProcedure is the fully-qualified name of the ClientCallback's Feedback RPC.
	ClientCallbackFeedbackProcedure = "/dotfilesd.v1.ClientCallback/Feedback"
)

// ClientCallbackClient is a client for the dotfilesd.v1.ClientCallback service.
type ClientCallbackClient interface {
	// Feedback is called by the daemon when it needs input from the client
	// (e.g. clarification, confirmation, or additional data).
	Feedback(context.Context, *connect.Request[dotfilesdv1.FeedbackRequest]) (*connect.Response[dotfilesdv1.FeedbackResponse], error)
}

// NewClientCallbackClient constructs a client for the dotfilesd.v1.ClientCallback service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientCallbackClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientCallbackClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clientCallbackMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_callback_proto.Services().ByName("ClientCallback").Methods()
	return &clientCallbackClient{
		feedback: connect.NewClient[dotfilesdv1.FeedbackRequest, dotfilesdv1.FeedbackResponse](
			httpClient,
			baseURL+ClientCallbackFeedbackProcedure,
			connect.WithSchema(clientCallbackMethods.ByName("Feedback")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientCallbackClient implements ClientCallbackClient.
type clientCallbackClient struct {
	feedback *connect.Client[dotfilesdv1.FeedbackRequest, dotfilesdv1.FeedbackResponse]
}

// Feedback calls dotfilesd.v1.ClientCallback.Feedback.
func (c *clientCallbackClient) Feedback(ctx context.Context, req *connect.Request[dotfilesdv1.FeedbackRequest]) (*connect.Response[dotfilesdv1.FeedbackResponse], error) {
	return c.feedback.CallUnary(ctx, req)
}

// ClientCallbackHandler is an implementation of the dotfilesd.v1.ClientCallback service.
type ClientCallbackHandler interface {
	// Feedback is called by the daemon when it needs input from the client
	// (e.g. clarification, confirmation, or additional data).
	Feedback(context.Context, *connect.Request[dotfilesdv1.FeedbackRequest]) (*connect.Response[dotfilesdv1.FeedbackResponse], error)
}

// NewClientCallbackHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientCallbackHandler(svc ClientCallbackHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientCallbackMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_callback_proto.Services().ByName("ClientCallback").Methods()
	clientCallbackFeedbackHandler := connect.NewUnaryHandler(
		ClientCallbackFeedbackProcedure,
		svc.Feedback,
		connect.WithSchema(clientCallbackMethods.ByName("Feedback")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ClientCallback/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientCallbackFeedbackProcedure:
			clientCallbackFeedbackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientCallbackHandler returns CodeUnimplemented from all methods.
type UnimplementedClientCallbackHandler struct{}

func (UnimplementedClientCallbackHandler) Feedback(context.Context, *connect.Request[dotfilesdv1.FeedbackRequest]) (*connect.Response[dotfilesdv1.FeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ClientCallback.Feedback is not implemented"))
}
