// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/config.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "dotfilesd.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceReloadProcedure is the fully-qualified name of the ConfigService's Reload RPC.
	ConfigServiceReloadProcedure = "/dotfilesd.v1.ConfigService/Reload"
	// ConfigServiceReconfigureProcedure is the fully-qualified name of the ConfigService's Reconfigure
	// RPC.
	ConfigServiceReconfigureProcedure = "/dotfilesd.v1.ConfigService/Reconfigure"
	// ConfigServiceRestartProcedure is the fully-qualified name of the ConfigService's Restart RPC.
	ConfigServiceRestartProcedure = "/dotfilesd.v1.ConfigService/Restart"
)

// ConfigServiceClient is a client for the dotfilesd.v1.ConfigService service.
type ConfigServiceClient interface {
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error)
	Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error)
}

// NewConfigServiceClient constructs a client for the dotfilesd.v1.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		reload: connect.NewClient[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse](
			httpClient,
			baseURL+ConfigServiceReloadProcedure,
			connect.WithSchema(configServiceMethods.ByName("Reload")),
			connect.WithClientOptions(opts...),
		),
		reconfigure: connect.NewClient[dotfilesdv1.ReconfigureRequest, dotfilesdv1.ReconfigureResponse](
			httpClient,
			baseURL+ConfigServiceReconfigureProcedure,
			connect.WithSchema(configServiceMethods.ByName("Reconfigure")),
			connect.WithClientOptions(opts...),
		),
		restart: connect.NewClient[dotfilesdv1.RestartRequest, dotfilesdv1.RestartResponse](
			httpClient,
			baseURL+ConfigServiceRestartProcedure,
			connect.WithSchema(configServiceMethods.ByName("Restart")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	reload      *connect.Client[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse]
	reconfigure *connect.Client[dotfilesdv1.ReconfigureRequest, dotfilesdv1.ReconfigureResponse]
	restart     *connect.Client[dotfilesdv1.RestartRequest, dotfilesdv1.RestartResponse]
}

// Reload calls dotfilesd.v1.ConfigService.Reload.
func (c *configServiceClient) Reload(ctx context.Context, req *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return c.reload.CallUnary(ctx, req)
}

// Reconfigure calls dotfilesd.v1.ConfigService.Reconfigure.
func (c *configServiceClient) Reconfigure(ctx context.Context, req *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error) {
	return c.reconfigure.CallUnary(ctx, req)
}

// Restart calls dotfilesd.v1.ConfigService.Restart.
func (c *configServiceClient) Restart(ctx context.Context, req *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error) {
	return c.restart.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the dotfilesd.v1.ConfigService service.
type ConfigServiceHandler interface {
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error)
	Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceReloadHandler := connect.NewUnaryHandler(
		ConfigServiceReloadProcedure,
		svc.Reload,
		connect.WithSchema(configServiceMethods.ByName("Reload")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceReconfigureHandler := connect.NewUnaryHandler(
		ConfigServiceReconfigureProcedure,
		svc.Reconfigure,
		connect.WithSchema(configServiceMethods.ByName("Reconfigure")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceRestartHandler := connect.NewUnaryHandler(
		ConfigServiceRestartProcedure,
		svc.Restart,
		connect.WithSchema(configServiceMethods.ByName("Restart")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceReloadProcedure:
			configServiceReloadHandler.ServeHTTP(w, r)
		case ConfigServiceReconfigureProcedure:
			configServiceReconfigureHandler.ServeHTTP(w, r)
		case ConfigServiceRestartProcedure:
			configServiceRestartHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Reload is not implemented"))
}

func (UnimplementedConfigServiceHandler) Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Reconfigure is not implemented"))
}

func (UnimplementedConfigServiceHandler) Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Restart is not implemented"))
}
