// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/context.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExecutionContextName is the fully-qualified name of the ExecutionContext service.
	ExecutionContextName = "dotfilesd.v1.ExecutionContext"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExecutionContextExecProcedure is the fully-qualified name of the ExecutionContext's Exec RPC.
	ExecutionContextExecProcedure = "/dotfilesd.v1.ExecutionContext/Exec"
	// ExecutionContextSudoExecProcedure is the fully-qualified name of the ExecutionContext's SudoExec
	// RPC.
	ExecutionContextSudoExecProcedure = "/dotfilesd.v1.ExecutionContext/SudoExec"
	// ExecutionContextRequestInputProcedure is the fully-qualified name of the ExecutionContext's
	// RequestInput RPC.
	ExecutionContextRequestInputProcedure = "/dotfilesd.v1.ExecutionContext/RequestInput"
	// ExecutionContextRequestConfirmProcedure is the fully-qualified name of the ExecutionContext's
	// RequestConfirm RPC.
	ExecutionContextRequestConfirmProcedure = "/dotfilesd.v1.ExecutionContext/RequestConfirm"
	// ExecutionContextRequestChooseProcedure is the fully-qualified name of the ExecutionContext's
	// RequestChoose RPC.
	ExecutionContextRequestChooseProcedure = "/dotfilesd.v1.ExecutionContext/RequestChoose"
	// ExecutionContextLogProcedure is the fully-qualified name of the ExecutionContext's Log RPC.
	ExecutionContextLogProcedure = "/dotfilesd.v1.ExecutionContext/Log"
	// ExecutionContextCallPluginProcedure is the fully-qualified name of the ExecutionContext's
	// CallPlugin RPC.
	ExecutionContextCallPluginProcedure = "/dotfilesd.v1.ExecutionContext/CallPlugin"
	// ExecutionContextRunScriptProcedure is the fully-qualified name of the ExecutionContext's
	// RunScript RPC.
	ExecutionContextRunScriptProcedure = "/dotfilesd.v1.ExecutionContext/RunScript"
)

// ExecutionContextClient is a client for the dotfilesd.v1.ExecutionContext service.
type ExecutionContextClient interface {
	// Exec runs a shell command without privilege escalation.
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// SudoExec runs a shell command with sudo. The daemon handles password
	// elicitation internally via its existing sudo flow.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.ContextSudoExecRequest]) (*connect.Response[dotfilesdv1.ContextSudoExecResponse], error)
	// RequestInput prompts the user for text input.
	RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error)
	// RequestConfirm prompts the user for a yes/no confirmation.
	RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error)
	// RequestChoose prompts the user to pick from a list of options.
	RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error)
	// Log submits a log entry from a plugin. The daemon routes it through
	// its logging system with the plugin name as the logger module.
	Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error)
	// CallPlugin invokes a tool on another loaded plugin. Plugins can use
	// this to delegate work to other plugins instead of shelling out.
	CallPlugin(context.Context, *connect.Request[dotfilesdv1.CallPluginRequest]) (*connect.Response[dotfilesdv1.CallPluginResponse], error)
	// RunScript runs a registered script or inline script content. Plugins
	// can use this to invoke scripted workflows (which may include feedback
	// steps like confirm/input/choose) without shelling out to dotfilesctl.
	RunScript(context.Context, *connect.Request[dotfilesdv1.RunScriptViaContextRequest]) (*connect.Response[dotfilesdv1.RunScriptViaContextResponse], error)
}

// NewExecutionContextClient constructs a client for the dotfilesd.v1.ExecutionContext service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecutionContextClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecutionContextClient {
	baseURL = strings.TrimRight(baseURL, "/")
	executionContextMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_context_proto.Services().ByName("ExecutionContext").Methods()
	return &executionContextClient{
		exec: connect.NewClient[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse](
			httpClient,
			baseURL+ExecutionContextExecProcedure,
			connect.WithSchema(executionContextMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		sudoExec: connect.NewClient[dotfilesdv1.ContextSudoExecRequest, dotfilesdv1.ContextSudoExecResponse](
			httpClient,
			baseURL+ExecutionContextSudoExecProcedure,
			connect.WithSchema(executionContextMethods.ByName("SudoExec")),
			connect.WithClientOptions(opts...),
		),
		requestInput: connect.NewClient[dotfilesdv1.InputRequest, dotfilesdv1.InputResponse](
			httpClient,
			baseURL+ExecutionContextRequestInputProcedure,
			connect.WithSchema(executionContextMethods.ByName("RequestInput")),
			connect.WithClientOptions(opts...),
		),
		requestConfirm: connect.NewClient[dotfilesdv1.ConfirmRequest, dotfilesdv1.ConfirmResponse](
			httpClient,
			baseURL+ExecutionContextRequestConfirmProcedure,
			connect.WithSchema(executionContextMethods.ByName("RequestConfirm")),
			connect.WithClientOptions(opts...),
		),
		requestChoose: connect.NewClient[dotfilesdv1.ChooseRequest, dotfilesdv1.ChooseResponse](
			httpClient,
			baseURL+ExecutionContextRequestChooseProcedure,
			connect.WithSchema(executionContextMethods.ByName("RequestChoose")),
			connect.WithClientOptions(opts...),
		),
		log: connect.NewClient[dotfilesdv1.LogRequest, dotfilesdv1.LogResponse](
			httpClient,
			baseURL+ExecutionContextLogProcedure,
			connect.WithSchema(executionContextMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
		callPlugin: connect.NewClient[dotfilesdv1.CallPluginRequest, dotfilesdv1.CallPluginResponse](
			httpClient,
			baseURL+ExecutionContextCallPluginProcedure,
			connect.WithSchema(executionContextMethods.ByName("CallPlugin")),
			connect.WithClientOptions(opts...),
		),
		runScript: connect.NewClient[dotfilesdv1.RunScriptViaContextRequest, dotfilesdv1.RunScriptViaContextResponse](
			httpClient,
			baseURL+ExecutionContextRunScriptProcedure,
			connect.WithSchema(executionContextMethods.ByName("RunScript")),
			connect.WithClientOptions(opts...),
		),
	}
}

// executionContextClient implements ExecutionContextClient.
type executionContextClient struct {
	exec           *connect.Client[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse]
	sudoExec       *connect.Client[dotfilesdv1.ContextSudoExecRequest, dotfilesdv1.ContextSudoExecResponse]
	requestInput   *connect.Client[dotfilesdv1.InputRequest, dotfilesdv1.InputResponse]
	requestConfirm *connect.Client[dotfilesdv1.ConfirmRequest, dotfilesdv1.ConfirmResponse]
	requestChoose  *connect.Client[dotfilesdv1.ChooseRequest, dotfilesdv1.ChooseResponse]
	log            *connect.Client[dotfilesdv1.LogRequest, dotfilesdv1.LogResponse]
	callPlugin     *connect.Client[dotfilesdv1.CallPluginRequest, dotfilesdv1.CallPluginResponse]
	runScript      *connect.Client[dotfilesdv1.RunScriptViaContextRequest, dotfilesdv1.RunScriptViaContextResponse]
}

// Exec calls dotfilesd.v1.ExecutionContext.Exec.
func (c *executionContextClient) Exec(ctx context.Context, req *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// SudoExec calls dotfilesd.v1.ExecutionContext.SudoExec.
func (c *executionContextClient) SudoExec(ctx context.Context, req *connect.Request[dotfilesdv1.ContextSudoExecRequest]) (*connect.Response[dotfilesdv1.ContextSudoExecResponse], error) {
	return c.sudoExec.CallUnary(ctx, req)
}

// RequestInput calls dotfilesd.v1.ExecutionContext.RequestInput.
func (c *executionContextClient) RequestInput(ctx context.Context, req *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error) {
	return c.requestInput.CallUnary(ctx, req)
}

// RequestConfirm calls dotfilesd.v1.ExecutionContext.RequestConfirm.
func (c *executionContextClient) RequestConfirm(ctx context.Context, req *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error) {
	return c.requestConfirm.CallUnary(ctx, req)
}

// RequestChoose calls dotfilesd.v1.ExecutionContext.RequestChoose.
func (c *executionContextClient) RequestChoose(ctx context.Context, req *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error) {
	return c.requestChoose.CallUnary(ctx, req)
}

// Log calls dotfilesd.v1.ExecutionContext.Log.
func (c *executionContextClient) Log(ctx context.Context, req *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error) {
	return c.log.CallUnary(ctx, req)
}

// CallPlugin calls dotfilesd.v1.ExecutionContext.CallPlugin.
func (c *executionContextClient) CallPlugin(ctx context.Context, req *connect.Request[dotfilesdv1.CallPluginRequest]) (*connect.Response[dotfilesdv1.CallPluginResponse], error) {
	return c.callPlugin.CallUnary(ctx, req)
}

// RunScript calls dotfilesd.v1.ExecutionContext.RunScript.
func (c *executionContextClient) RunScript(ctx context.Context, req *connect.Request[dotfilesdv1.RunScriptViaContextRequest]) (*connect.Response[dotfilesdv1.RunScriptViaContextResponse], error) {
	return c.runScript.CallUnary(ctx, req)
}

// ExecutionContextHandler is an implementation of the dotfilesd.v1.ExecutionContext service.
type ExecutionContextHandler interface {
	// Exec runs a shell command without privilege escalation.
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// SudoExec runs a shell command with sudo. The daemon handles password
	// elicitation internally via its existing sudo flow.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.ContextSudoExecRequest]) (*connect.Response[dotfilesdv1.ContextSudoExecResponse], error)
	// RequestInput prompts the user for text input.
	RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error)
	// RequestConfirm prompts the user for a yes/no confirmation.
	RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error)
	// RequestChoose prompts the user to pick from a list of options.
	RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error)
	// Log submits a log entry from a plugin. The daemon routes it through
	// its logging system with the plugin name as the logger module.
	Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error)
	// CallPlugin invokes a tool on another loaded plugin. Plugins can use
	// this to delegate work to other plugins instead of shelling out.
	CallPlugin(context.Context, *connect.Request[dotfilesdv1.CallPluginRequest]) (*connect.Response[dotfilesdv1.CallPluginResponse], error)
	// RunScript runs a registered script or inline script content. Plugins
	// can use this to invoke scripted workflows (which may include feedback
	// steps like confirm/input/choose) without shelling out to dotfilesctl.
	RunScript(context.Context, *connect.Request[dotfilesdv1.RunScriptViaContextRequest]) (*connect.Response[dotfilesdv1.RunScriptViaContextResponse], error)
}

// NewExecutionContextHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecutionContextHandler(svc ExecutionContextHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	executionContextMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_context_proto.Services().ByName("ExecutionContext").Methods()
	executionContextExecHandler := connect.NewUnaryHandler(
		ExecutionContextExecProcedure,
		svc.Exec,
		connect.WithSchema(executionContextMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextSudoExecHandler := connect.NewUnaryHandler(
		ExecutionContextSudoExecProcedure,
		svc.SudoExec,
		connect.WithSchema(executionContextMethods.ByName("SudoExec")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextRequestInputHandler := connect.NewUnaryHandler(
		ExecutionContextRequestInputProcedure,
		svc.RequestInput,
		connect.WithSchema(executionContextMethods.ByName("RequestInput")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextRequestConfirmHandler := connect.NewUnaryHandler(
		ExecutionContextRequestConfirmProcedure,
		svc.RequestConfirm,
		connect.WithSchema(executionContextMethods.ByName("RequestConfirm")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextRequestChooseHandler := connect.NewUnaryHandler(
		ExecutionContextRequestChooseProcedure,
		svc.RequestChoose,
		connect.WithSchema(executionContextMethods.ByName("RequestChoose")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextLogHandler := connect.NewUnaryHandler(
		ExecutionContextLogProcedure,
		svc.Log,
		connect.WithSchema(executionContextMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextCallPluginHandler := connect.NewUnaryHandler(
		ExecutionContextCallPluginProcedure,
		svc.CallPlugin,
		connect.WithSchema(executionContextMethods.ByName("CallPlugin")),
		connect.WithHandlerOptions(opts...),
	)
	executionContextRunScriptHandler := connect.NewUnaryHandler(
		ExecutionContextRunScriptProcedure,
		svc.RunScript,
		connect.WithSchema(executionContextMethods.ByName("RunScript")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ExecutionContext/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecutionContextExecProcedure:
			executionContextExecHandler.ServeHTTP(w, r)
		case ExecutionContextSudoExecProcedure:
			executionContextSudoExecHandler.ServeHTTP(w, r)
		case ExecutionContextRequestInputProcedure:
			executionContextRequestInputHandler.ServeHTTP(w, r)
		case ExecutionContextRequestConfirmProcedure:
			executionContextRequestConfirmHandler.ServeHTTP(w, r)
		case ExecutionContextRequestChooseProcedure:
			executionContextRequestChooseHandler.ServeHTTP(w, r)
		case ExecutionContextLogProcedure:
			executionContextLogHandler.ServeHTTP(w, r)
		case ExecutionContextCallPluginProcedure:
			executionContextCallPluginHandler.ServeHTTP(w, r)
		case ExecutionContextRunScriptProcedure:
			executionContextRunScriptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecutionContextHandler returns CodeUnimplemented from all methods.
type UnimplementedExecutionContextHandler struct{}

func (UnimplementedExecutionContextHandler) Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.Exec is not implemented"))
}

func (UnimplementedExecutionContextHandler) SudoExec(context.Context, *connect.Request[dotfilesdv1.ContextSudoExecRequest]) (*connect.Response[dotfilesdv1.ContextSudoExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.SudoExec is not implemented"))
}

func (UnimplementedExecutionContextHandler) RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.RequestInput is not implemented"))
}

func (UnimplementedExecutionContextHandler) RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.RequestConfirm is not implemented"))
}

func (UnimplementedExecutionContextHandler) RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.RequestChoose is not implemented"))
}

func (UnimplementedExecutionContextHandler) Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.Log is not implemented"))
}

func (UnimplementedExecutionContextHandler) CallPlugin(context.Context, *connect.Request[dotfilesdv1.CallPluginRequest]) (*connect.Response[dotfilesdv1.CallPluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.CallPlugin is not implemented"))
}

func (UnimplementedExecutionContextHandler) RunScript(context.Context, *connect.Request[dotfilesdv1.RunScriptViaContextRequest]) (*connect.Response[dotfilesdv1.RunScriptViaContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecutionContext.RunScript is not implemented"))
}
