// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/dotfiles.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DotfilesServiceName is the fully-qualified name of the DotfilesService service.
	DotfilesServiceName = "dotfilesd.v1.DotfilesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DotfilesServiceStatusProcedure is the fully-qualified name of the DotfilesService's Status RPC.
	DotfilesServiceStatusProcedure = "/dotfilesd.v1.DotfilesService/Status"
	// DotfilesServiceGitProcedure is the fully-qualified name of the DotfilesService's Git RPC.
	DotfilesServiceGitProcedure = "/dotfilesd.v1.DotfilesService/Git"
)

// DotfilesServiceClient is a client for the dotfilesd.v1.DotfilesService service.
type DotfilesServiceClient interface {
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
}

// NewDotfilesServiceClient constructs a client for the dotfilesd.v1.DotfilesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDotfilesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DotfilesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_dotfiles_proto.Services().ByName("DotfilesService").Methods()
	return &dotfilesServiceClient{
		status: connect.NewClient[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse](
			httpClient,
			baseURL+DotfilesServiceStatusProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		git: connect.NewClient[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse](
			httpClient,
			baseURL+DotfilesServiceGitProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dotfilesServiceClient implements DotfilesServiceClient.
type dotfilesServiceClient struct {
	status *connect.Client[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse]
	git    *connect.Client[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse]
}

// Status calls dotfilesd.v1.DotfilesService.Status.
func (c *dotfilesServiceClient) Status(ctx context.Context, req *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Git calls dotfilesd.v1.DotfilesService.Git.
func (c *dotfilesServiceClient) Git(ctx context.Context, req *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return c.git.CallUnary(ctx, req)
}

// DotfilesServiceHandler is an implementation of the dotfilesd.v1.DotfilesService service.
type DotfilesServiceHandler interface {
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
}

// NewDotfilesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDotfilesServiceHandler(svc DotfilesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_dotfiles_proto.Services().ByName("DotfilesService").Methods()
	dotfilesServiceStatusHandler := connect.NewUnaryHandler(
		DotfilesServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceGitHandler := connect.NewUnaryHandler(
		DotfilesServiceGitProcedure,
		svc.Git,
		connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.DotfilesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DotfilesServiceStatusProcedure:
			dotfilesServiceStatusHandler.ServeHTTP(w, r)
		case DotfilesServiceGitProcedure:
			dotfilesServiceGitHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDotfilesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDotfilesServiceHandler struct{}

func (UnimplementedDotfilesServiceHandler) Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Status is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Git is not implemented"))
}
