// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/exec.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExecServiceName is the fully-qualified name of the ExecService service.
	ExecServiceName = "dotfilesd.v1.ExecService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExecServiceExecProcedure is the fully-qualified name of the ExecService's Exec RPC.
	ExecServiceExecProcedure = "/dotfilesd.v1.ExecService/Exec"
	// ExecServiceSudoExecProcedure is the fully-qualified name of the ExecService's SudoExec RPC.
	ExecServiceSudoExecProcedure = "/dotfilesd.v1.ExecService/SudoExec"
)

// ExecServiceClient is a client for the dotfilesd.v1.ExecService service.
type ExecServiceClient interface {
	// Simple unary exec (no sudo).
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Challenge-response sudo. The first call omits password; if the daemon
	// needs auth it returns AuthChallenge. The client retries with the password.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error)
}

// NewExecServiceClient constructs a client for the dotfilesd.v1.ExecService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	execServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_exec_proto.Services().ByName("ExecService").Methods()
	return &execServiceClient{
		exec: connect.NewClient[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse](
			httpClient,
			baseURL+ExecServiceExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		sudoExec: connect.NewClient[dotfilesdv1.SudoExecRequest, dotfilesdv1.SudoExecResponse](
			httpClient,
			baseURL+ExecServiceSudoExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("SudoExec")),
			connect.WithClientOptions(opts...),
		),
	}
}

// execServiceClient implements ExecServiceClient.
type execServiceClient struct {
	exec     *connect.Client[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse]
	sudoExec *connect.Client[dotfilesdv1.SudoExecRequest, dotfilesdv1.SudoExecResponse]
}

// Exec calls dotfilesd.v1.ExecService.Exec.
func (c *execServiceClient) Exec(ctx context.Context, req *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// SudoExec calls dotfilesd.v1.ExecService.SudoExec.
func (c *execServiceClient) SudoExec(ctx context.Context, req *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error) {
	return c.sudoExec.CallUnary(ctx, req)
}

// ExecServiceHandler is an implementation of the dotfilesd.v1.ExecService service.
type ExecServiceHandler interface {
	// Simple unary exec (no sudo).
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Challenge-response sudo. The first call omits password; if the daemon
	// needs auth it returns AuthChallenge. The client retries with the password.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error)
}

// NewExecServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecServiceHandler(svc ExecServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	execServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_exec_proto.Services().ByName("ExecService").Methods()
	execServiceExecHandler := connect.NewUnaryHandler(
		ExecServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(execServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	execServiceSudoExecHandler := connect.NewUnaryHandler(
		ExecServiceSudoExecProcedure,
		svc.SudoExec,
		connect.WithSchema(execServiceMethods.ByName("SudoExec")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ExecService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecServiceExecProcedure:
			execServiceExecHandler.ServeHTTP(w, r)
		case ExecServiceSudoExecProcedure:
			execServiceSudoExecHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecServiceHandler struct{}

func (UnimplementedExecServiceHandler) Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecService.Exec is not implemented"))
}

func (UnimplementedExecServiceHandler) SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecService.SudoExec is not implemented"))
}
