// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/extension.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExtensionServiceName is the fully-qualified name of the ExtensionService service.
	ExtensionServiceName = "dotfilesd.v1.ExtensionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExtensionServiceGetDescriptorProcedure is the fully-qualified name of the ExtensionService's
	// GetDescriptor RPC.
	ExtensionServiceGetDescriptorProcedure = "/dotfilesd.v1.ExtensionService/GetDescriptor"
	// ExtensionServiceCallToolProcedure is the fully-qualified name of the ExtensionService's CallTool
	// RPC.
	ExtensionServiceCallToolProcedure = "/dotfilesd.v1.ExtensionService/CallTool"
)

// ExtensionServiceClient is a client for the dotfilesd.v1.ExtensionService service.
type ExtensionServiceClient interface {
	// GetDescriptor returns the plugin's capabilities (tools, metadata, CLI
	// hints). Called once at plugin load time; results are cached in the
	// daemon's plugin registry.
	GetDescriptor(context.Context, *connect.Request[dotfilesdv1.GetDescriptorRequest]) (*connect.Response[dotfilesdv1.GetDescriptorResponse], error)
	// CallTool invokes a named tool on the plugin with the given arguments.
	// The daemon proxies MCP tools/call and CLI commands to this RPC.
	CallTool(context.Context, *connect.Request[dotfilesdv1.CallToolRequest]) (*connect.Response[dotfilesdv1.CallToolResponse], error)
}

// NewExtensionServiceClient constructs a client for the dotfilesd.v1.ExtensionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExtensionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExtensionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	extensionServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_extension_proto.Services().ByName("ExtensionService").Methods()
	return &extensionServiceClient{
		getDescriptor: connect.NewClient[dotfilesdv1.GetDescriptorRequest, dotfilesdv1.GetDescriptorResponse](
			httpClient,
			baseURL+ExtensionServiceGetDescriptorProcedure,
			connect.WithSchema(extensionServiceMethods.ByName("GetDescriptor")),
			connect.WithClientOptions(opts...),
		),
		callTool: connect.NewClient[dotfilesdv1.CallToolRequest, dotfilesdv1.CallToolResponse](
			httpClient,
			baseURL+ExtensionServiceCallToolProcedure,
			connect.WithSchema(extensionServiceMethods.ByName("CallTool")),
			connect.WithClientOptions(opts...),
		),
	}
}

// extensionServiceClient implements ExtensionServiceClient.
type extensionServiceClient struct {
	getDescriptor *connect.Client[dotfilesdv1.GetDescriptorRequest, dotfilesdv1.GetDescriptorResponse]
	callTool      *connect.Client[dotfilesdv1.CallToolRequest, dotfilesdv1.CallToolResponse]
}

// GetDescriptor calls dotfilesd.v1.ExtensionService.GetDescriptor.
func (c *extensionServiceClient) GetDescriptor(ctx context.Context, req *connect.Request[dotfilesdv1.GetDescriptorRequest]) (*connect.Response[dotfilesdv1.GetDescriptorResponse], error) {
	return c.getDescriptor.CallUnary(ctx, req)
}

// CallTool calls dotfilesd.v1.ExtensionService.CallTool.
func (c *extensionServiceClient) CallTool(ctx context.Context, req *connect.Request[dotfilesdv1.CallToolRequest]) (*connect.Response[dotfilesdv1.CallToolResponse], error) {
	return c.callTool.CallUnary(ctx, req)
}

// ExtensionServiceHandler is an implementation of the dotfilesd.v1.ExtensionService service.
type ExtensionServiceHandler interface {
	// GetDescriptor returns the plugin's capabilities (tools, metadata, CLI
	// hints). Called once at plugin load time; results are cached in the
	// daemon's plugin registry.
	GetDescriptor(context.Context, *connect.Request[dotfilesdv1.GetDescriptorRequest]) (*connect.Response[dotfilesdv1.GetDescriptorResponse], error)
	// CallTool invokes a named tool on the plugin with the given arguments.
	// The daemon proxies MCP tools/call and CLI commands to this RPC.
	CallTool(context.Context, *connect.Request[dotfilesdv1.CallToolRequest]) (*connect.Response[dotfilesdv1.CallToolResponse], error)
}

// NewExtensionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExtensionServiceHandler(svc ExtensionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	extensionServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_extension_proto.Services().ByName("ExtensionService").Methods()
	extensionServiceGetDescriptorHandler := connect.NewUnaryHandler(
		ExtensionServiceGetDescriptorProcedure,
		svc.GetDescriptor,
		connect.WithSchema(extensionServiceMethods.ByName("GetDescriptor")),
		connect.WithHandlerOptions(opts...),
	)
	extensionServiceCallToolHandler := connect.NewUnaryHandler(
		ExtensionServiceCallToolProcedure,
		svc.CallTool,
		connect.WithSchema(extensionServiceMethods.ByName("CallTool")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ExtensionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExtensionServiceGetDescriptorProcedure:
			extensionServiceGetDescriptorHandler.ServeHTTP(w, r)
		case ExtensionServiceCallToolProcedure:
			extensionServiceCallToolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExtensionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExtensionServiceHandler struct{}

func (UnimplementedExtensionServiceHandler) GetDescriptor(context.Context, *connect.Request[dotfilesdv1.GetDescriptorRequest]) (*connect.Response[dotfilesdv1.GetDescriptorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExtensionService.GetDescriptor is not implemented"))
}

func (UnimplementedExtensionServiceHandler) CallTool(context.Context, *connect.Request[dotfilesdv1.CallToolRequest]) (*connect.Response[dotfilesdv1.CallToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExtensionService.CallTool is not implemented"))
}
