// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/feedback.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InputServiceName is the fully-qualified name of the InputService service.
	InputServiceName = "dotfilesd.v1.InputService"
	// ConfirmServiceName is the fully-qualified name of the ConfirmService service.
	ConfirmServiceName = "dotfilesd.v1.ConfirmService"
	// ChooseServiceName is the fully-qualified name of the ChooseService service.
	ChooseServiceName = "dotfilesd.v1.ChooseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InputServiceRequestInputProcedure is the fully-qualified name of the InputService's RequestInput
	// RPC.
	InputServiceRequestInputProcedure = "/dotfilesd.v1.InputService/RequestInput"
	// ConfirmServiceRequestConfirmProcedure is the fully-qualified name of the ConfirmService's
	// RequestConfirm RPC.
	ConfirmServiceRequestConfirmProcedure = "/dotfilesd.v1.ConfirmService/RequestConfirm"
	// ChooseServiceRequestChooseProcedure is the fully-qualified name of the ChooseService's
	// RequestChoose RPC.
	ChooseServiceRequestChooseProcedure = "/dotfilesd.v1.ChooseService/RequestChoose"
)

// InputServiceClient is a client for the dotfilesd.v1.InputService service.
type InputServiceClient interface {
	RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error)
}

// NewInputServiceClient constructs a client for the dotfilesd.v1.InputService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInputServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InputServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inputServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("InputService").Methods()
	return &inputServiceClient{
		requestInput: connect.NewClient[dotfilesdv1.InputRequest, dotfilesdv1.InputResponse](
			httpClient,
			baseURL+InputServiceRequestInputProcedure,
			connect.WithSchema(inputServiceMethods.ByName("RequestInput")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inputServiceClient implements InputServiceClient.
type inputServiceClient struct {
	requestInput *connect.Client[dotfilesdv1.InputRequest, dotfilesdv1.InputResponse]
}

// RequestInput calls dotfilesd.v1.InputService.RequestInput.
func (c *inputServiceClient) RequestInput(ctx context.Context, req *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error) {
	return c.requestInput.CallUnary(ctx, req)
}

// InputServiceHandler is an implementation of the dotfilesd.v1.InputService service.
type InputServiceHandler interface {
	RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error)
}

// NewInputServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInputServiceHandler(svc InputServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inputServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("InputService").Methods()
	inputServiceRequestInputHandler := connect.NewUnaryHandler(
		InputServiceRequestInputProcedure,
		svc.RequestInput,
		connect.WithSchema(inputServiceMethods.ByName("RequestInput")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.InputService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InputServiceRequestInputProcedure:
			inputServiceRequestInputHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInputServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInputServiceHandler struct{}

func (UnimplementedInputServiceHandler) RequestInput(context.Context, *connect.Request[dotfilesdv1.InputRequest]) (*connect.Response[dotfilesdv1.InputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.InputService.RequestInput is not implemented"))
}

// ConfirmServiceClient is a client for the dotfilesd.v1.ConfirmService service.
type ConfirmServiceClient interface {
	RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error)
}

// NewConfirmServiceClient constructs a client for the dotfilesd.v1.ConfirmService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfirmServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfirmServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	confirmServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("ConfirmService").Methods()
	return &confirmServiceClient{
		requestConfirm: connect.NewClient[dotfilesdv1.ConfirmRequest, dotfilesdv1.ConfirmResponse](
			httpClient,
			baseURL+ConfirmServiceRequestConfirmProcedure,
			connect.WithSchema(confirmServiceMethods.ByName("RequestConfirm")),
			connect.WithClientOptions(opts...),
		),
	}
}

// confirmServiceClient implements ConfirmServiceClient.
type confirmServiceClient struct {
	requestConfirm *connect.Client[dotfilesdv1.ConfirmRequest, dotfilesdv1.ConfirmResponse]
}

// RequestConfirm calls dotfilesd.v1.ConfirmService.RequestConfirm.
func (c *confirmServiceClient) RequestConfirm(ctx context.Context, req *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error) {
	return c.requestConfirm.CallUnary(ctx, req)
}

// ConfirmServiceHandler is an implementation of the dotfilesd.v1.ConfirmService service.
type ConfirmServiceHandler interface {
	RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error)
}

// NewConfirmServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfirmServiceHandler(svc ConfirmServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	confirmServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("ConfirmService").Methods()
	confirmServiceRequestConfirmHandler := connect.NewUnaryHandler(
		ConfirmServiceRequestConfirmProcedure,
		svc.RequestConfirm,
		connect.WithSchema(confirmServiceMethods.ByName("RequestConfirm")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ConfirmService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfirmServiceRequestConfirmProcedure:
			confirmServiceRequestConfirmHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfirmServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfirmServiceHandler struct{}

func (UnimplementedConfirmServiceHandler) RequestConfirm(context.Context, *connect.Request[dotfilesdv1.ConfirmRequest]) (*connect.Response[dotfilesdv1.ConfirmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfirmService.RequestConfirm is not implemented"))
}

// ChooseServiceClient is a client for the dotfilesd.v1.ChooseService service.
type ChooseServiceClient interface {
	RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error)
}

// NewChooseServiceClient constructs a client for the dotfilesd.v1.ChooseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChooseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChooseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chooseServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("ChooseService").Methods()
	return &chooseServiceClient{
		requestChoose: connect.NewClient[dotfilesdv1.ChooseRequest, dotfilesdv1.ChooseResponse](
			httpClient,
			baseURL+ChooseServiceRequestChooseProcedure,
			connect.WithSchema(chooseServiceMethods.ByName("RequestChoose")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chooseServiceClient implements ChooseServiceClient.
type chooseServiceClient struct {
	requestChoose *connect.Client[dotfilesdv1.ChooseRequest, dotfilesdv1.ChooseResponse]
}

// RequestChoose calls dotfilesd.v1.ChooseService.RequestChoose.
func (c *chooseServiceClient) RequestChoose(ctx context.Context, req *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error) {
	return c.requestChoose.CallUnary(ctx, req)
}

// ChooseServiceHandler is an implementation of the dotfilesd.v1.ChooseService service.
type ChooseServiceHandler interface {
	RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error)
}

// NewChooseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChooseServiceHandler(svc ChooseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chooseServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_feedback_proto.Services().ByName("ChooseService").Methods()
	chooseServiceRequestChooseHandler := connect.NewUnaryHandler(
		ChooseServiceRequestChooseProcedure,
		svc.RequestChoose,
		connect.WithSchema(chooseServiceMethods.ByName("RequestChoose")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ChooseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChooseServiceRequestChooseProcedure:
			chooseServiceRequestChooseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChooseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChooseServiceHandler struct{}

func (UnimplementedChooseServiceHandler) RequestChoose(context.Context, *connect.Request[dotfilesdv1.ChooseRequest]) (*connect.Response[dotfilesdv1.ChooseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ChooseService.RequestChoose is not implemented"))
}
