// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/log.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LogServiceName is the fully-qualified name of the LogService service.
	LogServiceName = "dotfilesd.v1.LogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LogServiceLogProcedure is the fully-qualified name of the LogService's Log RPC.
	LogServiceLogProcedure = "/dotfilesd.v1.LogService/Log"
)

// LogServiceClient is a client for the dotfilesd.v1.LogService service.
type LogServiceClient interface {
	// Log submits a log entry. The daemon routes it through its logging system
	// with the caller's identity as the logger module.
	Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error)
}

// NewLogServiceClient constructs a client for the dotfilesd.v1.LogService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	logServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_log_proto.Services().ByName("LogService").Methods()
	return &logServiceClient{
		log: connect.NewClient[dotfilesdv1.LogRequest, dotfilesdv1.LogResponse](
			httpClient,
			baseURL+LogServiceLogProcedure,
			connect.WithSchema(logServiceMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
	}
}

// logServiceClient implements LogServiceClient.
type logServiceClient struct {
	log *connect.Client[dotfilesdv1.LogRequest, dotfilesdv1.LogResponse]
}

// Log calls dotfilesd.v1.LogService.Log.
func (c *logServiceClient) Log(ctx context.Context, req *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error) {
	return c.log.CallUnary(ctx, req)
}

// LogServiceHandler is an implementation of the dotfilesd.v1.LogService service.
type LogServiceHandler interface {
	// Log submits a log entry. The daemon routes it through its logging system
	// with the caller's identity as the logger module.
	Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error)
}

// NewLogServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLogServiceHandler(svc LogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	logServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_log_proto.Services().ByName("LogService").Methods()
	logServiceLogHandler := connect.NewUnaryHandler(
		LogServiceLogProcedure,
		svc.Log,
		connect.WithSchema(logServiceMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.LogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LogServiceLogProcedure:
			logServiceLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLogServiceHandler struct{}

func (UnimplementedLogServiceHandler) Log(context.Context, *connect.Request[dotfilesdv1.LogRequest]) (*connect.Response[dotfilesdv1.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.LogService.Log is not implemented"))
}
