// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/plugin.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginServiceName is the fully-qualified name of the PluginService service.
	PluginServiceName = "dotfilesd.v1.PluginService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginServiceListPluginsProcedure is the fully-qualified name of the PluginService's ListPlugins
	// RPC.
	PluginServiceListPluginsProcedure = "/dotfilesd.v1.PluginService/ListPlugins"
	// PluginServiceListPluginTreeProcedure is the fully-qualified name of the PluginService's
	// ListPluginTree RPC.
	PluginServiceListPluginTreeProcedure = "/dotfilesd.v1.PluginService/ListPluginTree"
	// PluginServiceCallPluginToolProcedure is the fully-qualified name of the PluginService's
	// CallPluginTool RPC.
	PluginServiceCallPluginToolProcedure = "/dotfilesd.v1.PluginService/CallPluginTool"
)

// PluginServiceClient is a client for the dotfilesd.v1.PluginService service.
type PluginServiceClient interface {
	// ListPlugins returns descriptors for all loaded plugins (flat list).
	ListPlugins(context.Context, *connect.Request[dotfilesdv1.ListPluginsRequest]) (*connect.Response[dotfilesdv1.ListPluginsResponse], error)
	// ListPluginTree returns the plugin directory hierarchy with loaded
	// plugin descriptors at leaf nodes.
	ListPluginTree(context.Context, *connect.Request[dotfilesdv1.ListPluginTreeRequest]) (*connect.Response[dotfilesdv1.ListPluginTreeResponse], error)
	// CallPluginTool invokes a tool on a loaded plugin.
	// Returns a stream of output chunks (stdout/stderr) followed by a
	// final done message indicating completion or error.
	CallPluginTool(context.Context, *connect.Request[dotfilesdv1.CallPluginToolRequest]) (*connect.ServerStreamForClient[dotfilesdv1.CallPluginToolResponse], error)
}

// NewPluginServiceClient constructs a client for the dotfilesd.v1.PluginService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_plugin_proto.Services().ByName("PluginService").Methods()
	return &pluginServiceClient{
		listPlugins: connect.NewClient[dotfilesdv1.ListPluginsRequest, dotfilesdv1.ListPluginsResponse](
			httpClient,
			baseURL+PluginServiceListPluginsProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ListPlugins")),
			connect.WithClientOptions(opts...),
		),
		listPluginTree: connect.NewClient[dotfilesdv1.ListPluginTreeRequest, dotfilesdv1.ListPluginTreeResponse](
			httpClient,
			baseURL+PluginServiceListPluginTreeProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ListPluginTree")),
			connect.WithClientOptions(opts...),
		),
		callPluginTool: connect.NewClient[dotfilesdv1.CallPluginToolRequest, dotfilesdv1.CallPluginToolResponse](
			httpClient,
			baseURL+PluginServiceCallPluginToolProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("CallPluginTool")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginServiceClient implements PluginServiceClient.
type pluginServiceClient struct {
	listPlugins    *connect.Client[dotfilesdv1.ListPluginsRequest, dotfilesdv1.ListPluginsResponse]
	listPluginTree *connect.Client[dotfilesdv1.ListPluginTreeRequest, dotfilesdv1.ListPluginTreeResponse]
	callPluginTool *connect.Client[dotfilesdv1.CallPluginToolRequest, dotfilesdv1.CallPluginToolResponse]
}

// ListPlugins calls dotfilesd.v1.PluginService.ListPlugins.
func (c *pluginServiceClient) ListPlugins(ctx context.Context, req *connect.Request[dotfilesdv1.ListPluginsRequest]) (*connect.Response[dotfilesdv1.ListPluginsResponse], error) {
	return c.listPlugins.CallUnary(ctx, req)
}

// ListPluginTree calls dotfilesd.v1.PluginService.ListPluginTree.
func (c *pluginServiceClient) ListPluginTree(ctx context.Context, req *connect.Request[dotfilesdv1.ListPluginTreeRequest]) (*connect.Response[dotfilesdv1.ListPluginTreeResponse], error) {
	return c.listPluginTree.CallUnary(ctx, req)
}

// CallPluginTool calls dotfilesd.v1.PluginService.CallPluginTool.
func (c *pluginServiceClient) CallPluginTool(ctx context.Context, req *connect.Request[dotfilesdv1.CallPluginToolRequest]) (*connect.ServerStreamForClient[dotfilesdv1.CallPluginToolResponse], error) {
	return c.callPluginTool.CallServerStream(ctx, req)
}

// PluginServiceHandler is an implementation of the dotfilesd.v1.PluginService service.
type PluginServiceHandler interface {
	// ListPlugins returns descriptors for all loaded plugins (flat list).
	ListPlugins(context.Context, *connect.Request[dotfilesdv1.ListPluginsRequest]) (*connect.Response[dotfilesdv1.ListPluginsResponse], error)
	// ListPluginTree returns the plugin directory hierarchy with loaded
	// plugin descriptors at leaf nodes.
	ListPluginTree(context.Context, *connect.Request[dotfilesdv1.ListPluginTreeRequest]) (*connect.Response[dotfilesdv1.ListPluginTreeResponse], error)
	// CallPluginTool invokes a tool on a loaded plugin.
	// Returns a stream of output chunks (stdout/stderr) followed by a
	// final done message indicating completion or error.
	CallPluginTool(context.Context, *connect.Request[dotfilesdv1.CallPluginToolRequest], *connect.ServerStream[dotfilesdv1.CallPluginToolResponse]) error
}

// NewPluginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginServiceHandler(svc PluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_plugin_proto.Services().ByName("PluginService").Methods()
	pluginServiceListPluginsHandler := connect.NewUnaryHandler(
		PluginServiceListPluginsProcedure,
		svc.ListPlugins,
		connect.WithSchema(pluginServiceMethods.ByName("ListPlugins")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceListPluginTreeHandler := connect.NewUnaryHandler(
		PluginServiceListPluginTreeProcedure,
		svc.ListPluginTree,
		connect.WithSchema(pluginServiceMethods.ByName("ListPluginTree")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceCallPluginToolHandler := connect.NewServerStreamHandler(
		PluginServiceCallPluginToolProcedure,
		svc.CallPluginTool,
		connect.WithSchema(pluginServiceMethods.ByName("CallPluginTool")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.PluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginServiceListPluginsProcedure:
			pluginServiceListPluginsHandler.ServeHTTP(w, r)
		case PluginServiceListPluginTreeProcedure:
			pluginServiceListPluginTreeHandler.ServeHTTP(w, r)
		case PluginServiceCallPluginToolProcedure:
			pluginServiceCallPluginToolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginServiceHandler struct{}

func (UnimplementedPluginServiceHandler) ListPlugins(context.Context, *connect.Request[dotfilesdv1.ListPluginsRequest]) (*connect.Response[dotfilesdv1.ListPluginsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.PluginService.ListPlugins is not implemented"))
}

func (UnimplementedPluginServiceHandler) ListPluginTree(context.Context, *connect.Request[dotfilesdv1.ListPluginTreeRequest]) (*connect.Response[dotfilesdv1.ListPluginTreeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.PluginService.ListPluginTree is not implemented"))
}

func (UnimplementedPluginServiceHandler) CallPluginTool(context.Context, *connect.Request[dotfilesdv1.CallPluginToolRequest], *connect.ServerStream[dotfilesdv1.CallPluginToolResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.PluginService.CallPluginTool is not implemented"))
}
