// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/service.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "dotfilesd.v1.SystemService"
	// DotfilesServiceName is the fully-qualified name of the DotfilesService service.
	DotfilesServiceName = "dotfilesd.v1.DotfilesService"
	// ExecServiceName is the fully-qualified name of the ExecService service.
	ExecServiceName = "dotfilesd.v1.ExecService"
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "dotfilesd.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServicePingProcedure is the fully-qualified name of the SystemService's Ping RPC.
	SystemServicePingProcedure = "/dotfilesd.v1.SystemService/Ping"
	// SystemServiceSystemInfoProcedure is the fully-qualified name of the SystemService's SystemInfo
	// RPC.
	SystemServiceSystemInfoProcedure = "/dotfilesd.v1.SystemService/SystemInfo"
	// SystemServiceSudoMethodsProcedure is the fully-qualified name of the SystemService's SudoMethods
	// RPC.
	SystemServiceSudoMethodsProcedure = "/dotfilesd.v1.SystemService/SudoMethods"
	// DotfilesServiceStatusProcedure is the fully-qualified name of the DotfilesService's Status RPC.
	DotfilesServiceStatusProcedure = "/dotfilesd.v1.DotfilesService/Status"
	// DotfilesServiceGitProcedure is the fully-qualified name of the DotfilesService's Git RPC.
	DotfilesServiceGitProcedure = "/dotfilesd.v1.DotfilesService/Git"
	// ExecServiceExecProcedure is the fully-qualified name of the ExecService's Exec RPC.
	ExecServiceExecProcedure = "/dotfilesd.v1.ExecService/Exec"
	// ExecServiceSudoExecProcedure is the fully-qualified name of the ExecService's SudoExec RPC.
	ExecServiceSudoExecProcedure = "/dotfilesd.v1.ExecService/SudoExec"
	// ConfigServiceReloadProcedure is the fully-qualified name of the ConfigService's Reload RPC.
	ConfigServiceReloadProcedure = "/dotfilesd.v1.ConfigService/Reload"
	// ConfigServiceReconfigureProcedure is the fully-qualified name of the ConfigService's Reconfigure
	// RPC.
	ConfigServiceReconfigureProcedure = "/dotfilesd.v1.ConfigService/Reconfigure"
	// ConfigServiceRestartProcedure is the fully-qualified name of the ConfigService's Restart RPC.
	ConfigServiceRestartProcedure = "/dotfilesd.v1.ConfigService/Restart"
)

// SystemServiceClient is a client for the dotfilesd.v1.SystemService service.
type SystemServiceClient interface {
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewSystemServiceClient constructs a client for the dotfilesd.v1.SystemService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		ping: connect.NewClient[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse](
			httpClient,
			baseURL+SystemServicePingProcedure,
			connect.WithSchema(systemServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		systemInfo: connect.NewClient[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse](
			httpClient,
			baseURL+SystemServiceSystemInfoProcedure,
			connect.WithSchema(systemServiceMethods.ByName("SystemInfo")),
			connect.WithClientOptions(opts...),
		),
		sudoMethods: connect.NewClient[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse](
			httpClient,
			baseURL+SystemServiceSudoMethodsProcedure,
			connect.WithSchema(systemServiceMethods.ByName("SudoMethods")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	ping        *connect.Client[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse]
	systemInfo  *connect.Client[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse]
	sudoMethods *connect.Client[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse]
}

// Ping calls dotfilesd.v1.SystemService.Ping.
func (c *systemServiceClient) Ping(ctx context.Context, req *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SystemInfo calls dotfilesd.v1.SystemService.SystemInfo.
func (c *systemServiceClient) SystemInfo(ctx context.Context, req *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return c.systemInfo.CallUnary(ctx, req)
}

// SudoMethods calls dotfilesd.v1.SystemService.SudoMethods.
func (c *systemServiceClient) SudoMethods(ctx context.Context, req *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return c.sudoMethods.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the dotfilesd.v1.SystemService service.
type SystemServiceHandler interface {
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("SystemService").Methods()
	systemServicePingHandler := connect.NewUnaryHandler(
		SystemServicePingProcedure,
		svc.Ping,
		connect.WithSchema(systemServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceSystemInfoHandler := connect.NewUnaryHandler(
		SystemServiceSystemInfoProcedure,
		svc.SystemInfo,
		connect.WithSchema(systemServiceMethods.ByName("SystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceSudoMethodsHandler := connect.NewUnaryHandler(
		SystemServiceSudoMethodsProcedure,
		svc.SudoMethods,
		connect.WithSchema(systemServiceMethods.ByName("SudoMethods")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServicePingProcedure:
			systemServicePingHandler.ServeHTTP(w, r)
		case SystemServiceSystemInfoProcedure:
			systemServiceSystemInfoHandler.ServeHTTP(w, r)
		case SystemServiceSudoMethodsProcedure:
			systemServiceSudoMethodsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.Ping is not implemented"))
}

func (UnimplementedSystemServiceHandler) SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.SystemInfo is not implemented"))
}

func (UnimplementedSystemServiceHandler) SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.SudoMethods is not implemented"))
}

// DotfilesServiceClient is a client for the dotfilesd.v1.DotfilesService service.
type DotfilesServiceClient interface {
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
}

// NewDotfilesServiceClient constructs a client for the dotfilesd.v1.DotfilesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDotfilesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DotfilesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("DotfilesService").Methods()
	return &dotfilesServiceClient{
		status: connect.NewClient[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse](
			httpClient,
			baseURL+DotfilesServiceStatusProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		git: connect.NewClient[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse](
			httpClient,
			baseURL+DotfilesServiceGitProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dotfilesServiceClient implements DotfilesServiceClient.
type dotfilesServiceClient struct {
	status *connect.Client[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse]
	git    *connect.Client[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse]
}

// Status calls dotfilesd.v1.DotfilesService.Status.
func (c *dotfilesServiceClient) Status(ctx context.Context, req *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Git calls dotfilesd.v1.DotfilesService.Git.
func (c *dotfilesServiceClient) Git(ctx context.Context, req *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return c.git.CallUnary(ctx, req)
}

// DotfilesServiceHandler is an implementation of the dotfilesd.v1.DotfilesService service.
type DotfilesServiceHandler interface {
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
}

// NewDotfilesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDotfilesServiceHandler(svc DotfilesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("DotfilesService").Methods()
	dotfilesServiceStatusHandler := connect.NewUnaryHandler(
		DotfilesServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceGitHandler := connect.NewUnaryHandler(
		DotfilesServiceGitProcedure,
		svc.Git,
		connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.DotfilesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DotfilesServiceStatusProcedure:
			dotfilesServiceStatusHandler.ServeHTTP(w, r)
		case DotfilesServiceGitProcedure:
			dotfilesServiceGitHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDotfilesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDotfilesServiceHandler struct{}

func (UnimplementedDotfilesServiceHandler) Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Status is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Git is not implemented"))
}

// ExecServiceClient is a client for the dotfilesd.v1.ExecService service.
type ExecServiceClient interface {
	// Simple unary exec (no sudo).
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Challenge-response sudo. The first call omits password; if the daemon
	// needs auth it returns AuthChallenge. The client retries with the password.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error)
}

// NewExecServiceClient constructs a client for the dotfilesd.v1.ExecService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	execServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("ExecService").Methods()
	return &execServiceClient{
		exec: connect.NewClient[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse](
			httpClient,
			baseURL+ExecServiceExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		sudoExec: connect.NewClient[dotfilesdv1.SudoExecRequest, dotfilesdv1.SudoExecResponse](
			httpClient,
			baseURL+ExecServiceSudoExecProcedure,
			connect.WithSchema(execServiceMethods.ByName("SudoExec")),
			connect.WithClientOptions(opts...),
		),
	}
}

// execServiceClient implements ExecServiceClient.
type execServiceClient struct {
	exec     *connect.Client[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse]
	sudoExec *connect.Client[dotfilesdv1.SudoExecRequest, dotfilesdv1.SudoExecResponse]
}

// Exec calls dotfilesd.v1.ExecService.Exec.
func (c *execServiceClient) Exec(ctx context.Context, req *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// SudoExec calls dotfilesd.v1.ExecService.SudoExec.
func (c *execServiceClient) SudoExec(ctx context.Context, req *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error) {
	return c.sudoExec.CallUnary(ctx, req)
}

// ExecServiceHandler is an implementation of the dotfilesd.v1.ExecService service.
type ExecServiceHandler interface {
	// Simple unary exec (no sudo).
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Challenge-response sudo. The first call omits password; if the daemon
	// needs auth it returns AuthChallenge. The client retries with the password.
	SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error)
}

// NewExecServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecServiceHandler(svc ExecServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	execServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("ExecService").Methods()
	execServiceExecHandler := connect.NewUnaryHandler(
		ExecServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(execServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	execServiceSudoExecHandler := connect.NewUnaryHandler(
		ExecServiceSudoExecProcedure,
		svc.SudoExec,
		connect.WithSchema(execServiceMethods.ByName("SudoExec")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ExecService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecServiceExecProcedure:
			execServiceExecHandler.ServeHTTP(w, r)
		case ExecServiceSudoExecProcedure:
			execServiceSudoExecHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecServiceHandler struct{}

func (UnimplementedExecServiceHandler) Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecService.Exec is not implemented"))
}

func (UnimplementedExecServiceHandler) SudoExec(context.Context, *connect.Request[dotfilesdv1.SudoExecRequest]) (*connect.Response[dotfilesdv1.SudoExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ExecService.SudoExec is not implemented"))
}

// ConfigServiceClient is a client for the dotfilesd.v1.ConfigService service.
type ConfigServiceClient interface {
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error)
	Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error)
}

// NewConfigServiceClient constructs a client for the dotfilesd.v1.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		reload: connect.NewClient[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse](
			httpClient,
			baseURL+ConfigServiceReloadProcedure,
			connect.WithSchema(configServiceMethods.ByName("Reload")),
			connect.WithClientOptions(opts...),
		),
		reconfigure: connect.NewClient[dotfilesdv1.ReconfigureRequest, dotfilesdv1.ReconfigureResponse](
			httpClient,
			baseURL+ConfigServiceReconfigureProcedure,
			connect.WithSchema(configServiceMethods.ByName("Reconfigure")),
			connect.WithClientOptions(opts...),
		),
		restart: connect.NewClient[dotfilesdv1.RestartRequest, dotfilesdv1.RestartResponse](
			httpClient,
			baseURL+ConfigServiceRestartProcedure,
			connect.WithSchema(configServiceMethods.ByName("Restart")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	reload      *connect.Client[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse]
	reconfigure *connect.Client[dotfilesdv1.ReconfigureRequest, dotfilesdv1.ReconfigureResponse]
	restart     *connect.Client[dotfilesdv1.RestartRequest, dotfilesdv1.RestartResponse]
}

// Reload calls dotfilesd.v1.ConfigService.Reload.
func (c *configServiceClient) Reload(ctx context.Context, req *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return c.reload.CallUnary(ctx, req)
}

// Reconfigure calls dotfilesd.v1.ConfigService.Reconfigure.
func (c *configServiceClient) Reconfigure(ctx context.Context, req *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error) {
	return c.reconfigure.CallUnary(ctx, req)
}

// Restart calls dotfilesd.v1.ConfigService.Restart.
func (c *configServiceClient) Restart(ctx context.Context, req *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error) {
	return c.restart.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the dotfilesd.v1.ConfigService service.
type ConfigServiceHandler interface {
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error)
	Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("ConfigService").Methods()
	configServiceReloadHandler := connect.NewUnaryHandler(
		ConfigServiceReloadProcedure,
		svc.Reload,
		connect.WithSchema(configServiceMethods.ByName("Reload")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceReconfigureHandler := connect.NewUnaryHandler(
		ConfigServiceReconfigureProcedure,
		svc.Reconfigure,
		connect.WithSchema(configServiceMethods.ByName("Reconfigure")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceRestartHandler := connect.NewUnaryHandler(
		ConfigServiceRestartProcedure,
		svc.Restart,
		connect.WithSchema(configServiceMethods.ByName("Restart")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceReloadProcedure:
			configServiceReloadHandler.ServeHTTP(w, r)
		case ConfigServiceReconfigureProcedure:
			configServiceReconfigureHandler.ServeHTTP(w, r)
		case ConfigServiceRestartProcedure:
			configServiceRestartHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Reload is not implemented"))
}

func (UnimplementedConfigServiceHandler) Reconfigure(context.Context, *connect.Request[dotfilesdv1.ReconfigureRequest]) (*connect.Response[dotfilesdv1.ReconfigureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Reconfigure is not implemented"))
}

func (UnimplementedConfigServiceHandler) Restart(context.Context, *connect.Request[dotfilesdv1.RestartRequest]) (*connect.Response[dotfilesdv1.RestartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.ConfigService.Restart is not implemented"))
}
