// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/service.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DotfilesServiceName is the fully-qualified name of the DotfilesService service.
	DotfilesServiceName = "dotfilesd.v1.DotfilesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DotfilesServicePingProcedure is the fully-qualified name of the DotfilesService's Ping RPC.
	DotfilesServicePingProcedure = "/dotfilesd.v1.DotfilesService/Ping"
	// DotfilesServiceStatusProcedure is the fully-qualified name of the DotfilesService's Status RPC.
	DotfilesServiceStatusProcedure = "/dotfilesd.v1.DotfilesService/Status"
	// DotfilesServiceExecProcedure is the fully-qualified name of the DotfilesService's Exec RPC.
	DotfilesServiceExecProcedure = "/dotfilesd.v1.DotfilesService/Exec"
	// DotfilesServiceReloadProcedure is the fully-qualified name of the DotfilesService's Reload RPC.
	DotfilesServiceReloadProcedure = "/dotfilesd.v1.DotfilesService/Reload"
	// DotfilesServiceGitProcedure is the fully-qualified name of the DotfilesService's Git RPC.
	DotfilesServiceGitProcedure = "/dotfilesd.v1.DotfilesService/Git"
	// DotfilesServiceSystemInfoProcedure is the fully-qualified name of the DotfilesService's
	// SystemInfo RPC.
	DotfilesServiceSystemInfoProcedure = "/dotfilesd.v1.DotfilesService/SystemInfo"
	// DotfilesServiceSudoMethodsProcedure is the fully-qualified name of the DotfilesService's
	// SudoMethods RPC.
	DotfilesServiceSudoMethodsProcedure = "/dotfilesd.v1.DotfilesService/SudoMethods"
)

// DotfilesServiceClient is a client for the dotfilesd.v1.DotfilesService service.
type DotfilesServiceClient interface {
	// General
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	// Command execution
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Config reload
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	// Git operations on the dotfiles repo
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
	// System info
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	// Sudo method negotiation
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewDotfilesServiceClient constructs a client for the dotfilesd.v1.DotfilesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDotfilesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DotfilesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("DotfilesService").Methods()
	return &dotfilesServiceClient{
		ping: connect.NewClient[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse](
			httpClient,
			baseURL+DotfilesServicePingProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse](
			httpClient,
			baseURL+DotfilesServiceStatusProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		exec: connect.NewClient[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse](
			httpClient,
			baseURL+DotfilesServiceExecProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		reload: connect.NewClient[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse](
			httpClient,
			baseURL+DotfilesServiceReloadProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Reload")),
			connect.WithClientOptions(opts...),
		),
		git: connect.NewClient[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse](
			httpClient,
			baseURL+DotfilesServiceGitProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
			connect.WithClientOptions(opts...),
		),
		systemInfo: connect.NewClient[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse](
			httpClient,
			baseURL+DotfilesServiceSystemInfoProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("SystemInfo")),
			connect.WithClientOptions(opts...),
		),
		sudoMethods: connect.NewClient[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse](
			httpClient,
			baseURL+DotfilesServiceSudoMethodsProcedure,
			connect.WithSchema(dotfilesServiceMethods.ByName("SudoMethods")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dotfilesServiceClient implements DotfilesServiceClient.
type dotfilesServiceClient struct {
	ping        *connect.Client[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse]
	status      *connect.Client[dotfilesdv1.StatusRequest, dotfilesdv1.StatusResponse]
	exec        *connect.Client[dotfilesdv1.ExecRequest, dotfilesdv1.ExecResponse]
	reload      *connect.Client[dotfilesdv1.ReloadRequest, dotfilesdv1.ReloadResponse]
	git         *connect.Client[dotfilesdv1.GitRequest, dotfilesdv1.GitResponse]
	systemInfo  *connect.Client[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse]
	sudoMethods *connect.Client[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse]
}

// Ping calls dotfilesd.v1.DotfilesService.Ping.
func (c *dotfilesServiceClient) Ping(ctx context.Context, req *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// Status calls dotfilesd.v1.DotfilesService.Status.
func (c *dotfilesServiceClient) Status(ctx context.Context, req *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Exec calls dotfilesd.v1.DotfilesService.Exec.
func (c *dotfilesServiceClient) Exec(ctx context.Context, req *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// Reload calls dotfilesd.v1.DotfilesService.Reload.
func (c *dotfilesServiceClient) Reload(ctx context.Context, req *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return c.reload.CallUnary(ctx, req)
}

// Git calls dotfilesd.v1.DotfilesService.Git.
func (c *dotfilesServiceClient) Git(ctx context.Context, req *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return c.git.CallUnary(ctx, req)
}

// SystemInfo calls dotfilesd.v1.DotfilesService.SystemInfo.
func (c *dotfilesServiceClient) SystemInfo(ctx context.Context, req *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return c.systemInfo.CallUnary(ctx, req)
}

// SudoMethods calls dotfilesd.v1.DotfilesService.SudoMethods.
func (c *dotfilesServiceClient) SudoMethods(ctx context.Context, req *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return c.sudoMethods.CallUnary(ctx, req)
}

// DotfilesServiceHandler is an implementation of the dotfilesd.v1.DotfilesService service.
type DotfilesServiceHandler interface {
	// General
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error)
	// Command execution
	Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error)
	// Config reload
	Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error)
	// Git operations on the dotfiles repo
	Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error)
	// System info
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	// Sudo method negotiation
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewDotfilesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDotfilesServiceHandler(svc DotfilesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dotfilesServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_service_proto.Services().ByName("DotfilesService").Methods()
	dotfilesServicePingHandler := connect.NewUnaryHandler(
		DotfilesServicePingProcedure,
		svc.Ping,
		connect.WithSchema(dotfilesServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceStatusHandler := connect.NewUnaryHandler(
		DotfilesServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(dotfilesServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceExecHandler := connect.NewUnaryHandler(
		DotfilesServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(dotfilesServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceReloadHandler := connect.NewUnaryHandler(
		DotfilesServiceReloadProcedure,
		svc.Reload,
		connect.WithSchema(dotfilesServiceMethods.ByName("Reload")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceGitHandler := connect.NewUnaryHandler(
		DotfilesServiceGitProcedure,
		svc.Git,
		connect.WithSchema(dotfilesServiceMethods.ByName("Git")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceSystemInfoHandler := connect.NewUnaryHandler(
		DotfilesServiceSystemInfoProcedure,
		svc.SystemInfo,
		connect.WithSchema(dotfilesServiceMethods.ByName("SystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	dotfilesServiceSudoMethodsHandler := connect.NewUnaryHandler(
		DotfilesServiceSudoMethodsProcedure,
		svc.SudoMethods,
		connect.WithSchema(dotfilesServiceMethods.ByName("SudoMethods")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.DotfilesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DotfilesServicePingProcedure:
			dotfilesServicePingHandler.ServeHTTP(w, r)
		case DotfilesServiceStatusProcedure:
			dotfilesServiceStatusHandler.ServeHTTP(w, r)
		case DotfilesServiceExecProcedure:
			dotfilesServiceExecHandler.ServeHTTP(w, r)
		case DotfilesServiceReloadProcedure:
			dotfilesServiceReloadHandler.ServeHTTP(w, r)
		case DotfilesServiceGitProcedure:
			dotfilesServiceGitHandler.ServeHTTP(w, r)
		case DotfilesServiceSystemInfoProcedure:
			dotfilesServiceSystemInfoHandler.ServeHTTP(w, r)
		case DotfilesServiceSudoMethodsProcedure:
			dotfilesServiceSudoMethodsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDotfilesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDotfilesServiceHandler struct{}

func (UnimplementedDotfilesServiceHandler) Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Ping is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Status(context.Context, *connect.Request[dotfilesdv1.StatusRequest]) (*connect.Response[dotfilesdv1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Status is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Exec(context.Context, *connect.Request[dotfilesdv1.ExecRequest]) (*connect.Response[dotfilesdv1.ExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Exec is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Reload(context.Context, *connect.Request[dotfilesdv1.ReloadRequest]) (*connect.Response[dotfilesdv1.ReloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Reload is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) Git(context.Context, *connect.Request[dotfilesdv1.GitRequest]) (*connect.Response[dotfilesdv1.GitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.Git is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.SystemInfo is not implemented"))
}

func (UnimplementedDotfilesServiceHandler) SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.DotfilesService.SudoMethods is not implemented"))
}
