// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/dotfilesd/v1/dotfilesdv1/system.proto

package dotfilesdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	dotfilesdv1 "dotfilesd/proto/dotfilesd/v1/dotfilesdv1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "dotfilesd.v1.SystemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServicePingProcedure is the fully-qualified name of the SystemService's Ping RPC.
	SystemServicePingProcedure = "/dotfilesd.v1.SystemService/Ping"
	// SystemServiceSystemInfoProcedure is the fully-qualified name of the SystemService's SystemInfo
	// RPC.
	SystemServiceSystemInfoProcedure = "/dotfilesd.v1.SystemService/SystemInfo"
	// SystemServiceSudoMethodsProcedure is the fully-qualified name of the SystemService's SudoMethods
	// RPC.
	SystemServiceSudoMethodsProcedure = "/dotfilesd.v1.SystemService/SudoMethods"
)

// SystemServiceClient is a client for the dotfilesd.v1.SystemService service.
type SystemServiceClient interface {
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewSystemServiceClient constructs a client for the dotfilesd.v1.SystemService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_system_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		ping: connect.NewClient[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse](
			httpClient,
			baseURL+SystemServicePingProcedure,
			connect.WithSchema(systemServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		systemInfo: connect.NewClient[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse](
			httpClient,
			baseURL+SystemServiceSystemInfoProcedure,
			connect.WithSchema(systemServiceMethods.ByName("SystemInfo")),
			connect.WithClientOptions(opts...),
		),
		sudoMethods: connect.NewClient[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse](
			httpClient,
			baseURL+SystemServiceSudoMethodsProcedure,
			connect.WithSchema(systemServiceMethods.ByName("SudoMethods")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	ping        *connect.Client[dotfilesdv1.PingRequest, dotfilesdv1.PingResponse]
	systemInfo  *connect.Client[dotfilesdv1.SystemInfoRequest, dotfilesdv1.SystemInfoResponse]
	sudoMethods *connect.Client[dotfilesdv1.SudoMethodsRequest, dotfilesdv1.SudoMethodsResponse]
}

// Ping calls dotfilesd.v1.SystemService.Ping.
func (c *systemServiceClient) Ping(ctx context.Context, req *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SystemInfo calls dotfilesd.v1.SystemService.SystemInfo.
func (c *systemServiceClient) SystemInfo(ctx context.Context, req *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return c.systemInfo.CallUnary(ctx, req)
}

// SudoMethods calls dotfilesd.v1.SystemService.SudoMethods.
func (c *systemServiceClient) SudoMethods(ctx context.Context, req *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return c.sudoMethods.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the dotfilesd.v1.SystemService service.
type SystemServiceHandler interface {
	Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error)
	SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error)
	SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := dotfilesdv1.File_proto_dotfilesd_v1_dotfilesdv1_system_proto.Services().ByName("SystemService").Methods()
	systemServicePingHandler := connect.NewUnaryHandler(
		SystemServicePingProcedure,
		svc.Ping,
		connect.WithSchema(systemServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceSystemInfoHandler := connect.NewUnaryHandler(
		SystemServiceSystemInfoProcedure,
		svc.SystemInfo,
		connect.WithSchema(systemServiceMethods.ByName("SystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	systemServiceSudoMethodsHandler := connect.NewUnaryHandler(
		SystemServiceSudoMethodsProcedure,
		svc.SudoMethods,
		connect.WithSchema(systemServiceMethods.ByName("SudoMethods")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dotfilesd.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServicePingProcedure:
			systemServicePingHandler.ServeHTTP(w, r)
		case SystemServiceSystemInfoProcedure:
			systemServiceSystemInfoHandler.ServeHTTP(w, r)
		case SystemServiceSudoMethodsProcedure:
			systemServiceSudoMethodsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) Ping(context.Context, *connect.Request[dotfilesdv1.PingRequest]) (*connect.Response[dotfilesdv1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.Ping is not implemented"))
}

func (UnimplementedSystemServiceHandler) SystemInfo(context.Context, *connect.Request[dotfilesdv1.SystemInfoRequest]) (*connect.Response[dotfilesdv1.SystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.SystemInfo is not implemented"))
}

func (UnimplementedSystemServiceHandler) SudoMethods(context.Context, *connect.Request[dotfilesdv1.SudoMethodsRequest]) (*connect.Response[dotfilesdv1.SudoMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dotfilesd.v1.SystemService.SudoMethods is not implemented"))
}
