// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/htop/htop.proto

package htopconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	htop "plugins/htop/proto/htop"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HtopServiceName is the fully-qualified name of the HtopService service.
	HtopServiceName = "htop.HtopService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HtopServiceOpenProcedure is the fully-qualified name of the HtopService's Open RPC.
	HtopServiceOpenProcedure = "/htop.HtopService/Open"
)

// HtopServiceClient is a client for the htop.HtopService service.
type HtopServiceClient interface {
	Open(context.Context, *connect.Request[htop.OpenRequest]) (*connect.Response[htop.OpenResponse], error)
}

// NewHtopServiceClient constructs a client for the htop.HtopService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHtopServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HtopServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	htopServiceMethods := htop.File_proto_htop_htop_proto.Services().ByName("HtopService").Methods()
	return &htopServiceClient{
		open: connect.NewClient[htop.OpenRequest, htop.OpenResponse](
			httpClient,
			baseURL+HtopServiceOpenProcedure,
			connect.WithSchema(htopServiceMethods.ByName("Open")),
			connect.WithClientOptions(opts...),
		),
	}
}

// htopServiceClient implements HtopServiceClient.
type htopServiceClient struct {
	open *connect.Client[htop.OpenRequest, htop.OpenResponse]
}

// Open calls htop.HtopService.Open.
func (c *htopServiceClient) Open(ctx context.Context, req *connect.Request[htop.OpenRequest]) (*connect.Response[htop.OpenResponse], error) {
	return c.open.CallUnary(ctx, req)
}

// HtopServiceHandler is an implementation of the htop.HtopService service.
type HtopServiceHandler interface {
	Open(context.Context, *connect.Request[htop.OpenRequest]) (*connect.Response[htop.OpenResponse], error)
}

// NewHtopServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHtopServiceHandler(svc HtopServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	htopServiceMethods := htop.File_proto_htop_htop_proto.Services().ByName("HtopService").Methods()
	htopServiceOpenHandler := connect.NewUnaryHandler(
		HtopServiceOpenProcedure,
		svc.Open,
		connect.WithSchema(htopServiceMethods.ByName("Open")),
		connect.WithHandlerOptions(opts...),
	)
	return "/htop.HtopService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HtopServiceOpenProcedure:
			htopServiceOpenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHtopServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHtopServiceHandler struct{}

func (UnimplementedHtopServiceHandler) Open(context.Context, *connect.Request[htop.OpenRequest]) (*connect.Response[htop.OpenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("htop.HtopService.Open is not implemented"))
}
