# dotfilesd daemon configuration
port: 9105
log:
  dir: /home/manu343726/dotfilesd/logs
  level: trace  # trace | debug | info | warn | error
  max_size_mb: 10
  max_backups: 5
  max_age_days: 30

# Plugin system
plugins_dir: ~/.config/dotfilesd/plugins
plugin_cache_dir: ~/.cache/dotfilesd/plugins
